Dali::Ui::Integration::LabelImpl
Signal<void(View, const Dali::String&)> Dali::Ui::Integration::LabelImpl::mAnchorClickedSignal
Signal<void(View, float, float)> Dali::Ui::Integration::LabelImpl::mAsyncRenderFinishedSignal
Signal<void(View, float, float)> Dali::Ui::Integration::LabelImpl::mAsyncNaturalSizeComputedSignal
Signal<void(View, float, float)> Dali::Ui::Integration::LabelImpl::mAsyncHeightForWidthComputedSignal
std::unordered_map<Dali::Property::Index, Dali::String> Dali::Ui::Integration::LabelImpl::mVariationIndexMap
WeakHandle<Ui::View> Dali::Ui::Integration::LabelImpl::mMaskSourceView
Visual::Base Dali::Ui::Integration::LabelImpl::mVisual
Text::ControllerPtr Dali::Ui::Integration::LabelImpl::mController
Text::TextScrollerPtr Dali::Ui::Integration::LabelImpl::mTextScroller
Vector2 Dali::Ui::Integration::LabelImpl::mSize
Vector2 Dali::Ui::Integration::LabelImpl::mTouchPosition
The initial touch down position.
float Dali::Ui::Integration::LabelImpl::mLineHeight
Text::LineHeightMode Dali::Ui::Integration::LabelImpl::mLineHeightMode
Text::OverflowMode Dali::Ui::Integration::LabelImpl::mOverflowMode
Text::MarqueeTriggerPolicy Dali::Ui::Integration::LabelImpl::mMarqueeTriggerPolicy
int Dali::Ui::Integration::LabelImpl::mAsyncLineCount
int Dali::Ui::Integration::LabelImpl::mTextColorAnimatedCount
bool Dali::Ui::Integration::LabelImpl::mRendererUpdateNeeded
bool Dali::Ui::Integration::LabelImpl::mMeasureInvalidated
bool Dali::Ui::Integration::LabelImpl::mIsAsyncRenderRequested
bool Dali::Ui::Integration::LabelImpl::mIsAsyncRenderLayoutDirty
bool Dali::Ui::Integration::LabelImpl::mSuppressAutoMarquee
bool Dali::Ui::Integration::LabelImpl::mLastMarqueeEnabled
bool Dali::Ui::Integration::LabelImpl::mIsTouchDown
bool Dali::Ui::Integration::LabelImpl::mHasAnchors
bool Dali::Ui::Integration::LabelImpl::mIsVisible
bool Dali::Ui::Integration::LabelImpl::mIsVisibleInitialized
bool Dali::Ui::Integration::LabelImpl::mIsViewBackgroundEnabled
bool Dali::Ui::Integration::LabelImpl::mIsManualRenderInProgress
bool Dali::Ui::Integration::LabelImpl::mIsManualRenderFinished
LabelImplPtr Dali::Ui::Integration::LabelImpl::New()
Creates a new Label.
References LabelImpl.
Referenced by Dali::Ui::Label::New, Dali::Ui::Label::New.
void Dali::Ui::Integration::LabelImpl::SetProperty(BaseObject *object, Dali::Property::Index index, const Dali::Property::Value &value)
Called when a property of an object of this type is set.
object The object whose property is set. index The property index. value The new property value.
References Dali::Ui::View::DownCast, Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Dali::Property::Value Dali::Ui::Integration::LabelImpl::GetProperty(BaseObject *object, Dali::Property::Index index)
Called to retrieve a property of an object of this type.
object The object whose property is to be retrieved. index The property index. The current value of the property.
References Dali::Ui::View::DownCast, Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
Dali::Ui::Integration::LabelImpl::~LabelImpl()
A reference counted object may only be deleted by calling Unreference()
Dali::Ui::Integration::LabelImpl::LabelImpl()
LabelImpl constructor.
Referenced by New.
MeasuredSize Dali::Ui::Integration::LabelImpl::OnMeasure(float widthConstraint, float heightConstraint) override
Called during measure pass. Override to implement custom measurement.
widthConstraint Available visual (scale-applied) width, or WRAP_CONTENT / MATCH_PARENT. heightConstraint Available visual (scale-applied) height, or WRAP_CONTENT / MATCH_PARENT. Measured visual (scale-applied) size.
References Dali::Ui::ViewImpl::GetEffectiveScale, GetFontSize, Dali::Ui::Text::FitCandidate::GetFontSize, GetHeightForWidth, Dali::Ui::Text::FitCandidate::GetLineHeight, Dali::Ui::ViewImpl::GetMaximumHeight, Dali::Ui::ViewImpl::GetMaximumWidth, Dali::Ui::ViewImpl::GetMinimumHeight, Dali::Ui::ViewImpl::GetMinimumWidth, GetNaturalSize, Dali::Ui::ViewImpl::GetRequestedHeight, Dali::Ui::ViewImpl::GetRequestedWidth, Dali::Ui::MATCH_PARENT, SetTextUiScale, Dali::Ui::WRAP_CONTENT.
MeasuredSize Dali::Ui::Integration::LabelImpl::OnArrange(const LayoutRect &bounds) override
Called during arrange pass. Override to implement custom arrangement.
References Dali::Ui::LayoutRect::height, Dali::Ui::LayoutRect::width, Dali::Ui::LayoutRect::x, Dali::Ui::LayoutRect::y.
void Dali::Ui::Integration::LabelImpl::SetText(const Dali::String &text)
Sets the text.
text The text to display in UTF-8 format.
References InvalidateTextMeasure.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::LabelImpl::GetText() const
Gets the text.
The text currently set on the label in UTF-8 format.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty, OnRelayout.
void Dali::Ui::Integration::LabelImpl::SetFontFamily(const Dali::String &fontFamily)
Sets the font family of the text.
fontFamily The requested font family to use.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::LabelImpl::GetFontFamily() const
Gets the font family of the text.
The font family currently set on the label.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetFontSize(float fontSize)
Sets the font size of the text.
fontSize The font size in pixels.
References InvalidateTextMeasure.
Referenced by ApplyInitialConfig, Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::LabelImpl::GetFontSize() const
Gets the font size of the text.
The font size currently set on the label, in pixels.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty, OnMeasure.
void Dali::Ui::Integration::LabelImpl::SetMultiLine(bool multiLine)
Sets whether the text should be multi-line.
multiLine True for multi-line layout, false for single-line layout.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
bool Dali::Ui::Integration::LabelImpl::IsMultiLine() const
Gets whether the text should be multi-line.
True if multi-line layout is enabled, otherwise false.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetLineWrapMode(Text::LineWrapMode mode)
Sets the line wrap mode.
mode The line wrap mode to apply.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::LineWrapMode Dali::Ui::Integration::LabelImpl::GetLineWrapMode() const
Gets the line wrap mode.
The current line wrap mode.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetTextColor(const UiColor &color)
Sets the color of the text.
color The required text color value.
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by ApplyInitialConfig.
UiColor Dali::Ui::Integration::LabelImpl::GetTextColor()
Gets the color of the text.
The text color currently set on the label.
References Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::LabelImpl::SetHorizontalTextAlignment(Text::Alignment alignment)
Sets the horizontal alignment of the text within the label.
alignment The horizontal text alignment.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::Alignment Dali::Ui::Integration::LabelImpl::GetHorizontalTextAlignment() const
Gets the horizontal text alignment.
The horizontal text alignment.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetVerticalTextAlignment(Text::Alignment alignment)
Sets the vertical alignment of the text within the label.
alignment The vertical text alignment.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::Alignment Dali::Ui::Integration::LabelImpl::GetVerticalTextAlignment() const
Gets the vertical text alignment.
The vertical text alignment.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetOverflowMode(Text::OverflowMode mode)
Sets the overflow mode.
mode The overflow mode to apply.
References Dali::Ui::Text::CLIP, Dali::Ui::Text::ELLIPSIS, RequestAsyncRender, RequestTextRelayout.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::OverflowMode Dali::Ui::Integration::LabelImpl::GetOverflowMode() const
Gets the overflow mode.
The current overflow mode.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetLineHeight(float lineHeight)
Sets the line height of the text.
The interpretation of this value depends on the current LineHeightMode. If the mode is LineHeightMode::RELATIVE, the line height is calculated as a multiplier of the effective scaled font pixel size: CalculatedLineHeight(px)=fontSize(px)*lineHeight*fontSizeScale If the mode is LineHeightMode::ABSOLUTE, the value is treated as an absolute line height in pixels. CalculatedLineHeight(px)=lineHeight(px)*fontSizeScale Setting lineHeight to LINE_HEIGHT_AUTO uses the natural line height derived from the font metrics, regardless of the current LineHeightMode. This behavior is similar to the "Auto" line height option in design tools such as Figma. The final line height is clamped to be no smaller than the natural line height derived from the font metrics. lineHeight The line height value.
References InvalidateTextMeasure.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::LabelImpl::GetLineHeight() const
Gets the current line height value.
The returned value is interpreted according to the current LineHeightMode. A value of -1.0f indicates that the natural line height (based on font metrics) is used. The line height value.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetLineHeightMode(Text::LineHeightMode mode)
Sets how the line height value is interpreted.
- LineHeightMode::RELATIVE: The line height is calculated as a multiplier of the font size. LineHeightMode::ABSOLUTE: The line height is treated as an absolute pixel value. The default mode is LineHeightMode::RELATIVE. mode The line height mode.
References InvalidateTextMeasure.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::LineHeightMode Dali::Ui::Integration::LabelImpl::GetLineHeightMode() const
Gets the current line height mode.
The current LineHeightMode.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetLayoutDirectionMode(Text::LayoutDirectionMode mode)
Sets how the layout direction of the text is resolved.
- LayoutDirectionMode::CONTENTS: The layout direction is determined from the text content itself. LayoutDirectionMode::INHERIT: The layout direction is inherited from the parent view. LayoutDirectionMode::LOCALE: The layout direction is determined based on the system locale. mode The LayoutDirectionMode used to determine the text layout direction.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::LayoutDirectionMode Dali::Ui::Integration::LabelImpl::GetLayoutDirectionMode() const
Gets the current layout direction mode.
The LayoutDirectionMode used to resolve the text layout direction.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetMarkupEnabled(bool enabled)
Enables or disables mark-up processing for the text.
enabled True to enable mark-up parsing, false to render text as plain string.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
bool Dali::Ui::Integration::LabelImpl::IsMarkupEnabled() const
Gets whether mark-up processing is enabled.
True if mark-up parsing is enabled, otherwise false.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetAnchorColor(const UiColor &color)
Sets the color of anchors in the text.
color The color to apply to anchors.
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::LabelImpl::GetAnchorColor()
Gets the color of anchors in the text.
The current anchor color.
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetAnchorClickedColor(const UiColor &color)
Sets the color of anchors when they are clicked.
color The color to apply to clicked anchors.
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::LabelImpl::GetAnchorClickedColor()
Gets the color of anchors when they are clicked.
The current clicked anchor color.
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetMarqueeTriggerPolicy(Text::MarqueeTriggerPolicy policy)
Sets how the marquee animation is triggered.
- MarqueeTriggerPolicy::MANUAL: The marquee starts only when StartMarquee() is explicitly called. MarqueeTriggerPolicy::ON_OVERFLOW: The marquee starts automatically during layout when the text exceeds the available space. The default policy is MarqueeTriggerPolicy::MANUAL. policy The marquee trigger policy.
References RequestAsyncRender, RequestTextRelayout.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::MarqueeTriggerPolicy Dali::Ui::Integration::LabelImpl::GetMarqueeTriggerPolicy() const
Returns when the marquee animation is triggered.
The current marquee trigger policy.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetMarqueeSpeed(int speed)
Sets the marquee speed.
speed The marquee speed in pixels per second.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
int Dali::Ui::Integration::LabelImpl::GetMarqueeSpeed() const
Returns the marquee speed.
The marquee speed in pixels per second.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetMarqueeSpeed.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetMarqueeLoopCount(int loopCount)
Sets the number of complete loops for marquee.
loopCount The number of loops.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
int Dali::Ui::Integration::LabelImpl::GetMarqueeLoopCount() const
Returns the number of complete loops for marquee.
The number of loops.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetMarqueeLoopCount.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetMarqueeLoopDelay(float delay)
Sets the amount of time to delay the start of marquee and further loops.
delay The delay time in seconds.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::LabelImpl::GetMarqueeLoopDelay() const
Returns the amount of time to delay the start of marquee and further loops.
The delay time in seconds.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetMarqueeLoopDelay.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetMarqueeGap(int gap)
Sets the gap before marquee wraps.
gap The gap in pixels.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
int Dali::Ui::Integration::LabelImpl::GetMarqueeGap() const
Returns the gap before marquee wraps.
The gap in pixels.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetMarqueeGap.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetMarqueeOrientation(Text::MarqueeOrientation orientation)
Sets the marquee orientation.
Horizontal is applied only for single-line text, and vertical only for multi-line text. The setting is ignored if the text layout does not match the required condition. orientation The marquee orientation.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::MarqueeOrientation Dali::Ui::Integration::LabelImpl::GetMarqueeOrientation() const
Returns the marquee orientation.
The marquee orientation.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetMarqueeOrientation.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetMarqueeStopMode(Text::MarqueeStopMode stopMode)
Sets how the marquee stops.
stopMode The marquee stop mode.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::MarqueeStopMode Dali::Ui::Integration::LabelImpl::GetMarqueeStopMode() const
Returns how the marquee stops.
The marquee stop mode.
References Dali::Ui::Integration::UiConfigManager::Get, Dali::Ui::Integration::UiConfigManager::GetConfig, Dali::Ui::UiConfig::GetMarqueeStopMode.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetFontWeight(Text::FontWeight weight)
Sets the font weight.
weight The font weight.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::FontWeight Dali::Ui::Integration::LabelImpl::GetFontWeight() const
Returns the font weight.
The font weight.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetFontWidth(Text::FontWidth width)
Sets the font width.
width The font width.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::FontWidth Dali::Ui::Integration::LabelImpl::GetFontWidth() const
Returns the font width.
The font width.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetFontSlant(Text::FontSlant slant)
Sets the font slant.
slant The font slant.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
Text::FontSlant Dali::Ui::Integration::LabelImpl::GetFontSlant() const
Returns the font slant.
The font slant.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetTextBackgroundColor(const UiColor &color)
Sets the background color behind the text.
The background is rendered behind the glyphs of the text. color The text background color.
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::LabelImpl::GetTextBackgroundColor() const
Gets the background color behind the text.
The current text background color.
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::ClearTextBackgroundColor()
Clears the text background color.
Disables the text background and removes the previously set color.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::LabelImpl::SetUnderline(const Text::Underline &underline)
Sets the underline style.
underline The underline configuration.
References Dali::Ui::Text::Underline::GetColor, RequestAsyncRender, RequestTextRelayout, Dali::Ui::ViewImpl::SetColorBinding.
void Dali::Ui::Integration::LabelImpl::ClearUnderline()
Clears the underline style.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::LabelImpl::SetShadow(const Text::Shadow &shadow)
Sets the shadow style.
shadow The shadow configuration.
References Dali::Ui::Text::Shadow::GetColor, RequestAsyncRender, RequestTextRelayout, Dali::Ui::ViewImpl::SetColorBinding.
void Dali::Ui::Integration::LabelImpl::ClearShadow()
Clears the shadow style.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::LabelImpl::SetOutline(const Text::Outline &outline)
Sets the outline style.
outline The outline configuration.
References Dali::Ui::Text::Outline::GetColor, RequestAsyncRender, RequestTextRelayout, Dali::Ui::ViewImpl::SetColorBinding.
void Dali::Ui::Integration::LabelImpl::ClearOutline()
Clears the outline style.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::LabelImpl::SetLineThrough(const Text::LineThrough &lineThrough)
Sets the line-through style.
lineThrough The line-through configuration.
References Dali::Ui::Text::LineThrough::GetColor, RequestAsyncRender, RequestTextRelayout, Dali::Ui::ViewImpl::SetColorBinding.
void Dali::Ui::Integration::LabelImpl::ClearLineThrough()
Clears the line-through style.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::LabelImpl::SetBevel(const Text::Bevel &bevel)
Sets the bevel style.
bevel The bevel configuration.
References Dali::Ui::Text::Bevel::GetLightColor, Dali::Ui::Text::Bevel::GetShadowColor, RequestAsyncRender, RequestTextRelayout, Dali::Ui::ViewImpl::SetColorBinding.
void Dali::Ui::Integration::LabelImpl::ClearBevel()
Clears the bevel style.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::LabelImpl::SetTextFit(const Text::FitRange &range)
Dali::Ui::Label::SetTextFit
References Dali::Ui::Text::FitRange::GetFontSizeStep, Dali::Ui::Text::FitRange::GetMaximumFontSize, Dali::Ui::Text::FitRange::GetMinimumFontSize, InvalidateTextMeasure.
void Dali::Ui::Integration::LabelImpl::SetTextFit(const Dali::Vector< Text::FitCandidate > &candidates)
Dali::Ui::Label::SetTextFit(const Dali::Vector<Text::FitCandidate>&)
References InvalidateTextMeasure.
void Dali::Ui::Integration::LabelImpl::ClearTextFit()
Clears the text fit configuration.
References InvalidateTextMeasure.
void Dali::Ui::Integration::LabelImpl::SetFontSizeScale(float scale)
Sets the font size scale.
The scaled font size is calculated from the current font size multiplied by this scale value. scale The font size scale.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::LabelImpl::GetFontSizeScale() const
Gets the font size scale.
The font size scale.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetMinimumFontSizeScale(float scale)
Sets the minimum font size scale.
If this value is greater than the maximum font size scale, the adjusted font size scale follows this minimum value. scale The minimum font size scale.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::LabelImpl::GetMinimumFontSizeScale() const
Gets the minimum font size scale.
The minimum font size scale.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetMaximumFontSizeScale(float scale)
Sets the maximum font size scale.
If this value is less than the minimum font size scale, the adjusted font size scale follows the minimum font size scale. scale The maximum font size scale.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::LabelImpl::GetMaximumFontSizeScale() const
Gets the maximum font size scale.
The maximum font size scale.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetSystemFontSizeScaleEnabled(bool enabled)
Sets whether the system font size scale is applied.
When enabled, the system font size scale is combined with the current font size scale before applying the minimum and maximum constraints. enabled True to apply the system font size scale, false otherwise.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
bool Dali::Ui::Integration::LabelImpl::IsSystemFontSizeScaleEnabled() const
Gets whether the system font size scale is applied.
True if the system font size scale is applied, otherwise false.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetFontVariation(const Dali::Vector< Text::FontVariationAxis > &axes)
Dali::Ui::Label::SetFontVariation
Referenced by SetFontVariation.
void Dali::Ui::Integration::LabelImpl::SetFontVariation(const Dali::String &settings)
Dali::Ui::Label::SetFontVariation(const Dali::String&)
References Dali::Ui::Text::FontVariation::FromString, SetFontVariation.
Dali::Vector< Text::FontVariationAxis > Dali::Ui::Integration::LabelImpl::GetFontVariation() const
Returns the font variation axes.
The font variation axes.
void Dali::Ui::Integration::LabelImpl::ClearFontVariation()
Clears the font variation.
This removes all previously set font variation axes.
Dali::Property::Index Dali::Ui::Integration::LabelImpl::RegisterFontVariationProperty(const Dali::String &tag)
Registers or retrieves a font variation property for the given axis tag.
If a property with the same tag is already registered, the existing property is reused and its current value is updated. tag A 4-character OpenType variation axis tag. The property index associated with the variation tag, or Property::INVALID_INDEX on failure.
void Dali::Ui::Integration::LabelImpl::SetCutoutEnabled(bool enabled)
Sets whether the text is rendered as a cutout.
When enabled, the glyph shapes are cut out from the rendered content instead of being filled with the text color. enabled True to render the text as a cutout, false to render it normally.
References Dali::Ui::Text::LabelPropertyIndex::CUTOUT_ENABLED.
bool Dali::Ui::Integration::LabelImpl::IsCutoutEnabled() const
Gets whether the text is rendered as a cutout.
True if the text is rendered as a cutout, otherwise false.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetLetterSpacing(float spacing)
Sets the additional spacing between letters in pixels.
Positive values increase the spacing, while negative values reduce it. spacing The additional letter spacing in pixels.
References spacing.
float Dali::Ui::Integration::LabelImpl::GetLetterSpacing() const
Gets the additional spacing between letters in pixels.
The additional letter spacing in pixels.
void Dali::Ui::Integration::LabelImpl::SetMaskEffect(View view)
Applies a mask effect using the given view.
This helper creates a MaskEffect using the rendered output of the view as the mask source and applies it to the label. The given view is added as a child of the label and retained internally until ClearMaskEffect() is called. Any existing RenderEffect on the label will be replaced. view The view used as the mask source. Dali::Ui::MaskEffect Dali::Ui::View::SetRenderEffect()
References ClearMaskEffect, Dali::Ui::View::DownCast, Dali::Ui::GetImplementation, Dali::Ui::MaskEffect::New, Dali::Ui::View::SetRenderEffect.
void Dali::Ui::Integration::LabelImpl::ClearMaskEffect()
Clears the mask effect applied to the label.
Removes the internally retained mask view from the label and clears the applied RenderEffect. Dali::Ui::View::ClearRenderEffect()
References Dali::Ui::View::ClearRenderEffect, Dali::Ui::View::DownCast.
Referenced by SetMaskEffect.
void Dali::Ui::Integration::LabelImpl::SetAsyncRendering(bool asyncRendering)
Sets whether the text is rendered asynchronously.
When enabled, the label automatically requests asynchronous text rendering during relayout as needed. By default, text is rendered synchronously. asyncRendering True to enable asynchronous text rendering, false to render text synchronously. The render result is delivered through Label::AsyncRenderFinishedSignal().
Referenced by ApplyInitialConfig, Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
bool Dali::Ui::Integration::LabelImpl::IsAsyncRendering() const
Gets whether asynchronous text rendering is enabled.
True if asynchronous text rendering is enabled, otherwise false.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::LabelImpl::SetRenderScale(float scale)
Sets the render scale of the text.
Renders text by rasterizing glyphs at a larger scale and downscaling the result. This improves rendering quality when the view is visually scaled, by reducing quality loss caused by texture upscaling. The layout size of the view is not affected. Valid only when async rendering is enabled, and the value must be 1.0f or greater. scale The render scale.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::LabelImpl::GetRenderScale() const
Gets the render scale of the text.
The current render scale.
Referenced by Dali::Ui::Integration::LabelImpl::PropertyHandler::GetProperty.
int Dali::Ui::Integration::LabelImpl::GetLineCount()
Dali::Ui::Label::GetLineCount
References GetLineCount, Dali::Ui::ViewImpl::GetMaximumWidth, Dali::Ui::ViewImpl::GetMinimumWidth.
Referenced by GetLineCount.
int Dali::Ui::Integration::LabelImpl::GetLineCount(float width)
Dali::Ui::Label::GetLineCount(float)
References GetEffectiveTextPadding.
int Dali::Ui::Integration::LabelImpl::GetAsyncLineCount() const
Dali::Ui::Label::GetAsyncLineCount
bool Dali::Ui::Integration::LabelImpl::IsMarqueeRunning() const
Returns whether the marquee animation is currently running.
True if the marquee animation is running, false otherwise.
float Dali::Ui::Integration::LabelImpl::GetAdjustedFontSizeScale() const
Gets the adjusted font size scale used for rendering.
The adjusted font size scale is resolved after applying the current minimum and maximum font size scale constraints and, if enabled, the system font size scale. If the minimum font size scale is greater than the maximum font size scale, the minimum font size scale takes precedence and is used as the adjusted scale. The adjusted font size scale used for rendering.
void Dali::Ui::Integration::LabelImpl::StartMarquee()
Starts the marquee animation using the current marquee settings.
The marquee starts only when the orientation matches the current text layout: horizontal for single-line text, and vertical for multi-line text. If the condition is not met, this call has no effect. If the trigger policy is MarqueeTriggerPolicy::ON_OVERFLOW, the marquee starts only when the text exceeds the available space.
void Dali::Ui::Integration::LabelImpl::StopMarquee()
Stops the marquee animation.
The stopping behavior follows the current MarqueeStopMode: MarqueeStopMode::IMMEDIATE: Stops the marquee immediately. MarqueeStopMode::FINISH_LOOP: Continues the animation until the current loop finishes, then stops. This method works regardless of the current MarqueeTriggerPolicy. It stops the marquee even if the policy is MANUAL or ON_OVERFLOW.
void Dali::Ui::Integration::LabelImpl::RequestAsyncNaturalSize()
Requests asynchronous natural size computation.
This method can be used regardless of whether asynchronous rendering is enabled. The computed natural size includes the label padding. The computed result is delivered through Label::AsyncNaturalSizeComputedSignal().
References GetEffectiveTextPadding.
void Dali::Ui::Integration::LabelImpl::RequestAsyncHeightForWidth(float width)
Requests asynchronous height-for-width computation.
This method can be used regardless of whether asynchronous rendering is enabled. The given width must be the total label width including padding. width The total width used for the computation, including padding. The computed result is delivered through Label::AsyncHeightForWidthComputedSignal().
References GetEffectiveTextPadding.
void Dali::Ui::Integration::LabelImpl::RequestAsyncRenderWithFixedSize(float width, float height)
Requests asynchronous text rendering with a fixed size.
width The width used for rendering. height The height used for rendering.
References GetEffectiveTextPadding.
void Dali::Ui::Integration::LabelImpl::RequestAsyncRenderWithFixedWidth(float width, float heightConstraint)
Requests asynchronous text rendering with a fixed width.
width The width used for rendering. heightConstraint The maximum available height.
References GetEffectiveTextPadding.
void Dali::Ui::Integration::LabelImpl::RequestAsyncRenderWithFixedHeight(float widthConstraint, float height)
Requests asynchronous text rendering with a fixed height.
widthConstraint The maximum available width. height The height used for rendering.
References GetEffectiveTextPadding.
void Dali::Ui::Integration::LabelImpl::RequestAsyncRenderWithConstraints(float widthConstraint, float heightConstraint)
Requests asynchronous text rendering within the given constraints.
widthConstraint The maximum available width. heightConstraint The maximum available height.
References GetEffectiveTextPadding.
Signal< void(View, const Dali::String &)> & Dali::Ui::Integration::LabelImpl::AnchorClickedSignal()
This signal is emitted when an anchor in the text is clicked.
voidOnAnchorClicked(Viewview,constDali::String&href); view The view that received the click event. href The href of the clicked anchor. The signal to connect to.
Signal< void(View, float, float)> & Dali::Ui::Integration::LabelImpl::AsyncRenderFinishedSignal()
This signal is emitted when asynchronous text rendering is finished.
voidOnAsyncRenderFinished(Viewview,floatwidth,floatheight); view The view whose async text rendering has completed. width The rendered text width, including padding. height The rendered text height, including padding. The signal to connect to.
Signal< void(View, float, float)> & Dali::Ui::Integration::LabelImpl::AsyncNaturalSizeComputedSignal()
This signal is emitted when asynchronous natural size computation is finished.
voidOnAsyncNaturalSizeComputed(Viewview,floatwidth,floatheight); view The view whose async natural size computation has completed. width The computed natural width, including padding. height The computed natural height, including padding. The signal to connect to.
Signal< void(View, float, float)> & Dali::Ui::Integration::LabelImpl::AsyncHeightForWidthComputedSignal()
This signal is emitted when asynchronous height-for-width computation is finished.
voidOnAsyncHeightForWidthComputed(Viewview,floatwidth,floatheight); view The view whose async height-for-width computation has completed. width The total width used for the computation, including padding. height The computed height for the given width, including padding. The signal to connect to.
void Dali::Ui::Integration::LabelImpl::ApplyInitialConfig()
Applies default values from UiConfigManager if initialized.
References Dali::Ui::Integration::UiConfigManager::Get, SetAsyncRendering, SetFontSize, SetTextColor.
Referenced by OnInitialize.
bool Dali::Ui::Integration::LabelImpl::SetTextUiScale(float scale)
Sets the UI scale used for text-specific metrics.
This scale is used for text-specific size calculation, such as font size. scale The text UI scale. True if the scale was changed, false otherwise.
Referenced by OnMeasure.
float Dali::Ui::Integration::LabelImpl::GetTextUiScale() const
Gets the UI scale used for text-specific metrics.
The text UI scale.
Referenced by GetEffectiveTextPadding.
Extents Dali::Ui::Integration::LabelImpl::GetEffectiveTextPadding() const
Gets the effective padding used for text layout.
The view padding is adjusted by the current text UI scale. The effective text padding.
References Dali::Ui::ViewImpl::GetPadding, GetTextUiScale.
Referenced by AsyncRenderFinished, AsyncSizeComputed, GetHeightForWidth, GetLineCount, GetNaturalSize, OnRelayout, RequestAsyncHeightForWidth, RequestAsyncNaturalSize, RequestAsyncRenderWithConstraints, RequestAsyncRenderWithFixedHeight, RequestAsyncRenderWithFixedSize, RequestAsyncRenderWithFixedWidth.
void Dali::Ui::Integration::LabelImpl::OnInitialize() override
Called after the actor has been initialized.
References ApplyInitialConfig, Dali::Ui::Text::CENTER, Dali::Ui::DepthIndex::CONTENT, Dali::Ui::VisualFactory::CreateVisual, Dali::Ui::View::DownCast, Dali::Ui::VisualFactory::Get, Dali::Ui::GetImpl, Dali::Ui::ViewImpl::OnInitialize, Dali::Ui::Text::LabelPropertyIndex::PIXEL_SNAP_FACTOR, Dali::Ui::Text::LabelPropertyIndex::TEXT, Dali::Ui::Visual::TEXT, Dali::Ui::Text::LabelPropertyIndex::TEXT_COLOR, Dali::Ui::Visual::Property::TYPE.
void Dali::Ui::Integration::LabelImpl::OnRelayout(const Vector2 &size, RelayoutContainer &container) override
References Dali::Ui::Visual::Transform::Policy::ABSOLUTE, GetEffectiveTextPadding, GetText, Dali::Ui::Text::HORIZONTAL, Dali::Ui::Visual::Transform::Property::OFFSET, Dali::Ui::Visual::Transform::Property::OFFSET_POLICY, Dali::Ui::Visual::Transform::Property::ORIGIN, Dali::Ui::Visual::Transform::Property::PIVOT, Dali::Ui::Visual::Base::SetTransformAndSize, Dali::Ui::Visual::Transform::Property::SIZE, Dali::Ui::Visual::Transform::Property::SIZE_POLICY, Dali::Ui::Align::TOP_BEGIN, Dali::Ui::Text::VERTICAL.
Vector3 Dali::Ui::Integration::LabelImpl::GetNaturalSize() override
References GetEffectiveTextPadding.
Referenced by OnMeasure.
float Dali::Ui::Integration::LabelImpl::GetHeightForWidth(float width) override
References GetEffectiveTextPadding.
Referenced by OnMeasure.
void Dali::Ui::Integration::LabelImpl::OnAnimateAnimatableProperty(Animation &animation, Dali::Property::Index index, Dali::Animation::State state) override
References Dali::Ui::ViewImpl::OnAnimateAnimatableProperty, Dali::Ui::Text::LabelPropertyIndex::TEXT_COLOR.
void Dali::Ui::Integration::LabelImpl::OnConstraintAnimatableProperty(Constraint &constraint, Dali::Property::Index index, bool applied) override
References Dali::Ui::ViewImpl::OnConstraintAnimatableProperty, Dali::Ui::Text::LabelPropertyIndex::TEXT_COLOR.
void Dali::Ui::Integration::LabelImpl::RequestTextRelayout() override
Referenced by SetBevel, SetLineThrough, SetMarqueeTriggerPolicy, SetOutline, SetOverflowMode, SetShadow, SetUnderline.
void Dali::Ui::Integration::LabelImpl::InvalidateTextMeasure() override
References Dali::Ui::ViewImpl::GetRequestedHeight, Dali::Ui::ViewImpl::GetRequestedWidth, Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::WRAP_CONTENT.
Referenced by ClearTextFit, SetFontSize, SetLineHeight, SetLineHeightMode, SetText, SetTextFit, SetTextFit.
void Dali::Ui::Integration::LabelImpl::RequestAsyncRender() override
Referenced by AsyncInitializeMarquee, SetBevel, SetLineThrough, SetMarqueeTriggerPolicy, SetOutline, SetOverflowMode, SetShadow, SetUnderline.
bool Dali::Ui::Integration::LabelImpl::AnchorClicked(uint32_t cursorPosition, std::string &href) override
void Dali::Ui::Integration::LabelImpl::EmitAnchorClicked(const std::string &href) override
void Dali::Ui::Integration::LabelImpl::AsyncInitializeMarquee(Text::AsyncTextRenderInfo renderInfo) override
References Dali::Ui::GetImplementation, Dali::Ui::Text::HORIZONTAL, Dali::Ui::Text::MANUAL, RequestAsyncRender.
void Dali::Ui::Integration::LabelImpl::AsyncTextFitChanged(float pointSize) override
void Dali::Ui::Integration::LabelImpl::AsyncRenderFinished(Text::AsyncTextRenderInfo renderInfo) override
References GetEffectiveTextPadding.
void Dali::Ui::Integration::LabelImpl::AsyncSizeComputed(Text::AsyncTextRenderInfo renderInfo) override
References GetEffectiveTextPadding.
void Dali::Ui::Integration::LabelImpl::OnPropertySet(Dali::Property::Index index, const Dali::Property::Value &propertyValue) override
References Dali::Ui::View::Property::BACKGROUND, Dali::Ui::Text::LabelPropertyIndex::CUTOUT_ENABLED, Dali::Ui::ViewImpl::OnPropertySet, Dali::Ui::View::Property::PADDING, Dali::Ui::Text::LabelPropertyIndex::TEXT_COLOR.
void Dali::Ui::Integration::LabelImpl::ScrollingFinished() override
void Dali::Ui::Integration::LabelImpl::RequestRendererUpdate()
Marks that the text renderer needs to be updated on the next relayout.
void Dali::Ui::Integration::LabelImpl::UpdateLineHeight()
Updates the effective line height based on the current LineHeightMode.
void Dali::Ui::Integration::LabelImpl::OnLayoutDirectionChanged(Actor actor, LayoutDirection::Type type)
Callback function for when the layout is changed.
actor The actor whose layoutDirection is changed. type The layoutDirection.
void Dali::Ui::Integration::LabelImpl::OnLocaleChanged(std::string locale)
Callback function for when the locale is changed.
locale The new system locale.
bool Dali::Ui::Integration::LabelImpl::OnInterceptTouched(Actor actor, TouchEvent touch)
Handles touch interactions for text anchors when mark-up is enabled.
actor The label that received the touch. touch The touch event information. True if the touch event is consumed, otherwise false.
void Dali::Ui::Integration::LabelImpl::UpdateAnchorTouchInterception()
Updates touch interception based on anchor presence.
void Dali::Ui::Integration::LabelImpl::InitializeMarquee(const Size &contentSize, const Size &originSize)
Initializes marquee based on the current text layout.
contentSize The size of the text content excluding padding. originSize The size of the laid-out text used to compute the initial scroll offset.
void Dali::Ui::Integration::LabelImpl::UpdateMarqueeState()
Updates the marquee state.
Called when properties such as orientation or multiline state change.
void Dali::Ui::Integration::LabelImpl::EnableAutoMarqueeEvaluation()
Enables automatic marquee evaluation.
Clears the suppression state so that marquee can be re-evaluated based on the current layout conditions (e.g., overflow, visibility).
void Dali::Ui::Integration::LabelImpl::SuppressAutoMarqueeEvaluation()
Suppresses automatic marquee evaluation.
Prevents marquee from being automatically enabled even if layout conditions (e.g., overflow) are satisfied.
void Dali::Ui::Integration::LabelImpl::OnMarqueeVisibilityChanged(bool visible)
Handles marquee behavior when visibility changes.
visible True to restore the previous marquee state, false to stop the marquee animation.
Text::TextScrollerPtr Dali::Ui::Integration::LabelImpl::GetTextScroller()
Returns the text scroller, creating it if necessary.
The text scroller.
void Dali::Ui::Integration::LabelImpl::SetMarqueeEnabled(bool enabled)
Enables or disables the marquee animation.
Updates the internal marquee state and starts or stops the scrolling accordingly. enabled True to start the marquee animation, false to stop it.
void Dali::Ui::Integration::LabelImpl::OnViewInheritedVisibilityChanged(Actor actor, bool visible)
Callback when the visibility of the actor is changed.
bool Dali::Ui::Integration::LabelImpl::IsVisible()
Returns the cached effective visibility of the label.
True if the label is effectively visible.
void Dali::Ui::Integration::LabelImpl::EvaluateAndApplyMarquee(const Size &contentSize, Text::MarqueeOrientation orientation)
Evaluates whether marquee should run and applies the result.
Enables or disables marquee depending on the current layout and mode. contentSize The size of the text content excluding padding. orientation The marquee orientation.
void Dali::Ui::Integration::LabelImpl::PrepareMarqueeLayout(const Size &contentSize, Text::MarqueeOrientation orientation, Size &originSize)
Prepares layout data required for marquee.
contentSize The size of the text content excluding padding. orientation The marquee orientation. originSize The laid-out text size used to compute the initial scroll offset.
void Dali::Ui::Integration::LabelImpl::OnVariationPropertyNotify(PropertyNotification source)
Called when a font variation property changes.
bool Dali::Ui::Integration::LabelImpl::HandleVariationPropertySet(Dali::Property::Index index, const Dali::Property::Value &propertyValue)
Handles font variation property updates.
index The property index being set. propertyValue The property value. true if handled, false otherwise.
void Dali::Ui::Integration::LabelImpl::SetCutoutEnabledInternal(bool enabled)
Applies the cutout enabled state internally.
This updates the internal rendering state and synchronizes any dependent background or visual configuration required for cutout rendering. enabled True to enable cutout rendering, false otherwise.
void Dali::Ui::Integration::LabelImpl::SetViewBackgroundEnabled(bool enabled)
Sets whether the background of the view is enabled.
enabled True to enable the view background, false to disable it.
bool Dali::Ui::Integration::LabelImpl::GetViewBackgroundColor(Vector4 &backgroundColor) const
Gets the current background color of the view.
Extracts the color from the view's background visual if available. backgroundColor The extracted background color. True if a background color was successfully retrieved, false otherwise.
void Dali::Ui::Integration::LabelImpl::OnBackgroundPropertyChanged()
Handles background property changes related to cutout rendering.
void Dali::Ui::Integration::LabelImpl::UpdateCutoutState(bool enabled)
Updates dependent rendering state for cutout rendering.
This synchronizes background and visual state after the cutout property has been applied through the property handler. enabled True if cutout rendering is enabled, false otherwise.
Text::AsyncTextParameters Dali::Ui::Integration::LabelImpl::GetAsyncTextParameters(Text::Async::RequestType requestType, const Vector2 &contentSize, const Extents &padding, Dali::LayoutDirection::Type layoutDirection)
Returns the parameters used for asynchronous text processing.
Collects and returns the text label properties required to perform asynchronous text rendering or size computation. requestType The type of asynchronous request. contentSize The content size requested by relayout, excluding padding. padding The label padding. layoutDirection The layout direction. The parameters for asynchronous text processing.
void Dali::Ui::Integration::LabelImpl::EmitTextFitChanged()
Emits TextFitChanged signal.
void Dali::Ui::Integration::LabelImpl::EmitAsyncRenderFinished(float width, float height)
Emits AsyncRenderFinished signal.
void Dali::Ui::Integration::LabelImpl::EmitAsyncNaturalSizeComputed(float width, float height)
Emits AsyncNaturalSizeComputed signal.
void Dali::Ui::Integration::LabelImpl::EmitAsyncHeightForWidthComputed(float width, float height)
Emits AsyncHeightForWidthComputed signal.
void Dali::Ui::Integration::LabelImpl::SetTextColorInternal(const Vector4 &color)
void Dali::Ui::Integration::LabelImpl::SetAnchorColorInternal(const Vector4 &color)
void Dali::Ui::Integration::LabelImpl::SetAnchorClickedColorInternal(const Vector4 &color)
void Dali::Ui::Integration::LabelImpl::SetTextBackgroundColorInternal(const Vector4 &color)
void Dali::Ui::Integration::LabelImpl::SetUnderlineColorInternal(const Vector4 &color)
void Dali::Ui::Integration::LabelImpl::SetShadowColorInternal(const Vector4 &color)
void Dali::Ui::Integration::LabelImpl::SetOutlineColorInternal(const Vector4 &color)
void Dali::Ui::Integration::LabelImpl::SetLineThroughColorInternal(const Vector4 &color)
void Dali::Ui::Integration::LabelImpl::SetBevelLightColorInternal(const Vector4 &color)
void Dali::Ui::Integration::LabelImpl::SetBevelShadowColorInternal(const Vector4 &color)
Dali::Ui::Integration::LabelImpl::LabelImpl(const LabelImpl &)=delete
Dali::Ui::Integration::LabelImpl::LabelImpl(LabelImpl &&)=delete
LabelImpl & Dali::Ui::Integration::LabelImpl::operator=(const LabelImpl &)=delete
LabelImpl & Dali::Ui::Integration::LabelImpl::operator=(LabelImpl &&)=delete