Dali::Ui::ScrollBar
Dali::Ui::ScrollBar::ScrollBar()
Creates an uninitialized ScrollBar handle.
Referenced by New.
Dali::Ui::ScrollBar::ScrollBar(const ScrollBar &scrollBar)
Copy constructor.
Dali::Ui::ScrollBar::ScrollBar(ScrollBar &&rhs) noexcept
Move constructor.
Dali::Ui::ScrollBar::~ScrollBar()
Destructor.
ScrollBar & Dali::Ui::ScrollBar::operator=(const ScrollBar &handle)
Copy assignment operator.
References Dali::Ui::AbsoluteLayout::operator=, Dali::Ui::View::VerifyCustomActorPointer.
ScrollBar & Dali::Ui::ScrollBar::operator=(ScrollBar &&rhs) noexcept
Move assignment operator.
References Dali::Ui::AbsoluteLayout::operator=.
View Dali::Ui::ScrollBar::GetTarget() const override
Gets the target view for which the scroll bar is responsible.
The target view.
References Dali::Ui::GetImpl.
ScrollBarVisibility Dali::Ui::ScrollBar::GetVerticalScrollBarVisibility() const override
Gets the visibility of the vertical scroll bar.
The vertical scroll bar visibility.
References Dali::Ui::GetImpl.
void Dali::Ui::ScrollBar::SetVerticalScrollBarVisibility(ScrollBarVisibility visibility) override
Sets the visibility of the vertical scroll bar.
visibility The vertical scroll bar visibility.
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
Referenced by Dali::Ui::Integration::ScrollViewImpl::OnInitialize, Dali::Ui::Integration::ScrollViewImpl::SetVerticalScrollBarVisibility.
ScrollBarVisibility Dali::Ui::ScrollBar::GetHorizontalScrollBarVisibility() const override
Gets the visibility of the horizontal scroll bar.
The horizontal scroll bar visibility.
References Dali::Ui::GetImpl.
void Dali::Ui::ScrollBar::SetHorizontalScrollBarVisibility(ScrollBarVisibility visibility) override
Sets the visibility of the horizontal scroll bar.
visibility The horizontal scroll bar visibility.
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
Referenced by Dali::Ui::Integration::ScrollViewImpl::OnInitialize, Dali::Ui::Integration::ScrollViewImpl::SetHorizontalScrollBarVisibility.
void Dali::Ui::ScrollBar::UpdateBarSize(float scrollWidth, float scrollHeight, float viewportWidth, float viewportHeight) override
Updates the size of the scroll bar based on the given scroll area and viewport size.
scrollWidth The width of the scrollable area. scrollHeight The height of the scrollable area. viewportWidth The width of the visible area. viewportHeight The height of the visible area.
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
void Dali::Ui::ScrollBar::UpdateScrollPosition(const Vector2 &position) override
Updates the scroll position of the scroll bar based on the given position.
position The new scroll position.
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
void Dali::Ui::ScrollBar::HideBar() override
Hides the scroll bar (fade out).
Called when scrolling ends. Only affects bars with Auto visibility.
References Dali::Ui::GetImpl.
float Dali::Ui::ScrollBar::GetBarThickness() const
Gets or sets the thickness of the scroll bar.
The thickness of the scroll bar.
References Dali::Ui::GetImpl.
void Dali::Ui::ScrollBar::SetBarThickness(float thickness)
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
Vector4 Dali::Ui::ScrollBar::GetBarColor() const
Gets or sets the color of the scroll bar.
The color of the scroll bar.
References Dali::Ui::GetImpl.
void Dali::Ui::ScrollBar::SetBarColor(const Vector4 &color)
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
float Dali::Ui::ScrollBar::GetBarMinSize() const
Gets or sets the minimum size of the scroll bar.
The minimum size of the scroll bar.
References Dali::Ui::GetImpl.
void Dali::Ui::ScrollBar::SetBarMinSize(float minSize)
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
Vector2 Dali::Ui::ScrollBar::GetScrollPosition() const
Gets or sets the current scroll position of the target view.
The current scroll position.
References Dali::Ui::GetImpl.
void Dali::Ui::ScrollBar::SetScrollPosition(const Vector2 &position)
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
float Dali::Ui::ScrollBar::GetBarOffset() const
Gets or sets the offset of bars from the edges. This creates a small gap between the bar and the scroll bar container edges. Padding can be set using View::SetPadding() which is inherited by ScrollBar.
The bar offset.
References Dali::Ui::GetImpl.
void Dali::Ui::ScrollBar::SetBarOffset(float offset)
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
Vector4 Dali::Ui::ScrollBar::GetBarCornerRadius() const
Gets the corner radius of the scroll bar.
The corner radius for each corner (topLeft, topRight, bottomRight, bottomLeft).
References Dali::Ui::GetImpl.
void Dali::Ui::ScrollBar::SetBarCornerRadius(float radius)
Sets the corner radius of the scroll bar (same for all corners).
radius The corner radius to apply to all corners.
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
void Dali::Ui::ScrollBar::SetBarCornerRadius(const Vector4 &radius)
Sets the corner radius of the scroll bar for each corner individually.
radius The corner radius (topLeft, topRight, bottomRight, bottomLeft).
References Dali::Ui::GetImpl, Dali::Ui::View::VerifyCustomActorPointer.
ScrollBar Dali::Ui::ScrollBar::New()
Creates an initialized ScrollBar.
A handle to a newly allocated Dali resource.
References Dali::Ui::Integration::ScrollBarImpl::New, ScrollBar, Dali::Ui::View::VerifyCustomActorPointer.
ScrollBar Dali::Ui::ScrollBar::DownCast(BaseHandle handle)
Downcasts a handle to ScrollBar handle.
handle Handle to an object. A handle to a ScrollBar or an uninitialized handle.
References Dali::Ui::View::VerifyCustomActorPointer.