Dali::Ui::Internal::VisualBaseImpl
PropertyUpdatedStatus
Nothing be changed after create visual.
using Dali::Ui::Internal::VisualBaseImpl::VisualPropertyId = uint32_t
constexpr VisualPropertyId Dali::Ui::Internal::VisualBaseImpl::INVALID_VISUAL_PROPERTY_ID
Referenced by DetachFromContainerInternal.
Dali::WeakHandle<Dali::Ui::VisualsContainer> Dali::Ui::Internal::VisualBaseImpl::mContainer
const Dali::Ui::Visual::Type Dali::Ui::Internal::VisualBaseImpl::mVisualType
Dali::String Dali::Ui::Internal::VisualBaseImpl::mName
Property::Map Dali::Ui::Internal::VisualBaseImpl::mCachedVisualPropertyMap
Whole collected map of properties.
Property::Map Dali::Ui::Internal::VisualBaseImpl::mUpdatedMutableVisualProperties
Temporal properties that was.
std::unique_ptr<Internal::Visual::Transform> Dali::Ui::Internal::VisualBaseImpl::mTransform
Dali::Ui::Visual::Base Dali::Ui::Internal::VisualBaseImpl::mVisual
Created visual by CreateVisual API.
Dali::Ui::DevelVisual::InternalContainerRangeType Dali::Ui::Internal::VisualBaseImpl::mRangeType
Dali::Ui::VisualsContainer::ShadowType Dali::Ui::Internal::VisualBaseImpl::mShadowType
uint32_t Dali::Ui::Internal::VisualBaseImpl::mSiblingOrder
VisualPropertyId Dali::Ui::Internal::VisualBaseImpl::mVisualPropertyId
PropertyUpdatedStatus Dali::Ui::Internal::VisualBaseImpl::mPropertyUpdatedStatus
bool Dali::Ui::Internal::VisualBaseImpl::mTransformChanged
Whether transform properties changed.
bool Dali::Ui::Internal::VisualBaseImpl::mUpdatePropertyRegistered
Whether the processor for update property is registered.
bool Dali::Ui::Internal::VisualBaseImpl::mApplyFittingModeRegistered
Whether the processor for apply fitting mode is registered.
VisualBaseImplPtr Dali::Ui::Internal::VisualBaseImpl::New(Dali::Ui::Visual::Type type)
Creates a VisualBase object.
Public API. type The type of visual base. The newly created visual object.
Referenced by Dali::Ui::AnimatedImageVisual::New, Dali::Ui::ColorVisual::New, Dali::Ui::ImageVisual::New, Dali::Ui::LottieAnimationVisual::New.
Dali::Ui::View Dali::Ui::Internal::VisualBaseImpl::GetOwner() const
< Public API
< Public API Get attached view. Empty handle if this visual is not be attached. The attached view, or empty handle if not be attached.
Referenced by Dali::Ui::VisualsContainer::GetOwner, Dali::Ui::VisualBase::GetOwner, Process.
Dali::Ui::DevelVisual::InternalContainerRangeType Dali::Ui::Internal::VisualBaseImpl::GetInternalContainerRangeType() const
Get the attached container range type. INVALID if this visual is not be attached.
The attached container range type, or INVALID if not be attached.
Referenced by Dali::Ui::VisualBase::GetContainerRangeType.
void Dali::Ui::Internal::VisualBaseImpl::DetachFromContainer()
Detach from the attached view.
References DetachFromContainerInternal, GetName.
Referenced by Dali::Ui::VisualBase::Detach.
void Dali::Ui::Internal::VisualBaseImpl::DoAction(Dali::Property::Index actionId, const Dali::Property::Value &attributes)
Perform an action on a visual registered to this view. Visuals will have actions, this API is used to perform one of these actions with the given attributes.
If visual is not been registered to the view, action should be ignored. actionId The action to perform. See Visual to find supported actions. attributes Optional attributes for the action.
References Dali::Ui::Visual::Base::DoAction, GetName.
Referenced by Dali::Ui::Visual::Base::DoAction, Dali::Ui::VisualBase::DoAction.
Dali::Ui::Visual::Type Dali::Ui::Internal::VisualBaseImpl::GetVisualType() const
Get the type of this VisualBase.
The type of this VisualBase
Referenced by Dali::Ui::VisualBase::GetVisualType.
void Dali::Ui::Internal::VisualBaseImpl::SetProperty(Dali::Property::Index index, Dali::Property::Value propertyValue)
Sets the value of an existing property.
Properties. BaseHandle is not subclass of Handle. So this API is not use Handle.SetProperty index The index of the property propertyValue The new value of the property
References GetName.
Referenced by Dali::Ui::VisualBase::SetProperty.
Dali::Property::Value Dali::Ui::Internal::VisualBaseImpl::GetProperty(Dali::Property::Index index) const
Retrieves a property value.
BaseHandle is not subclass of Handle. So this API is not use Handle.SetProperty index The index of the property The property value This returns the value set by SetProperty() or the animation target value if it is being animated.
References Dali::Ui::ABSOLUTE, Dali::Ui::DevelVisual::Property::BORDERLINE_COLOR, Dali::Ui::DevelVisual::Property::CORNER_RADIUS_POLICY, GetName, Dali::Ui::VisualBasePropertyIndex::MIX_COLOR.
Referenced by GetBorderlineColor, GetColor, Dali::Ui::VisualBase::GetProperty.
const Dali::String & Dali::Ui::Internal::VisualBaseImpl::GetName() const
Gets the name of the VisualBase.
The name of the VisualBase
Referenced by DetachFromContainer, DoAction, DoActionExtension, Dali::Ui::Visual::Base::GetName, Dali::Ui::VisualBase::GetName, GetProperty, SetName, SetProperty, SetSiblingOrder, SetSiblingOrderInternal, ~VisualBaseImpl.
void Dali::Ui::Internal::VisualBaseImpl::SetName(const Dali::String &name)
Sets the name of this VisualBase.
name The name to set
References GetName.
Referenced by Dali::Ui::VisualBase::SetName, Dali::Ui::Visual::Base::SetName.
UiColor Dali::Ui::Internal::VisualBaseImpl::GetColor() const
Gets the color of the VisualBase.
The color of the VisualBase
References Dali::Ui::UiColorManager::Get, GetProperty, Dali::Ui::VisualBasePropertyIndex::MIX_COLOR.
Referenced by Dali::Ui::VisualBase::GetColor.
void Dali::Ui::Internal::VisualBaseImpl::SetColor(const UiColor &color)
Sets the color of this VisualBase.
color The UiColor to apply
References SetColorBinding.
Referenced by Dali::Ui::VisualBase::SetColor.
float Dali::Ui::Internal::VisualBaseImpl::GetOffsetX() const
Gets the X offset of the VisualBase.
The X offset of the VisualBase
Referenced by Dali::Ui::VisualBase::GetOffsetX.
void Dali::Ui::Internal::VisualBaseImpl::SetOffsetX(float x)
Sets the X offset of the VisualBase.
x The X offset to set
References Dali::Ui::Internal::Visual::Transform::mOffset.
Referenced by Dali::Ui::VisualBase::SetOffsetX.
float Dali::Ui::Internal::VisualBaseImpl::GetOffsetY() const
Gets the Y offset of the VisualBase.
The Y offset of the VisualBase
Referenced by Dali::Ui::VisualBase::GetOffsetY.
void Dali::Ui::Internal::VisualBaseImpl::SetOffsetY(float y)
Sets the Y offset of the VisualBase.
y The Y offset to set
References Dali::Ui::Internal::Visual::Transform::mOffset.
Referenced by Dali::Ui::VisualBase::SetOffsetY.
float Dali::Ui::Internal::VisualBaseImpl::GetWidth() const
Gets the width of the VisualBase.
The width of the VisualBase
Referenced by Dali::Ui::VisualBase::GetWidth.
void Dali::Ui::Internal::VisualBaseImpl::SetWidth(float width)
Sets the width of the VisualBase.
width The width to set
References Dali::Ui::Internal::Visual::Transform::mSize.
Referenced by Dali::Ui::VisualBase::SetWidth.
float Dali::Ui::Internal::VisualBaseImpl::GetHeight() const
Gets the height of the VisualBase.
The height of the VisualBase
Referenced by Dali::Ui::VisualBase::GetHeight.
void Dali::Ui::Internal::VisualBaseImpl::SetHeight(float height)
Sets the height of the VisualBase.
height The height to set
References Dali::Ui::Internal::Visual::Transform::mSize.
Referenced by Dali::Ui::VisualBase::SetHeight.
Dali::Ui::Visual::Transform::ProportionFlags Dali::Ui::Internal::VisualBaseImpl::GetProportionFlags() const
Gets the proportion flags of the VisualBase.
The proportion flags of the VisualBase
Referenced by Dali::Ui::VisualBase::GetProportionFlags.
void Dali::Ui::Internal::VisualBaseImpl::SetProportionFlags(Dali::Ui::Visual::Transform::ProportionFlags flags)
Sets the proportion flags of the VisualBase.
flags The proportion flags to set
References Dali::Ui::Visual::Transform::ALL, Dali::Ui::Internal::Visual::Transform::mOffsetSizeMode.
Referenced by Dali::Ui::VisualBase::SetProportionFlags.
float Dali::Ui::Internal::VisualBaseImpl::GetExtraWidth() const
Gets the extra width of the VisualBase.
The extra width of the VisualBase
Referenced by Dali::Ui::VisualBase::GetExtraWidth.
void Dali::Ui::Internal::VisualBaseImpl::SetExtraWidth(float extraWidth)
Sets the extra width of the VisualBase. This width will be added to final width absolutly, independent as proportion flags.
extraWidth The extra width to set
References Dali::Ui::Internal::Visual::Transform::mExtraSize.
Referenced by Dali::Ui::VisualBase::SetExtraWidth.
float Dali::Ui::Internal::VisualBaseImpl::GetExtraHeight() const
Gets the extra height of the VisualBase.
The extra height of the VisualBase
Referenced by Dali::Ui::VisualBase::GetExtraHeight.
void Dali::Ui::Internal::VisualBaseImpl::SetExtraHeight(float extraHeight)
Sets the extra height of the VisualBase. This height will be added to final height absolutly, independent as proportion flags.
extraHeight The extra height to set
References Dali::Ui::Internal::Visual::Transform::mExtraSize.
Referenced by Dali::Ui::VisualBase::SetExtraHeight.
Align::Type Dali::Ui::Internal::VisualBaseImpl::GetOrigin() const
Gets the origin of the VisualBase.
The origin of the VisualBase
References Dali::Ui::Align::TOP_BEGIN.
Referenced by Dali::Ui::VisualBase::GetOrigin.
void Dali::Ui::Internal::VisualBaseImpl::SetOrigin(Dali::Ui::Align::Type origin)
Sets the origin of the VisualBase.
origin The origin type to set
References Dali::Ui::Internal::Visual::Transform::mOrigin, Dali::Ui::Align::TOP_BEGIN.
Referenced by Dali::Ui::VisualBase::SetOrigin.
Align::Type Dali::Ui::Internal::VisualBaseImpl::GetPivot() const
Gets the pivot of the VisualBase.
The pivot of the VisualBase
References Dali::Ui::Align::TOP_BEGIN.
Referenced by Dali::Ui::VisualBase::GetPivot.
void Dali::Ui::Internal::VisualBaseImpl::SetPivot(Dali::Ui::Align::Type pivot)
Sets the pivot of the VisualBase.
pivot The pivot to set
References Dali::Ui::Internal::Visual::Transform::mPivot, Dali::Ui::Align::TOP_BEGIN.
Referenced by Dali::Ui::VisualBase::SetPivot.
UiColor Dali::Ui::Internal::VisualBaseImpl::GetBorderlineColor() const
Gets the borderline color of the VisualBase.
The borderline color
References Dali::Ui::DevelVisual::Property::BORDERLINE_COLOR, Dali::Ui::UiColorManager::Get, GetProperty.
Referenced by Dali::Ui::VisualBase::GetBorderlineColor.
void Dali::Ui::Internal::VisualBaseImpl::SetBorderlineColor(const UiColor &color)
Sets the borderline color of the VisualBase.
Only supported type of visual has efforts. If the UiColor has a color ID, it is resolved from the current theme and a binding is registered so the color is automatically refreshed when the theme changes. color The UiColor to apply
References SetColorBinding.
Referenced by Dali::Ui::VisualBase::SetBorderlineColor.
uint32_t Dali::Ui::Internal::VisualBaseImpl::GetSiblingOrder() const
Sibling Order Change API.
Sibling Order Change API. Get the sibling order of the visual object inside of the container. The sibling order inside of the container. Or 0 if visual object is not in container.
Referenced by Dali::Ui::VisualBase::GetSiblingOrder, LowerBelow, RaiseAbove.
void Dali::Ui::Internal::VisualBaseImpl::SetSiblingOrder(uint32_t siblingOrder)
Set the sibling order of the visual object inside of the container.
It will change other VisualBase's sibling order to keep the order. It will throw assert if siblingOrder is bigger than the number of visuals that contianer has. siblingOrder The sibling order inside of the container.
References Dali::Ui::GetImplementation, GetName.
Referenced by Lower, LowerBelow, LowerToBottom, Raise, RaiseAbove, RaiseToTop, Dali::Ui::VisualBase::SetSiblingOrder.
void Dali::Ui::Internal::VisualBaseImpl::Raise()
Raise the visual object above the next sibling visual object.
The VisualBase has been initialized. The VisualBase has been parented.
References SetSiblingOrder.
Referenced by Dali::Ui::VisualBase::Raise.
void Dali::Ui::Internal::VisualBaseImpl::Lower()
Lower the visual object below the previous sibling visual object.
The VisualBase has been initialized. The VisualBase has been parented.
References SetSiblingOrder.
Referenced by Dali::Ui::VisualBase::Lower.
void Dali::Ui::Internal::VisualBaseImpl::RaiseToTop()
Raise visual object above all other sibling visual objects.
The VisualBase has been initialized. The VisualBase has been parented.
References SetSiblingOrder.
Referenced by Dali::Ui::VisualBase::RaiseToTop.
void Dali::Ui::Internal::VisualBaseImpl::LowerToBottom()
Lower visual object to the bottom of all other sibling visual objects.
The VisualBase has been initialized. The VisualBase has been parented.
References SetSiblingOrder.
Referenced by Dali::Ui::VisualBase::LowerToBottom.
void Dali::Ui::Internal::VisualBaseImpl::RaiseAbove(Dali::Ui::Internal::VisualBaseImpl &target)
Raises the visual object above the target visual object.
target The target visual object The VisualBase has been initialized. The VisualBase has been parented. The target visual object is a sibling.
References GetContainer, GetSiblingOrder, SetSiblingOrder.
Referenced by Dali::Ui::VisualBase::RaiseAbove.
void Dali::Ui::Internal::VisualBaseImpl::LowerBelow(Dali::Ui::Internal::VisualBaseImpl &target)
Lower the visual object to below the target visual object.
target The target visual object The VisualBase has been initialized. The VisualBase has been parented. The target visual object is a sibling.
References GetContainer, GetSiblingOrder, SetSiblingOrder.
Referenced by Dali::Ui::VisualBase::LowerBelow.
Dali::Ui::VisualsContainer Dali::Ui::Internal::VisualBaseImpl::GetContainer() const
< Called from Internal::VisualsContainer
Get the Container who contain this visual object. VisualsContainer who contain this visual object. Or empty container if visual object is not in container.
Referenced by LowerBelow, RaiseAbove.
void Dali::Ui::Internal::VisualBaseImpl::AttachToContainerInternal(Dali::Ui::VisualsContainer container)
Set the container who contain this visual object.
It should be called only from Internal::VisualBaseImpl or Internal::VisualsContainer. container VisualsContainer who contain this visual object. Or empty container if visual object is not in container.
References Dali::Ui::VisualsContainer::GetContainerRangeType.
void Dali::Ui::Internal::VisualBaseImpl::DetachFromContainerInternal()
Detach from container without change the container.
It should be called only from Internal::VisualBaseImpl or Internal::VisualsContainer.
References Dali::Ui::DevelVisual::INVALID, INVALID_VISUAL_PROPERTY_ID.
Referenced by DetachFromContainer, ~VisualBaseImpl.
void Dali::Ui::Internal::VisualBaseImpl::SetSiblingOrderInternal(uint32_t siblingOrder)
Set the sibling order without change the container.
It should be called only from Internal::VisualBaseImpl or Internal::VisualsContainer. siblingOrder The sibling order inside of the container.
References GetDepthIndex, GetName, Dali::Ui::Visual::Base::SetDepthIndex.
int32_t Dali::Ui::Internal::VisualBaseImpl::GetDepthIndex() const
Get the depth index of visual, depend by sibling order.
It should be called only from Internal::VisualBaseImpl or Internal::VisualsContainer. The depth index of visual.
References Dali::Ui::DepthIndex::BACKGROUND, Dali::Ui::DevelVisual::BACKGROUND, Dali::Ui::DepthIndex::BACKGROUND_EFFECT, Dali::Ui::DevelVisual::BACKGROUND_EFFECT, Dali::Ui::DevelVisual::BETWEEN_BACKGROUND_AND_CONTENT, Dali::Ui::DevelVisual::BETWEEN_BACKGROUND_EFFECT_AND_BACKGROUND, Dali::Ui::DevelVisual::BETWEEN_CONTENT_AND_DECORATION, Dali::Ui::DevelVisual::BETWEEN_DECORATION_AND_FOREGROUND_EFFECT, Dali::Ui::DepthIndex::CONTENT, Dali::Ui::DevelVisual::CONTENT, Dali::Ui::DepthIndex::DECORATION, Dali::Ui::DevelVisual::DECORATION, Dali::Ui::DepthIndex::FOREGROUND_EFFECT, Dali::Ui::DevelVisual::FOREGROUND_EFFECT, Dali::Ui::DepthIndex::MINIMUM_DEPTH_INDEX, Dali::Ui::DevelVisual::OVER_FOREGROUND_EFFECT, Dali::Ui::DevelVisual::UNDER_BACKGROUND_EFFECT.
Referenced by Dali::Ui::Visual::Base::GetDepthIndex, SetSiblingOrderInternal.
void Dali::Ui::Internal::VisualBaseImpl::SetShadowType(Dali::Ui::VisualsContainer::ShadowType shadowType)
Sets the shadow type for this visual object.
This method defines how the visual object should be treated in terms of shadow rendering and corner radius calculations. The shadow type influences the internal constraints and properties applied to the visual, especially when it's registered with a control that supports corner radius overrides. shadowType The type of shadow to be applied to the visual object. Can be NONE, BOX_SHADOW, or INNER_SHADOW. GetShadowType(), Dali::VisualsContainer::ShadowType
Dali::Ui::VisualsContainer::ShadowType Dali::Ui::Internal::VisualBaseImpl::GetShadowType() const
Retrieves the currently configured shadow type for this visual object.
This method returns the shadow type that was previously set via SetShadowType. It allows other parts of the system, particularly the VisualsContainer during visual registration or property updates, to query the visual's shadow behavior and apply the corresponding rendering logic and constraints. The shadow type of the visual object. SetShadowType(), Dali::Ui::VisualsContainer::ShadowType
Dali::Ui::Visual::Base Dali::Ui::Internal::VisualBaseImpl::GetVisual() const
Get the Visual::Base object what this object hold.
It should be called only from Internal::VisualBase or Internal::VisualsContainer. Latest created Visual::Base object created by VisualBase::CreateVisual();
void Dali::Ui::Internal::VisualBaseImpl::SetVisualPropertyId(VisualPropertyId visualPropertyId)
Set the unique id of visual what it registered into control.
visualPropertyId The id of visual property registered.
VisualPropertyId Dali::Ui::Internal::VisualBaseImpl::GetVisualPropertyId() const
Get the unique id of visual what it registered into control.
The id of visual property registered
Dali::Property Dali::Ui::Internal::VisualBaseImpl::GetPropertyObject(Dali::Property::Key visualPropertyKey)
< Called from other internal class
Retrieve the property object associated with the given visual property key. It will return invalid property if visual object is not be attached to any view. Returned Property will be invalidated after we call CreateVisual method. visualPropertyKey The key of the visual's property. The Property object
References Dali::Ui::Visual::Base::GetPropertyObject.
Referenced by Dali::Ui::Visual::Base::GetPropertyObject.
void Dali::Ui::Internal::VisualBaseImpl::RemoveCache(Dali::Property::Index index) const
Remove cached data of given index.
We can call this function at const case since cache is mutable. index The index want to remove cache.
Referenced by Dali::Ui::LottieAnimationVisual::GetContentInfo, Dali::Ui::AnimatedImageVisual::GetCurrentFrameNumber, Dali::Ui::LottieAnimationVisual::GetCurrentFrameNumber, Dali::Ui::LottieAnimationVisual::GetMarkerInfo, Dali::Ui::AnimatedImageVisual::GetPlayState, Dali::Ui::LottieAnimationVisual::GetPlayState, Dali::Ui::AnimatedImageVisual::GetTotalFrameNumber, Dali::Ui::LottieAnimationVisual::GetTotalFrameNumber.
void Dali::Ui::Internal::VisualBaseImpl::UpdateProperty()
Update properties manually.
Referenced by Dali::Ui::AnimatedImageVisual::JumpTo, Dali::Ui::LottieAnimationVisual::JumpTo, Dali::Ui::AnimatedImageVisual::Pause, Dali::Ui::LottieAnimationVisual::Pause, Dali::Ui::AnimatedImageVisual::Play, Dali::Ui::LottieAnimationVisual::Play, Dali::Ui::LottieAnimationVisual::SetDynamicProperty, Dali::Ui::AnimatedImageVisual::Stop, Dali::Ui::LottieAnimationVisual::Stop.
void Dali::Ui::Internal::VisualBaseImpl::DoActionExtension(Dali::Property::Index actionId, const Dali::Any &attributes)
Performs an action on the visual with the given action id and attributes.
actionId The id of the action to perform this API only takes an Index attributes The list of attributes for the action. ( optional for this data structure to have content )
References Dali::Ui::Visual::Base::DoActionExtension, GetName.
Referenced by Dali::Ui::Visual::Base::DoActionExtension, Dali::Ui::LottieAnimationVisual::SetDynamicProperty.
Dali::Ui::Internal::VisualBaseImpl::~VisualBaseImpl() override
Destructor.
References DetachFromContainerInternal, Dali::Ui::VisualFactory::Get, GetName.
void Dali::Ui::Internal::VisualBaseImpl::Process(bool postProcessor) override
References GetOwner, Dali::Ui::View::GetPadding.
std::string_view Dali::Ui::Internal::VisualBaseImpl::GetProcessorName() const override
Dali::Ui::Internal::VisualBaseImpl::VisualBaseImpl(Dali::Ui::Visual::Type type)
Constructor - creates a VisualBaseImpl.
References Dali::Ui::VisualBasePropertyIndex::MIX_COLOR, Dali::Ui::VisualBasePropertyIndex::TYPE.
void Dali::Ui::Internal::VisualBaseImpl::SetColorBinding(StringView bindingId, const UiColor &color, T *inst, void(T::*setter)(const Vector4 &))
Registers a color binding for theme-aware color updates.
T Type of the instance (ViewImpl or a derived class) bindingId Caller-defined identifier for this binding color The UiColor to apply inst The object whose setter will be used as the callback setter Member function called both immediately and on theme change
References Dali::Ui::UiColorManager::Get, Dali::Ui::UiColor::GetRgba, Dali::Ui::UiColor::HasColorId.
Referenced by SetBorderlineColor, SetColor.
void Dali::Ui::Internal::VisualBaseImpl::CreateVisual(const Dali::Property::Map &map)
Create Visual with Property::Map.
It will remove previous visual. map The Creation information of the visual.
void Dali::Ui::Internal::VisualBaseImpl::RetrieveVisualPropertyMap(Dali::Property::Map &map) const
Get the visual property map.
map The visual property map.
void Dali::Ui::Internal::VisualBaseImpl::SetColorInternal(const Vector4 &color)
Set color value internally.
void Dali::Ui::Internal::VisualBaseImpl::SetBorderlineColorInternal(const Vector4 &borderlineColor)
Set borderline color value internally.
Internal::Visual::Transform & Dali::Ui::Internal::VisualBaseImpl::GetOrCreateTransform()
Ensure to create Transform class, and return it.
Transform info.
void Dali::Ui::Internal::VisualBaseImpl::ApplyTransfromToPropertyMap()
Apply transform infomations to cched visual property map.
void Dali::Ui::Internal::VisualBaseImpl::RequestUpdateProperty()
Register processor for update property.
void Dali::Ui::Internal::VisualBaseImpl::RequestApplyFittingMode()
Register processor for apply fitting mode.
void Dali::Ui::Internal::VisualBaseImpl::UpdatePropertyInternal()
Update properties for visual.
void Dali::Ui::Internal::VisualBaseImpl::ApplyFittingModeInternal(const Vector2 &controlSize, const Extents &viewPadding)
Apply fitting mode for visual.
controlSize The size of the parent control. viewPadding The padding of the parent control (start, end, top, bottom). For RTL layouts, start/end should already be swapped by the caller.