Dali::Ui::VisualsContainer
ShadowType
Represents a standard box shadow (drop shadow) outside the visual.
VisualsContainer Dali::Ui::VisualsContainer::New(Dali::Ui::View view, Dali::Ui::DevelVisual::InternalContainerRangeType rangeType)
Creates a VisualsContainer object.
view The view that owns this VisualsContainer. rangeType The range type of this VisualsContainer. The newly created visual objects container The view should not create another VisualsContainer for each rangeType.
References VisualsContainer.
VisualsContainer Dali::Ui::VisualsContainer::DownCast(BaseHandle handle)
Downcasts a handle to VisualsContainer handle.
Public API. handle Handle to an object A handle to a VisualsContainer or an uninitialized handle
References VisualsContainer.
Dali::Ui::View Dali::Ui::VisualsContainer::GetOwner() const
< Public API
Get the owner of this container. The owner of this container, or empty handle if owner is invalid.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetOwner.
Dali::Ui::DevelVisual::InternalContainerRangeType Dali::Ui::VisualsContainer::GetContainerRangeType() const
Gets the range type of VisualsContainer.
The range type of VisualsContainer.
References Dali::Ui::GetImplementation.
Referenced by Dali::Ui::Internal::VisualBaseImpl::AttachToContainerInternal.
uint32_t Dali::Ui::VisualsContainer::GetVisualBasesCount() const
Gets the number of visual objects in the container.
The number of visual objects in the container.
References Dali::Ui::GetImplementation.
Dali::Ui::VisualBase Dali::Ui::VisualsContainer::GetVisualBaseAt(uint32_t index) const
Get the visual objects from the container.
If index is out of range, will throw exception. index The index of the visual object to get. The visual object at the given index.
References Dali::Ui::GetImplementation.
bool Dali::Ui::VisualsContainer::AddVisualBase(Dali::Ui::VisualBase visualObject)
Adds a visual object to the container. Added visual object will be placed top of other visuals. If the container cannot add more than maximum count of objects or the visual object is already added, It will be ignored.
visualObject The visual object to be added. True if the visual object is added successfully.
References Dali::Ui::GetImplementation.
bool Dali::Ui::VisualsContainer::AddShadowVisualBase(Dali::Ui::VisualBase visualObject, ShadowType shadowType)
Adds a shadow visual object to the container.
This method adds a visual object specifically intended to be rendered as a shadow. It configures the visual object based on the specified shadow type (e.g., BOX_SHADOW or INNER_SHADOW), applying appropriate internal flags and constraints for correct rendering. For instance, inner shadows require specialized corner radius calculations to account for borderline width. The added visual object will be placed on top of other visuals within the container. If the container cannot add more than the maximum count of objects, or if the visual object is already added to this or another container, the operation will be ignored. visualObject The visual object to be added as a shadow. shadowType The type of shadow (e.g., BOX_SHADOW, INNER_SHADOW). True if the shadow visual object is added successfully, false otherwise.
References Dali::Ui::GetImplementation.
void Dali::Ui::VisualsContainer::RemoveVisualBase(Dali::Ui::VisualBase visualObject)
Removes a visual object from the container. All other visual objects will be shifted down.
visualObject The visual object to be added.
References Dali::Ui::GetImplementation.
Dali::Ui::VisualsContainer::VisualsContainer()=default
Referenced by DownCast, New.
Dali::Ui::VisualsContainer::~VisualsContainer()=default
Dali::Ui::VisualsContainer::VisualsContainer(const VisualsContainer &handle)=default
VisualsContainer & Dali::Ui::VisualsContainer::operator=(const VisualsContainer &rhs)=default
Dali::Ui::VisualsContainer::VisualsContainer(VisualsContainer &&rhs) noexcept=default
VisualsContainer & Dali::Ui::VisualsContainer::operator=(VisualsContainer &&rhs) noexcept=default
Dali::Ui::VisualsContainer::VisualsContainer(Dali::Ui::Internal::VisualsContainer *object)
This constructor is used by Dali New() methods.
object A pointer to a newly allocated Dali resource