Dali::Ui::Integration::InputFieldImpl
Signal<void(View)> Dali::Ui::Integration::InputFieldImpl::mTextChangedSignal
Signal<void(View)> Dali::Ui::Integration::InputFieldImpl::mMaxLengthReachedSignal
Signal<void(View, Text::InputFilter::RejectReason)> Dali::Ui::Integration::InputFieldImpl::mInputRejectedSignal
Signal<void(View, uint32_t)> Dali::Ui::Integration::InputFieldImpl::mCursorPositionChangedSignal
Signal<void(View)> Dali::Ui::Integration::InputFieldImpl::mSelectionStartedSignal
Signal<void(View, uint32_t, uint32_t)> Dali::Ui::Integration::InputFieldImpl::mSelectionChangedSignal
Signal<void(View)> Dali::Ui::Integration::InputFieldImpl::mSelectionClearedSignal
Signal<void(View, Text::TypingStyle::Mask)> Dali::Ui::Integration::InputFieldImpl::mTypingStyleChangedSignal
InputMethodContext Dali::Ui::Integration::InputFieldImpl::mInputMethodContext
TapGestureDetector Dali::Ui::Integration::InputFieldImpl::mTapGestureDetector
PanGestureDetector Dali::Ui::Integration::InputFieldImpl::mPanGestureDetector
LongPressGestureDetector Dali::Ui::Integration::InputFieldImpl::mLongPressGestureDetector
Text::ControllerPtr Dali::Ui::Integration::InputFieldImpl::mController
Text::RendererPtr Dali::Ui::Integration::InputFieldImpl::mRenderer
Text::DecoratorPtr Dali::Ui::Integration::InputFieldImpl::mDecorator
Actor Dali::Ui::Integration::InputFieldImpl::mStencil
std::vector<Actor> Dali::Ui::Integration::InputFieldImpl::mClippingDecorationActors
Decoration actors which need clipping.
std::vector<Ui::TextAnchor> Dali::Ui::Integration::InputFieldImpl::mAnchorActors
Dali::InputMethodOptions Dali::Ui::Integration::InputFieldImpl::mInputMethodOptions
Actor Dali::Ui::Integration::InputFieldImpl::mRenderableActor
Actor Dali::Ui::Integration::InputFieldImpl::mActiveLayer
Actor Dali::Ui::Integration::InputFieldImpl::mCursorLayer
Actor Dali::Ui::Integration::InputFieldImpl::mBackgroundActor
Text::OverflowMode Dali::Ui::Integration::InputFieldImpl::mOverflowMode
float Dali::Ui::Integration::InputFieldImpl::mAlignmentOffset
bool Dali::Ui::Integration::InputFieldImpl::mMeasureInvalidated
bool Dali::Ui::Integration::InputFieldImpl::mHasBeenStaged
bool Dali::Ui::Integration::InputFieldImpl::mTextChanged
If true, emits TextChangedSignal in next OnRelayout().
bool Dali::Ui::Integration::InputFieldImpl::mCursorPositionChanged
If true, emits CursorPositionChangedSignal at the end of OnRelayout().
bool Dali::Ui::Integration::InputFieldImpl::mSelectionStarted
If true, emits SelectionStartedSignal at the end of OnRelayout().
bool Dali::Ui::Integration::InputFieldImpl::mSelectionChanged
If true, emits SelectionChangedSignal at the end of OnRelayout().
bool Dali::Ui::Integration::InputFieldImpl::mSelectionCleared
If true, emits SelectionClearedSignal at the end of OnRelayout().
InputFieldImplPtr Dali::Ui::Integration::InputFieldImpl::New()
Creates a new InputField.
References InputFieldImpl.
Referenced by Dali::Ui::InputField::New.
void Dali::Ui::Integration::InputFieldImpl::SetProperty(BaseObject *object, Dali::Property::Index index, const Dali::Property::Value &value)
Called when a property of an object of this type is set.
object The object whose property is set. index The property index. value The new property value.
References Dali::Ui::View::DownCast, Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::Property::Value Dali::Ui::Integration::InputFieldImpl::GetProperty(BaseObject *object, Dali::Property::Index index)
Called to retrieve a property of an object of this type.
object The object whose property is to be retrieved. index The property index. The current value of the property.
References Dali::Ui::View::DownCast, Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
Dali::Ui::Integration::InputFieldImpl::~InputFieldImpl()
A reference counted object may only be deleted by calling Unreference()
Dali::Ui::Integration::InputFieldImpl::InputFieldImpl()
InputFieldImpl constructor.
Referenced by New.
MeasuredSize Dali::Ui::Integration::InputFieldImpl::OnMeasure(float widthConstraint, float heightConstraint) override
Called during measure pass. Override to implement custom measurement.
widthConstraint Available visual (scale-applied) width, or WRAP_CONTENT / MATCH_PARENT. heightConstraint Available visual (scale-applied) height, or WRAP_CONTENT / MATCH_PARENT. Measured visual (scale-applied) size.
References Dali::Ui::ViewImpl::GetEffectiveScale, GetEffectiveTextPadding, Dali::Ui::ViewImpl::GetMaximumHeight, Dali::Ui::ViewImpl::GetMaximumWidth, Dali::Ui::ViewImpl::GetMinimumHeight, Dali::Ui::ViewImpl::GetMinimumWidth, GetNaturalSize, Dali::Ui::ViewImpl::GetRequestedHeight, Dali::Ui::ViewImpl::GetRequestedWidth, GetText, Dali::Ui::MATCH_PARENT, SetTextUiScale, Dali::Ui::WRAP_CONTENT.
MeasuredSize Dali::Ui::Integration::InputFieldImpl::OnArrange(const LayoutRect &bounds) override
Called during arrange pass. Override to implement custom arrangement.
References Dali::Ui::LayoutRect::height, Dali::Ui::LayoutRect::width, Dali::Ui::LayoutRect::x, Dali::Ui::LayoutRect::y.
void Dali::Ui::Integration::InputFieldImpl::SetText(const Dali::String &text)
Sets the text.
text The text to display in UTF-8 format.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::InputFieldImpl::GetText() const
Gets the text.
The text currently set on the inputField in UTF-8 format.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty, OnMeasure.
void Dali::Ui::Integration::InputFieldImpl::SetFontFamily(const Dali::String &fontFamily)
Sets the font family of the text.
fontFamily The requested font family to use.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::InputFieldImpl::GetFontFamily() const
Gets the font family of the text.
The font family currently set on the inputField.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetFontSize(float fontSize)
Sets the font size of the text.
fontSize The font size in pixels.
Referenced by ApplyInitialConfig, Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::InputFieldImpl::GetFontSize() const
Gets the font size of the text.
The font size currently set on the inputField, in pixels.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTextColor(const UiColor &color)
Sets the color of the text.
color The required text color value.
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by ApplyInitialConfig, Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::InputFieldImpl::GetTextColor()
Gets the color of the text.
The text color currently set on the inputField.
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetHorizontalTextAlignment(Text::Alignment alignment)
Sets the horizontal alignment of the text within the inputField.
alignment The horizontal text alignment.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::Alignment Dali::Ui::Integration::InputFieldImpl::GetHorizontalTextAlignment() const
Gets the horizontal text alignment.
The horizontal text alignment.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetVerticalTextAlignment(Text::Alignment alignment)
Sets the vertical alignment of the text within the inputField.
alignment The vertical text alignment.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::Alignment Dali::Ui::Integration::InputFieldImpl::GetVerticalTextAlignment() const
Gets the vertical text alignment.
The vertical text alignment.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetOverflowMode(Text::OverflowMode mode)
Sets the overflow mode.
mode The overflow mode to apply.
References Dali::Ui::Text::CLIP, Dali::Ui::Text::ELLIPSIS.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::OverflowMode Dali::Ui::Integration::InputFieldImpl::GetOverflowMode() const
Gets the overflow mode.
The current overflow mode.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetPlaceholder(const Dali::String &text)
Sets the placeholder text displayed when the input field is empty.
text The placeholder text in UTF-8 encoding.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::InputFieldImpl::GetPlaceholder() const
Gets the placeholder text.
The placeholder text in UTF-8 encoding.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetPlaceholderColor(const UiColor &color)
Sets the color of the placeholder text.
color The placeholder text color as a UiColor.
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by ApplyInitialConfig, Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::InputFieldImpl::GetPlaceholderColor()
Gets the color of the placeholder text.
The placeholder text color as a UiColor.
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetShowPlaceholderOnFocus(bool enabled)
Sets whether the placeholder text is shown when the input field has focus.
enabled True to show the placeholder text when focused, false otherwise.
Referenced by ApplyInitialConfig, Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
bool Dali::Ui::Integration::InputFieldImpl::IsPlaceholderShownOnFocus() const
Returns whether the placeholder text is shown when the input field has focus.
True if the placeholder text is shown when focused, false otherwise.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetCursorWidth(int width)
Sets the width of the text cursor.
width The cursor width in pixels.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
int Dali::Ui::Integration::InputFieldImpl::GetCursorWidth() const
Gets the width of the text cursor.
The cursor width in pixels.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetCursorColor(const UiColor &color)
Sets the color of the text cursor.
This color is applied to both primary and secondary cursors when a split cursor is shown in bidirectional text. color The cursor color as a UiColor.
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::InputFieldImpl::GetCursorColor()
Gets the color of the text cursor.
The cursor color as a UiColor.
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetCursorBlinkEnabled(bool enabled)
Sets whether the cursor should blink.
enabled True to enable cursor blinking, false otherwise.
References RequestTextRelayout.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
bool Dali::Ui::Integration::InputFieldImpl::IsCursorBlinkEnabled() const
Returns whether the cursor is set to blink.
True if cursor blinking is enabled, false otherwise.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetCursorBlinkInterval(float interval)
Sets the time interval in seconds between cursor on and off states.
interval The cursor blink interval in seconds.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::InputFieldImpl::GetCursorBlinkInterval() const
Returns the time interval in seconds between cursor on and off states.
The cursor blink interval in seconds.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetCursorPosition(uint32_t position)
Sets the cursor position.
The position is specified as a character index in the current text. position The cursor position.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
uint32_t Dali::Ui::Integration::InputFieldImpl::GetCursorPosition() const
Returns the current cursor position.
The returned value is the character index in the current text. The current cursor position.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetSelectionEnabled(bool enabled)
Sets whether text selection is enabled.
enabled True to enable text selection, false otherwise.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
bool Dali::Ui::Integration::InputFieldImpl::IsSelectionEnabled() const
Returns whether text selection is enabled.
True if text selection is enabled, false otherwise.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetSelectionColor(const UiColor &color)
Sets the highlight color of the selected text region.
color The selection highlight color as a UiColor).
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::InputFieldImpl::GetSelectionColor()
Gets the highlight color of the selected text region.
The selection highlight color as a UiColor.
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTextHandleEnabled(bool enabled)
Sets whether text editing handles are enabled.
Text editing handles include the cursor handle (shown below the insertion cursor) and the left/right selection handles (shown at both ends of the selected text range). enabled True to enable text editing handles, false otherwise.
References RequestTextRelayout.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
bool Dali::Ui::Integration::InputFieldImpl::IsTextHandleEnabled() const
Returns whether text editing handles are enabled.
True if text editing handles are enabled, false otherwise.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTextHandleColor(const UiColor &color)
Sets the color of the text editing handles.
This color is applied to both the cursor handle and the left/right selection handles. color The text editing handle color as a UiColor.
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::InputFieldImpl::GetTextHandleColor() const
Gets the color of the text editing handles.
The text editing handle color as a UiColor.
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetCursorHandleImage(const Dali::String &image)
Sets the cursor handle image.
The cursor handle is shown below the insertion cursor when there is no selection range. image The cursor handle image URL.
References RequestTextRelayout.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::InputFieldImpl::GetCursorHandleImage() const
Gets the cursor handle image.
The cursor handle image URL.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetCursorHandlePressedImage(const Dali::String &image)
Sets the pressed cursor handle image.
The cursor handle is shown below the insertion cursor when there is no selection range. image The pressed cursor handle image URL.
References RequestTextRelayout.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::InputFieldImpl::GetCursorHandlePressedImage() const
Gets the pressed cursor handle image.
The pressed cursor handle image URL.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetSelectionHandleImageLeft(const Dali::String &image)
Sets the left selection handle image.
The selection handle is shown at the left bound of the selected text range. image The left selection handle image URL.
References RequestTextRelayout.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::InputFieldImpl::GetSelectionHandleImageLeft() const
Gets the left selection handle image.
The left selection handle image URL.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetSelectionHandleImageRight(const Dali::String &image)
Sets the right selection handle image.
The selection handle is shown at the right bound of the selected text range. image The right selection handle image URL.
References RequestTextRelayout.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::InputFieldImpl::GetSelectionHandleImageRight() const
Gets the right selection handle image.
The right selection handle image URL.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetSelectionHandlePressedImageLeft(const Dali::String &image)
Sets the pressed left selection handle image.
The selection handle is shown at the left bound of the selected text range. image The pressed left selection handle image URL.
References RequestTextRelayout.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::InputFieldImpl::GetSelectionHandlePressedImageLeft() const
Gets the pressed left selection handle image.
The pressed left selection handle image URL.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetSelectionHandlePressedImageRight(const Dali::String &image)
Sets the pressed right selection handle image.
The selection handle is shown at the right bound of the selected text range. image The pressed right selection handle image URL.
References RequestTextRelayout.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::InputFieldImpl::GetSelectionHandlePressedImageRight() const
Gets the pressed right selection handle image.
The pressed right selection handle image URL.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetMaximumLength(int length)
Sets the maximum number of characters that can be entered into the InputField.
length The maximum number of characters allowed.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
int Dali::Ui::Integration::InputFieldImpl::GetMaximumLength() const
Gets the maximum number of characters allowed in the InputField.
The maximum character count.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetInputFilter(const Text::InputFilter &inputFilter)
Sets the input filter.
The input filter defines allow and deny patterns used to filter text before it is inserted. If an allow pattern is set, input that does not match the pattern is rejected. If a deny pattern is set, input that matches the pattern is rejected. If both patterns are set, input must match the allow pattern and must not match the deny pattern. This filter is applied to inserted input, such as user input, input method commits, and paste operations. It is not applied when text is set directly with SetText(). inputFilter The input filter to apply. This input field.
References Dali::Ui::Text::InputFilter::GetAllowPattern, Dali::Ui::Text::InputFilter::GetDenyPattern.
void Dali::Ui::Integration::InputFieldImpl::ClearInputFilter()
Clears the input filter.
After clearing the input filter, all input is allowed unless another input filter is set. This input field.
void Dali::Ui::Integration::InputFieldImpl::SetPasswordMode(Text::PasswordMode mode)
Sets the password display mode.
- PasswordMode::NONE: Password masking is not used. The input text is displayed as-is. PasswordMode::HIDE_ALL: All input characters are displayed using the password mask character. PasswordMode::REVEAL_LAST_CHARACTER: The last entered character is briefly displayed for the password reveal duration, then replaced with the password mask character. mode The password display mode. This input field.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::PasswordMode Dali::Ui::Integration::InputFieldImpl::GetPasswordMode() const
Gets the current password display mode.
The current password display mode.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetPasswordMaskCharacter(uint32_t character)
Sets the password mask character as a Unicode code point.
This character is used to mask the password text when PasswordMode is HIDE_ALL or REVEAL_LAST_CHARACTER. The parameter is a Unicode code point. For example: '*' is U+002A (0x2A) '•' is U+2022 (0x2022) Although the parameter type is uint32_t, only valid Unicode code points should be used. When setting this property via the property system, Property::INTEGER is used, so only code points within the int range can be safely passed through the property system. character The Unicode code point of the password mask character. This input field.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
uint32_t Dali::Ui::Integration::InputFieldImpl::GetPasswordMaskCharacter() const
Gets the password mask character as a Unicode code point.
The Unicode code point of the password mask character.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetPasswordRevealDuration(uint32_t duration)
Sets the password reveal duration in milliseconds.
This value is used when PasswordMode is REVEAL_LAST_CHARACTER to determine how long the last entered character remains visible before being masked. A duration of 0 means the character is immediately masked. duration The password reveal duration in milliseconds. This input field.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
uint32_t Dali::Ui::Integration::InputFieldImpl::GetPasswordRevealDuration() const
Gets the password reveal duration in milliseconds.
The password reveal duration in milliseconds.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetLayoutDirectionMode(Text::LayoutDirectionMode mode)
Sets how the layout direction of the text is resolved.
- LayoutDirectionMode::CONTENTS: The layout direction is determined from the text content itself. LayoutDirectionMode::INHERIT: The layout direction is inherited from the parent view. LayoutDirectionMode::LOCALE: The layout direction is determined based on the system locale. The default layout direction mode of InputField is LayoutDirectionMode::INHERIT. mode The LayoutDirectionMode used to determine the text layout direction.
References RequestTextRelayout.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::LayoutDirectionMode Dali::Ui::Integration::InputFieldImpl::GetLayoutDirectionMode() const
Gets the current layout direction mode.
The LayoutDirectionMode used to resolve the text layout direction.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetMarkupEnabled(bool enabled)
Enables or disables mark-up processing for the input text.
When enabled, markup tags in the input text are interpreted and rendered accordingly. When disabled, the input text is treated as plain text. enabled True to enable mark-up parsing, false to render text as plain string.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
bool Dali::Ui::Integration::InputFieldImpl::IsMarkupEnabled() const
Gets whether mark-up processing is enabled.
True if mark-up parsing is enabled, otherwise false.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetFontWeight(Text::FontWeight weight)
Sets the font weight.
weight The font weight.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::FontWeight Dali::Ui::Integration::InputFieldImpl::GetFontWeight() const
Returns the font weight.
The font weight.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetFontWidth(Text::FontWidth width)
Sets the font width.
width The font width.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::FontWidth Dali::Ui::Integration::InputFieldImpl::GetFontWidth() const
Returns the font width.
The font width.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetFontSlant(Text::FontSlant slant)
Sets the font slant.
slant The font slant.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::FontSlant Dali::Ui::Integration::InputFieldImpl::GetFontSlant() const
Returns the font slant.
The font slant.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTextBackgroundColor(const UiColor &color)
Sets the background color behind the text.
The background is rendered behind the glyphs of the text. color The text background color. This input field.
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::InputFieldImpl::GetTextBackgroundColor() const
Gets the background color behind the text.
The current text background color.
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::ClearTextBackgroundColor()
Clears the text background color.
Disables the text background and removes the previously set color.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::InputFieldImpl::SetUnderline(const Text::Underline &underline)
Sets the underline style.
underline The underline configuration.
References Dali::Ui::Text::Underline::GetColor, Dali::Ui::ViewImpl::SetColorBinding.
void Dali::Ui::Integration::InputFieldImpl::ClearUnderline()
Clears the underline style.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::InputFieldImpl::SetShadow(const Text::Shadow &shadow)
Sets the shadow style.
shadow The shadow configuration.
References Dali::Ui::Text::Shadow::GetColor, Dali::Ui::ViewImpl::SetColorBinding.
void Dali::Ui::Integration::InputFieldImpl::ClearShadow()
Clears the shadow style.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::InputFieldImpl::SetOutline(const Text::Outline &outline)
Sets the outline style.
outline The outline configuration.
References Dali::Ui::Text::Outline::GetColor, Dali::Ui::ViewImpl::SetColorBinding.
void Dali::Ui::Integration::InputFieldImpl::ClearOutline()
Clears the outline style.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::InputFieldImpl::SetLineThrough(const Text::LineThrough &lineThrough)
Sets the line-through style.
lineThrough The line-through configuration.
References Dali::Ui::Text::LineThrough::GetColor, Dali::Ui::ViewImpl::SetColorBinding.
void Dali::Ui::Integration::InputFieldImpl::ClearLineThrough()
Clears the line-through style.
References Dali::Ui::UiColorManager::ClearBinding, Dali::Ui::UiColorManager::Get.
void Dali::Ui::Integration::InputFieldImpl::SetFontSizeScale(float scale)
Sets the font size scale.
The scaled font size is calculated from the current font size multiplied by this scale value. scale The font size scale.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::InputFieldImpl::GetFontSizeScale() const
Gets the font size scale.
The font size scale.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetMinimumFontSizeScale(float scale)
Sets the minimum font size scale.
If this value is greater than the maximum font size scale, the adjusted font size scale follows this minimum value. scale The minimum font size scale.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::InputFieldImpl::GetMinimumFontSizeScale() const
Gets the minimum font size scale.
The minimum font size scale.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetMaximumFontSizeScale(float scale)
Sets the maximum font size scale.
If this value is less than the minimum font size scale, the adjusted font size scale follows the minimum font size scale. scale The maximum font size scale.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::InputFieldImpl::GetMaximumFontSizeScale() const
Gets the maximum font size scale.
The maximum font size scale.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetSystemFontSizeScaleEnabled(bool enabled)
Sets whether the system font size scale is applied.
When enabled, the system font size scale is used instead of the user-defined font size scale before applying the minimum and maximum constraints. enabled True to apply the system font size scale, false otherwise.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
bool Dali::Ui::Integration::InputFieldImpl::IsSystemFontSizeScaleEnabled() const
Gets whether the system font size scale is applied.
True if the system font size scale is applied, otherwise false.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTypingTextColor(const UiColor &color)
Sets the text color used for typing.
If a text range is selected, the color is applied to the selected text. If the selection is collapsed, the color is applied to text inserted after the current cursor position. color The typing text color. This input field.
References Dali::Ui::ViewImpl::SetColorBinding.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::InputFieldImpl::GetTypingTextColor() const
Gets the text color used for typing.
The typing text color.
References Dali::Ui::UiColorManager::Get.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTypingFontFamily(const Dali::String &fontFamily)
Sets the font family used for typing.
If a text range is selected, the font family is applied to the selected text. If the selection is collapsed, the font family is applied to text inserted after the current cursor position. fontFamily The typing font family. This input field.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::InputFieldImpl::GetTypingFontFamily() const
Gets the font family used for typing.
The typing font family.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTypingFontSize(float fontSize)
Sets the font size in pixels used for typing.
If a text range is selected, the font size is applied to the selected text. If the selection is collapsed, the font size is applied to text inserted after the current cursor position. fontSize The typing font size in pixels. This input field.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::InputFieldImpl::GetTypingFontSize() const
Gets the font size in pixels used for typing.
The typing font size in pixels.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTypingFontWeight(Text::FontWeight weight)
Sets the font weight used for typing.
If a text range is selected, the font weight is applied to the selected text. If the selection is collapsed, the font weight is applied to text inserted after the current cursor position. weight The typing font weight. This input field.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::FontWeight Dali::Ui::Integration::InputFieldImpl::GetTypingFontWeight() const
Gets the font weight used for typing.
The typing font weight.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTypingFontWidth(Text::FontWidth width)
Sets the font width used for typing.
If a text range is selected, the font width is applied to the selected text. If the selection is collapsed, the font width is applied to text inserted after the current cursor position. width The typing font width. This input field.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::FontWidth Dali::Ui::Integration::InputFieldImpl::GetTypingFontWidth() const
Gets the font width used for typing.
The typing font width.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTypingFontSlant(Text::FontSlant slant)
Sets the font slant used for typing.
If a text range is selected, the font slant is applied to the selected text. If the selection is collapsed, the font slant is applied to text inserted after the current cursor position. slant The typing font slant. This input field.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
Text::FontSlant Dali::Ui::Integration::InputFieldImpl::GetTypingFontSlant() const
Gets the font slant used for typing.
The typing font slant.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetFontVariation(const Dali::Vector< Text::FontVariationAxis > &axes)
Dali::Ui::InputField::SetFontVariation
Referenced by SetFontVariation.
void Dali::Ui::Integration::InputFieldImpl::SetFontVariation(const Dali::String &settings)
Dali::Ui::InputField::SetFontVariation(const Dali::String&)
References Dali::Ui::Text::FontVariation::FromString, SetFontVariation.
Dali::Vector< Text::FontVariationAxis > Dali::Ui::Integration::InputFieldImpl::GetFontVariation() const
Returns the font variation axes.
The font variation axes.
void Dali::Ui::Integration::InputFieldImpl::ClearFontVariation()
Clears the font variation.
This removes all previously set font variation axes.
void Dali::Ui::Integration::InputFieldImpl::SetLetterSpacing(float spacing)
Sets the additional spacing between letters in pixels.
Positive values increase the spacing, while negative values reduce it. spacing The additional letter spacing in pixels.
References spacing.
float Dali::Ui::Integration::InputFieldImpl::GetLetterSpacing() const
Gets the additional spacing between letters in pixels.
The additional letter spacing in pixels.
float Dali::Ui::Integration::InputFieldImpl::GetAdjustedFontSizeScale() const
Gets the adjusted font size scale used for rendering.
The adjusted font size scale is resolved after applying the current minimum and maximum font size scale constraints and, if enabled, the system font size scale. If the minimum font size scale is greater than the maximum font size scale, the minimum font size scale takes precedence and is used as the adjusted scale. The adjusted font size scale used for rendering.
uint32_t Dali::Ui::Integration::InputFieldImpl::GetSelectedTextStart() const
Gets the start index of the currently selected text.
The start index of the selected text.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
uint32_t Dali::Ui::Integration::InputFieldImpl::GetSelectedTextEnd() const
Gets the end index of the currently selected text.
The end index of the selected text.
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
Signal< void(View)> & Dali::Ui::Integration::InputFieldImpl::TextChangedSignal()
This signal is emitted when the text content changes.
voidOnTextChanged(Viewview); The signal to connect to.
Signal< void(View)> & Dali::Ui::Integration::InputFieldImpl::MaximumLengthReachedSignal()
This signal is emitted when the text input reaches the maximum allowed length.
The signal is triggered when an attempt is made to insert additional characters beyond the configured maximum length. voidOnMaximumLengthReached(Viewview); The signal to connect to.
Signal< void(View, Text::InputFilter::RejectReason)> & Dali::Ui::Integration::InputFieldImpl::InputRejectedSignal()
This signal is emitted when input is rejected by the input filter.
The signal is triggered when an attempt is made to insert text that does not match the allow pattern, or matches the deny pattern. voidOnInputRejected(Viewview,Text::InputFilter::RejectReasonreason); The reason indicates whether the input did not match the allow pattern, or matched the deny pattern. The signal to connect to.
Signal< void(View, uint32_t)> & Dali::Ui::Integration::InputFieldImpl::CursorPositionChangedSignal()
This signal is emitted when the cursor position changes.
voidOnCursorPositionChanged(Viewview,uint32_tposition); view The view whose cursor position changed. position The current cursor position. The signal to connect to.
Signal< void(View)> & Dali::Ui::Integration::InputFieldImpl::SelectionStartedSignal()
This signal is emitted when text selection starts.
voidOnSelectionStarted(Viewview); The signal to connect to.
Signal< void(View, uint32_t, uint32_t)> & Dali::Ui::Integration::InputFieldImpl::SelectionChangedSignal()
This signal is emitted when the text selection changes.
voidOnSelectionChanged(Viewview,uint32_tstart,uint32_tend); view The view whose selection changed. start The current selection start index. end The current selection end index. The signal to connect to.
Signal< void(View)> & Dali::Ui::Integration::InputFieldImpl::SelectionClearedSignal()
This signal is emitted when the text selection is cleared.
voidOnSelectionCleared(Viewview); The signal to connect to.
Signal< void(View, Text::TypingStyle::Mask)> & Dali::Ui::Integration::InputFieldImpl::TypingStyleChangedSignal()
This signal is emitted when the current typing style changes.
The signal is emitted when the typing style attributes resolved at the current cursor position or selected text range change, for example after cursor movement or selection changes. The mask indicates which typing style attributes changed. This signal is intended to notify changes detected from the current cursor position or selection, not to mirror every SetTyping*() API call. voidOnTypingStyleChanged(Viewview,Text::TypingStyle::Maskmask); The signal to connect to.
void Dali::Ui::Integration::InputFieldImpl::ApplyInitialConfig()
Applies default values from UiConfigManager if initialized.
References Dali::Ui::Integration::UiConfigManager::Get, SetFontSize, SetPlaceholderColor, SetShowPlaceholderOnFocus, SetTextColor.
Referenced by OnInitialize.
bool Dali::Ui::Integration::InputFieldImpl::SetTextUiScale(float scale)
Sets the UI scale used for text-specific metrics.
This scale is used for text-specific size calculation, such as font size. scale The text UI scale. True if the scale was changed, false otherwise.
Referenced by OnMeasure.
float Dali::Ui::Integration::InputFieldImpl::GetTextUiScale() const
Gets the UI scale used for text-specific metrics.
The text UI scale.
Referenced by GetEffectiveTextPadding.
Extents Dali::Ui::Integration::InputFieldImpl::GetEffectiveTextPadding() const
Gets the effective padding used for text layout.
The view padding is adjusted by the current text UI scale. The effective text padding.
References Dali::Ui::ViewImpl::GetPadding, GetTextUiScale.
Referenced by GetHeightForWidth, GetNaturalSize, OnMeasure, OnRelayout.
void Dali::Ui::Integration::InputFieldImpl::OnInitialize() override
Called after the actor has been initialized.
References ApplyInitialConfig, Dali::Ui::View::DownCast, Dali::Ui::GetImpl, Dali::Ui::ViewImpl::OnInitialize.
void Dali::Ui::Integration::InputFieldImpl::OnRelayout(const Vector2 &size, RelayoutContainer &container) override
References GetEffectiveTextPadding.
Vector3 Dali::Ui::Integration::InputFieldImpl::GetNaturalSize() override
References GetEffectiveTextPadding.
Referenced by OnMeasure.
float Dali::Ui::Integration::InputFieldImpl::GetHeightForWidth(float width) override
References GetEffectiveTextPadding.
void Dali::Ui::Integration::InputFieldImpl::RequestTextRelayout() override
Referenced by SetCursorBlinkEnabled, SetCursorHandleImage, SetCursorHandlePressedImage, SetLayoutDirectionMode, SetSelectionHandleImageLeft, SetSelectionHandleImageRight, SetSelectionHandlePressedImageLeft, SetSelectionHandlePressedImageRight, SetTextHandleEnabled.
void Dali::Ui::Integration::InputFieldImpl::InvalidateTextMeasure() override
References Dali::Ui::ViewImpl::GetRequestedHeight, Dali::Ui::ViewImpl::GetRequestedWidth, Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::WRAP_CONTENT.
void Dali::Ui::Integration::InputFieldImpl::RequestAsyncRender() override
void Dali::Ui::Integration::InputFieldImpl::AddDecoration(Actor &actor, Ui::Text::DecorationType type, bool needsClipping) override
void Dali::Ui::Integration::InputFieldImpl::GetControlBackgroundColor(Vector4 &color) const override
References Dali::Ui::View::Property::BACKGROUND, Dali::Ui::Visual::Property::MIX_COLOR.
bool Dali::Ui::Integration::InputFieldImpl::IsEditable() const override
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetEditable(bool editable) override
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::SetProperty.
std::string Dali::Ui::Integration::InputFieldImpl::CopyText() override
std::string Dali::Ui::Integration::InputFieldImpl::CutText() override
void Dali::Ui::Integration::InputFieldImpl::PasteText() override
void Dali::Ui::Integration::InputFieldImpl::TextChanged(bool immediate) override
void Dali::Ui::Integration::InputFieldImpl::MaximumLengthReached() override
void Dali::Ui::Integration::InputFieldImpl::InputRejected(Text::InputFilter::RejectReason reason) override
void Dali::Ui::Integration::InputFieldImpl::CursorPositionChanged(unsigned int oldPosition, unsigned int newPosition) override
void Dali::Ui::Integration::InputFieldImpl::InputStyleChanged(Text::InputStyle::Mask inputStyleMask) override
References Dali::Ui::Text::TypingStyle::NONE.
void Dali::Ui::Integration::InputFieldImpl::TextInserted(unsigned int position, unsigned int length, const std::string &content) override
void Dali::Ui::Integration::InputFieldImpl::TextDeleted(unsigned int position, unsigned int length, const std::string &content) override
void Dali::Ui::Integration::InputFieldImpl::SelectText(const uint32_t start, const uint32_t end) override
void Dali::Ui::Integration::InputFieldImpl::SelectWholeText() override
void Dali::Ui::Integration::InputFieldImpl::ClearSelection() override
Dali::String Dali::Ui::Integration::InputFieldImpl::GetSelectedText() const override
Referenced by Dali::Ui::Integration::InputFieldImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::InputFieldImpl::SetTextSelectionRange(const uint32_t *start, const uint32_t *end) override
Uint32Pair Dali::Ui::Integration::InputFieldImpl::GetTextSelectionRange() const override
void Dali::Ui::Integration::InputFieldImpl::SelectionChanged(uint32_t oldStart, uint32_t oldEnd, uint32_t newStart, uint32_t newEnd) override
bool Dali::Ui::Integration::InputFieldImpl::AnchorClicked(uint32_t cursorPosition, std::string &href) override
void Dali::Ui::Integration::InputFieldImpl::EmitAnchorClicked(const std::string &href) override
void Dali::Ui::Integration::InputFieldImpl::OnPropertySet(Dali::Property::Index index, const Dali::Property::Value &propertyValue) override
References Dali::Ui::ViewImpl::OnPropertySet.
void Dali::Ui::Integration::InputFieldImpl::OnFocusChanged(bool focused) override
Called when the view's focus state changes. Override to add custom focus handling. Call the base class at the end of the override to preserve default state management.
focused True if the view gained focus, false if lost
void Dali::Ui::Integration::InputFieldImpl::OnSceneConnection(int depth) override
bool Dali::Ui::Integration::InputFieldImpl::OnKeyEvent(const KeyEvent &event) override
Called when a key event is received.
event The key event True if the event is consumed
void Dali::Ui::Integration::InputFieldImpl::OnFocusGained()
Handles focus gain (IME activation, controller notification).
void Dali::Ui::Integration::InputFieldImpl::OnFocusLost()
Handles focus loss (IME deactivation, controller notification).
InputMethodContext::CallbackData Dali::Ui::Integration::InputFieldImpl::OnInputMethodContextEvent(InputMethodContext inputMethodContext, const InputMethodContext::EventData &inputMethodContextEvent)
void Dali::Ui::Integration::InputFieldImpl::OnSceneConnect(Dali::Actor actor)
Connection needed to re-render text, when a Input Field returns to the scene.
void Dali::Ui::Integration::InputFieldImpl::OnTapDetected(Actor actor, TapGesture tap)
Callback when a tap gesture is detected.
void Dali::Ui::Integration::InputFieldImpl::OnPanDetected(Actor actor, PanGesture pan)
Callback when a pan gesture is detected.
void Dali::Ui::Integration::InputFieldImpl::OnLongPressDetected(Actor actor, LongPressGesture longPress)
Callback when a long press gesture is detected.
bool Dali::Ui::Integration::InputFieldImpl::OnTouched(Actor actor, TouchEvent touch)
Callback when InputField is touched.
actor InputField touched touch Touch information
void Dali::Ui::Integration::InputFieldImpl::OnLayoutDirectionChanged(Actor actor, LayoutDirection::Type type)
Callback function for when the layout is changed.
actor The actor whose layoutDirection is changed. type The layoutDirection.
void Dali::Ui::Integration::InputFieldImpl::OnLocaleChanged(std::string locale)
Callback function for when the locale is changed.
locale The new system locale.
void Dali::Ui::Integration::InputFieldImpl::OnKeyboardStatusChanged(bool keyboardShown)
Callback when keyboard is shown/hidden.
keyboardShown True if keyboard is shown.
void Dali::Ui::Integration::InputFieldImpl::EnableClipping()
Enable or disable clipping.
void Dali::Ui::Integration::InputFieldImpl::ResizeActor(Actor &actor, const Vector2 &size)
Resize actor to the given size.
actor The actor to be resized. size Size to change.
void Dali::Ui::Integration::InputFieldImpl::AddLayer(Actor &layer, Actor &actor)
Add a layer for active or cursor.
layer The actor in which to store the layer. actor The new layer to add.
void Dali::Ui::Integration::InputFieldImpl::RenderText(Text::Controller::UpdateTextType updateTextType)
Render view, create and attach actor(s) to this Input Field.
void Dali::Ui::Integration::InputFieldImpl::EmitTextChanged()
Emits TextChanged signal.
void Dali::Ui::Integration::InputFieldImpl::EmitMaximumLengthReached()
Emits MaximumLengthReached signal.
void Dali::Ui::Integration::InputFieldImpl::EmitInputRejected(Text::InputFilter::RejectReason reason)
Emits InputRejected signal.
void Dali::Ui::Integration::InputFieldImpl::EmitCursorPositionChanged()
Emits CursorPositionChanged signal.
void Dali::Ui::Integration::InputFieldImpl::EmitSelectionStarted()
Emits SelectionStarted signal.
void Dali::Ui::Integration::InputFieldImpl::EmitSelectionChanged()
Emits SelectionChanged signal.
void Dali::Ui::Integration::InputFieldImpl::EmitSelectionCleared()
Emits SelectionCleared signal.
void Dali::Ui::Integration::InputFieldImpl::EmitTypingStyleChanged(Text::TypingStyle::Mask mask)
Emits TypingStyleChanged signal.
void Dali::Ui::Integration::InputFieldImpl::SetTextColorInternal(const Vector4 &color)
void Dali::Ui::Integration::InputFieldImpl::SetPlaceholderColorInternal(const Vector4 &color)
void Dali::Ui::Integration::InputFieldImpl::SetCursorColorInternal(const Vector4 &color)
void Dali::Ui::Integration::InputFieldImpl::SetSelectionColorInternal(const Vector4 &color)
void Dali::Ui::Integration::InputFieldImpl::SetTextHandleColorInternal(const Vector4 &color)
void Dali::Ui::Integration::InputFieldImpl::SetTextBackgroundColorInternal(const Vector4 &color)
void Dali::Ui::Integration::InputFieldImpl::SetUnderlineColorInternal(const Vector4 &color)
void Dali::Ui::Integration::InputFieldImpl::SetShadowColorInternal(const Vector4 &color)
void Dali::Ui::Integration::InputFieldImpl::SetOutlineColorInternal(const Vector4 &color)
void Dali::Ui::Integration::InputFieldImpl::SetLineThroughColorInternal(const Vector4 &color)
void Dali::Ui::Integration::InputFieldImpl::SetTypingTextColorInternal(const Vector4 &color)
Dali::Ui::Integration::InputFieldImpl::InputFieldImpl(const InputFieldImpl &)=delete
Dali::Ui::Integration::InputFieldImpl::InputFieldImpl(InputFieldImpl &&)=delete
InputFieldImpl & Dali::Ui::Integration::InputFieldImpl::operator=(const InputFieldImpl &)=delete
InputFieldImpl & Dali::Ui::Integration::InputFieldImpl::operator=(InputFieldImpl &&)=delete