Dali::Ui::Integration::TextVisualizerImpl
Dali::String Dali::Ui::Integration::TextVisualizerImpl::mText
Dali::String Dali::Ui::Integration::TextVisualizerImpl::mFontFamily
float Dali::Ui::Integration::TextVisualizerImpl::mFontSize
float Dali::Ui::Integration::TextVisualizerImpl::mLineHeight
UiColor Dali::Ui::Integration::TextVisualizerImpl::mTextColor
Dali::Vector<Bounds> Dali::Ui::Integration::TextVisualizerImpl::mExclusionRegions
Internal::TextVisualizer::ExclusionLayoutCache Dali::Ui::Integration::TextVisualizerImpl::mExclusionLayoutCache
Internal::TextVisualizer::PreparedText Dali::Ui::Integration::TextVisualizerImpl::mPreparedText
Internal::TextVisualizer::LayoutResult Dali::Ui::Integration::TextVisualizerImpl::mLayoutResult
Internal::TextVisualizer::LayoutResult Dali::Ui::Integration::TextVisualizerImpl::mMeasuredLayoutCache
Internal::TextVisualizer::AtlasViewAdapter Dali::Ui::Integration::TextVisualizerImpl::mAtlasViewAdapter
Internal::TextVisualizer::AtlasRendererBridge Dali::Ui::Integration::TextVisualizerImpl::mAtlasRendererBridge
Actor Dali::Ui::Integration::TextVisualizerImpl::mRenderHost
Vector2 Dali::Ui::Integration::TextVisualizerImpl::mLastLayoutSize
float Dali::Ui::Integration::TextVisualizerImpl::mMeasuredLayoutWidth
uint64_t Dali::Ui::Integration::TextVisualizerImpl::mLastRenderedLayoutSignature
bool Dali::Ui::Integration::TextVisualizerImpl::mPrepareDirty
bool Dali::Ui::Integration::TextVisualizerImpl::mLayoutDirty
bool Dali::Ui::Integration::TextVisualizerImpl::mRenderDirty
bool Dali::Ui::Integration::TextVisualizerImpl::mForceRenderDirty
bool Dali::Ui::Integration::TextVisualizerImpl::mHasLastRenderedLayoutSignature
bool Dali::Ui::Integration::TextVisualizerImpl::mHasMeasuredLayoutCache
bool Dali::Ui::Integration::TextVisualizerImpl::mRenderDiagnosticsLogged
TextVisualizerImplPtr Dali::Ui::Integration::TextVisualizerImpl::New()
Creates a new TextVisualizer.
References TextVisualizerImpl.
Referenced by Dali::Ui::TextVisualizer::New.
void Dali::Ui::Integration::TextVisualizerImpl::SetProperty(BaseObject *object, Dali::Property::Index index, const Dali::Property::Value &value)
References Dali::Ui::View::DownCast, Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::SetProperty.
Dali::Property::Value Dali::Ui::Integration::TextVisualizerImpl::GetProperty(BaseObject *object, Dali::Property::Index index)
References Dali::Ui::View::DownCast, Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::GetProperty.
Dali::Ui::Integration::TextVisualizerImpl::~TextVisualizerImpl()
A reference counted object may only be deleted by calling Unreference()
Dali::Ui::Integration::TextVisualizerImpl::TextVisualizerImpl()
TextVisualizerImpl constructor.
Referenced by New.
void Dali::Ui::Integration::TextVisualizerImpl::SetText(const Dali::String &text)
Sets the text.
text The text to display in UTF-8 format.
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::TextVisualizerImpl::GetText() const
Gets the text.
The text currently set on the text visualizer in UTF-8 format.
Referenced by Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::TextVisualizerImpl::SetFontFamily(const Dali::String &fontFamily)
Sets the font family of the text.
fontFamily The requested font family to use.
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::SetProperty.
Dali::String Dali::Ui::Integration::TextVisualizerImpl::GetFontFamily() const
Gets the font family of the text.
The font family currently set on the text visualizer.
Referenced by Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::TextVisualizerImpl::SetFontSize(float fontSize)
Sets the font size of the text.
fontSize The font pixel size.
References Dali::Ui::ViewImpl::InvalidateMeasure.
Referenced by Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::TextVisualizerImpl::GetFontSize() const
Gets the font size of the text.
The font pixel size currently set on the text visualizer.
Referenced by Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::TextVisualizerImpl::SetLineHeight(float lineHeight)
Sets the relative line height multiplier.
If the line height is positive, it is calculated as a multiplier of the font pixel size: CalculatedLineHeight(px) = FontSize(px) * lineHeight If the line height is -1.0f, natural line height is used. Only relative line height is supported by TextVisualizer in this revision. lineHeight The relative line height multiplier, or -1.0f for automatic line height.
References Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::Text::LINE_HEIGHT_AUTO.
Referenced by ClearLineHeight, Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::SetProperty.
float Dali::Ui::Integration::TextVisualizerImpl::GetLineHeight() const
Gets the current line height multiplier.
The relative line height multiplier, or -1.0f when natural line height is used.
Referenced by Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::TextVisualizerImpl::ClearLineHeight()
Clears the line height override and restores natural line height.
References Dali::Ui::Text::LINE_HEIGHT_AUTO, SetLineHeight.
void Dali::Ui::Integration::TextVisualizerImpl::SetTextColor(const UiColor &color)
Sets the color of the text.
color The required text color value.
References Dali::Ui::UiColor::GetColorId, Dali::Ui::UiColor::GetRgba.
Referenced by Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::SetProperty.
UiColor Dali::Ui::Integration::TextVisualizerImpl::GetTextColor()
Gets the color of the text.
The text color currently set on the text visualizer.
Referenced by Dali::Ui::Integration::TextVisualizerImpl::PropertyHandler::GetProperty.
void Dali::Ui::Integration::TextVisualizerImpl::Prepare()
Prepares the current text state for layout.
This is an eager command. In this commit it only updates internal dirty state.
Referenced by OnMeasure, OnRelayout.
void Dali::Ui::Integration::TextVisualizerImpl::SetExclusionRegions(const Dali::Vector< Bounds > &regions)
Sets the exclusion regions used by the future layout pass.
regions Regions where text should not be placed.
References Dali::Ui::ViewImpl::InvalidateMeasure.
Dali::Vector< Bounds > Dali::Ui::Integration::TextVisualizerImpl::GetExclusionRegions() const
Gets the currently stored exclusion regions.
The current exclusion regions.
void Dali::Ui::Integration::TextVisualizerImpl::ClearExclusionRegions()
Clears all exclusion regions.
References Dali::Ui::ViewImpl::InvalidateMeasure.
void Dali::Ui::Integration::TextVisualizerImpl::OnInitialize() override
Called after the actor has been initialized.
References Dali::Ui::ViewImpl::OnInitialize.
void Dali::Ui::Integration::TextVisualizerImpl::OnRelayout(const Vector2 &size, RelayoutContainer &container) override
References Prepare.
MeasuredSize Dali::Ui::Integration::TextVisualizerImpl::OnMeasure(float widthConstraint, float heightConstraint) override
Called during measure pass. Override to implement custom measurement.
widthConstraint Available visual (scale-applied) width, or WRAP_CONTENT / MATCH_PARENT. heightConstraint Available visual (scale-applied) height, or WRAP_CONTENT / MATCH_PARENT. Measured visual (scale-applied) size.
References Dali::Ui::ViewImpl::GetEffectiveScale, Dali::Ui::ViewImpl::GetMaximumHeight, Dali::Ui::ViewImpl::GetMaximumWidth, Dali::Ui::ViewImpl::GetMinimumHeight, Dali::Ui::ViewImpl::GetMinimumWidth, Dali::Ui::ViewImpl::GetRequestedHeight, Dali::Ui::ViewImpl::GetRequestedWidth, Dali::Ui::MATCH_PARENT, Prepare.
void Dali::Ui::Integration::TextVisualizerImpl::OnPropertySet(Dali::Property::Index index, const Dali::Property::Value &propertyValue) override
References Dali::Ui::Text::TextVisualizerPropertyIndex::FONT_FAMILY, Dali::Ui::Text::TextVisualizerPropertyIndex::FONT_SIZE, Dali::Ui::Text::TextVisualizerPropertyIndex::LINE_HEIGHT, Dali::Ui::ViewImpl::OnPropertySet, Dali::Ui::Text::TextVisualizerPropertyIndex::TEXT, Dali::Ui::Text::TextVisualizerPropertyIndex::TEXT_COLOR.
Dali::Ui::Integration::TextVisualizerImpl::TextVisualizerImpl(const TextVisualizerImpl &)=delete
Dali::Ui::Integration::TextVisualizerImpl::TextVisualizerImpl(TextVisualizerImpl &&)=delete
TextVisualizerImpl & Dali::Ui::Integration::TextVisualizerImpl::operator=(const TextVisualizerImpl &)=delete
TextVisualizerImpl & Dali::Ui::Integration::TextVisualizerImpl::operator=(TextVisualizerImpl &&)=delete
void Dali::Ui::Integration::TextVisualizerImpl::MarkPrepareDirty()
void Dali::Ui::Integration::TextVisualizerImpl::MarkLayoutDirty()
void Dali::Ui::Integration::TextVisualizerImpl::MarkRenderDirty()
void Dali::Ui::Integration::TextVisualizerImpl::MarkPlacementRenderDirty()
void Dali::Ui::Integration::TextVisualizerImpl::ClearPrepareDirty()
void Dali::Ui::Integration::TextVisualizerImpl::ClearLayoutDirty()
void Dali::Ui::Integration::TextVisualizerImpl::ClearRenderDirty()
void Dali::Ui::Integration::TextVisualizerImpl::EnsureRenderHost()
void Dali::Ui::Integration::TextVisualizerImpl::SyncRenderHostSize(const Vector2 &size)
void Dali::Ui::Integration::TextVisualizerImpl::ClearRenderHost()
void Dali::Ui::Integration::TextVisualizerImpl::LogRenderDiagnostics(const Vector2 &size, bool updateRenderDataResult, bool attachResult) const
float Dali::Ui::Integration::TextVisualizerImpl::CalculateEffectiveLineHeight() const
bool Dali::Ui::Integration::TextVisualizerImpl::HasRenderHost() const
bool Dali::Ui::Integration::TextVisualizerImpl::CanSkipRenderForUnchangedLayout(uint64_t layoutSignature) const
bool Dali::Ui::Integration::TextVisualizerImpl::IsRenderUpdateSuccessful(bool updateRenderDataResult, bool attachResult) const
void Dali::Ui::Integration::TextVisualizerImpl::ResetLastRenderedLayoutSignature()
void Dali::Ui::Integration::TextVisualizerImpl::StoreLastRenderedLayoutSignature(uint64_t layoutSignature)
void Dali::Ui::Integration::TextVisualizerImpl::UpdateStoredExclusionRegions(const Dali::Vector< Bounds > &regions)
bool Dali::Ui::Integration::TextVisualizerImpl::AreExclusionRegionsEqual(const Dali::Vector< Bounds > &regions) const
void Dali::Ui::Integration::TextVisualizerImpl::ClearMeasuredLayoutCache()
void Dali::Ui::Integration::TextVisualizerImpl::StoreMeasuredLayoutCache(float layoutWidth, const Internal::TextVisualizer::LayoutResult &result)
bool Dali::Ui::Integration::TextVisualizerImpl::TryUseMeasuredLayoutCache(float layoutWidth, Internal::TextVisualizer::LayoutResult &result)
float Dali::Ui::Integration::TextVisualizerImpl::GetNaturalTextWidth() const
float Dali::Ui::Integration::TextVisualizerImpl::MeasureNaturalTextHeightForWidth(float layoutWidth)
void Dali::Ui::Integration::TextVisualizerImpl::UpdateLayout(float layoutWidth, Internal::TextVisualizer::LayoutResult &result)
void Dali::Ui::Integration::TextVisualizerImpl::SyncRenderStateToAdapter(const Vector2 &controlSize)