Dali::Ui::Integration::ScrollBarImpl
View Dali::Ui::Integration::ScrollBarImpl::mVerticalBar
The vertical bar view.
View Dali::Ui::Integration::ScrollBarImpl::mHorizontalBar
The horizontal bar view.
float Dali::Ui::Integration::ScrollBarImpl::mBarThickness
The thickness of the scroll bar.
Vector4 Dali::Ui::Integration::ScrollBarImpl::mBarColor
The color of the scroll bar.
float Dali::Ui::Integration::ScrollBarImpl::mBarMinSize
The minimum size of the scroll bar.
Vector2 Dali::Ui::Integration::ScrollBarImpl::mScrollPosition
The current scroll position.
float Dali::Ui::Integration::ScrollBarImpl::mBarOffset
The offset of bars from the edges (padding is inherited from View)
Vector4 Dali::Ui::Integration::ScrollBarImpl::mBarCornerRadius
The corner radius for each corner (topLeft, topRight, bottomRight, bottomLeft)
ScrollBarVisibility Dali::Ui::Integration::ScrollBarImpl::mVerticalVisibility
Vertical scroll bar visibility.
ScrollBarVisibility Dali::Ui::Integration::ScrollBarImpl::mHorizontalVisibility
Horizontal scroll bar visibility.
float Dali::Ui::Integration::ScrollBarImpl::mScrollableWidth
Scrollable content width.
float Dali::Ui::Integration::ScrollBarImpl::mScrollableHeight
Scrollable content height.
float Dali::Ui::Integration::ScrollBarImpl::mViewPortWidth
Viewport width.
float Dali::Ui::Integration::ScrollBarImpl::mViewPortHeight
Viewport height.
LayoutRect Dali::Ui::Integration::ScrollBarImpl::mLastVBarBounds
Last vertical bar bounds (for change detection)
LayoutRect Dali::Ui::Integration::ScrollBarImpl::mLastHBarBounds
Last horizontal bar bounds (for change detection)
Animation Dali::Ui::Integration::ScrollBarImpl::mFadeInAnimation
Fade in animation.
Animation Dali::Ui::Integration::ScrollBarImpl::mFadeOutAnimation
Fade out animation.
bool Dali::Ui::Integration::ScrollBarImpl::mIsBarVisible
True once bars are fully opaque (fade-in complete)
Timer Dali::Ui::Integration::ScrollBarImpl::mHideTimer
Fires 2 seconds after the last ShowBar call to trigger fade-out.
ScrollBarImplPtr Dali::Ui::Integration::ScrollBarImpl::New()
Creates a new ScrollBar.
References ScrollBarImpl.
Referenced by Dali::Ui::ScrollBar::New.
Dali::Ui::Integration::ScrollBarImpl::~ScrollBarImpl()
Destructor.
Dali::Ui::Integration::ScrollBarImpl::ScrollBarImpl()
ScrollBar constructor.
Referenced by New.
void Dali::Ui::Integration::ScrollBarImpl::UpdateBarSize()
Updates the bar size.
References CreateHBar, CreateVBar, RemoveHBar, RemoveVBar, UpdateHBarSize, UpdateVBarSize.
Referenced by SetBarOffset, SetHorizontalScrollBarVisibility, SetVerticalScrollBarVisibility, UpdateBarSize.
void Dali::Ui::Integration::ScrollBarImpl::ShowBar()
Shows the bar.
References Dali::Ui::Auto, OnHideTimerFired, PlayFadeIn.
Referenced by SetHorizontalScrollBarVisibility, SetVerticalScrollBarVisibility, UpdatePosition.
void Dali::Ui::Integration::ScrollBarImpl::PlayFadeIn()
Plays fade in animation.
References OnFadeInFinished.
Referenced by ShowBar.
void Dali::Ui::Integration::ScrollBarImpl::OnFadeInFinished(Animation animation)
Called when fade in animation finishes.
Referenced by PlayFadeIn.
bool Dali::Ui::Integration::ScrollBarImpl::OnHideTimerFired()
Called when the auto-hide timer fires (2-second delay after last ShowBar).
References PlayFadeOut.
Referenced by ShowBar.
void Dali::Ui::Integration::ScrollBarImpl::PlayFadeOut()
Plays fade out animation.
References Dali::Ui::Auto.
Referenced by HideBar, OnHideTimerFired.
void Dali::Ui::Integration::ScrollBarImpl::UpdatePosition(const Vector2 &position)
Updates the position.
References Dali::Ui::ViewImpl::GetPadding, Dali::Ui::LayoutRect::height, SetHBarBounds, SetVBarBounds, ShowBar, Dali::Ui::LayoutRect::width.
Referenced by SetBarOffset, SetScrollPosition.
void Dali::Ui::Integration::ScrollBarImpl::RemoveVBar()
Removes vertical bar.
Referenced by SetVerticalScrollBarVisibility, UpdateBarSize.
void Dali::Ui::Integration::ScrollBarImpl::CreateVBar()
Creates vertical bar.
References Dali::Ui::ViewImpl::GetPadding, Dali::Ui::Never, Dali::Ui::AbsoluteLayoutParams::New, Dali::Ui::View::New, Dali::Ui::View::SetBackgroundColor, Dali::Ui::AbsoluteLayoutParams::SetBounds, Dali::Ui::View::SetCornerRadius, Dali::Ui::View::SetLayoutParams, Dali::Ui::View::SetOpacity.
Referenced by SetVerticalScrollBarVisibility, UpdateBarSize.
void Dali::Ui::Integration::ScrollBarImpl::UpdateVBarSize(float ratio)
Updates vertical bar size.
References GetBarMinSize, Dali::Ui::ViewImpl::GetPadding, SetVBarBounds.
Referenced by UpdateBarSize.
void Dali::Ui::Integration::ScrollBarImpl::RemoveHBar()
Removes horizontal bar.
Referenced by SetHorizontalScrollBarVisibility, UpdateBarSize.
void Dali::Ui::Integration::ScrollBarImpl::CreateHBar()
Creates horizontal bar.
References Dali::Ui::ViewImpl::GetPadding, Dali::Ui::Never, Dali::Ui::AbsoluteLayoutParams::New, Dali::Ui::View::New, Dali::Ui::View::SetBackgroundColor, Dali::Ui::AbsoluteLayoutParams::SetBounds, Dali::Ui::View::SetCornerRadius, Dali::Ui::View::SetLayoutParams, Dali::Ui::View::SetOpacity.
Referenced by SetHorizontalScrollBarVisibility, UpdateBarSize.
void Dali::Ui::Integration::ScrollBarImpl::UpdateHBarSize(float ratio)
Updates horizontal bar size.
References GetBarMinSize, Dali::Ui::ViewImpl::GetPadding, SetHBarBounds.
Referenced by UpdateBarSize.
void Dali::Ui::Integration::ScrollBarImpl::SetVBarBounds(float x, float y, float width, float height)
Sets vertical bar bounds with change detection.
References Dali::Ui::LayoutRect::height, Dali::Ui::AbsoluteLayoutParams::New, Dali::Ui::View::SetLayoutParams, Dali::Ui::LayoutRect::width, Dali::Ui::LayoutRect::x, Dali::Ui::LayoutRect::y.
Referenced by UpdatePosition, UpdateVBarSize.
void Dali::Ui::Integration::ScrollBarImpl::SetHBarBounds(float x, float y, float width, float height)
Sets horizontal bar bounds with change detection.
References Dali::Ui::LayoutRect::height, Dali::Ui::AbsoluteLayoutParams::New, Dali::Ui::View::SetLayoutParams, Dali::Ui::LayoutRect::width, Dali::Ui::LayoutRect::x, Dali::Ui::LayoutRect::y.
Referenced by UpdateHBarSize, UpdatePosition.
void Dali::Ui::Integration::ScrollBarImpl::ApplyCornerRadiusToBars()
Applies corner radius to vertical and horizontal bars.
References Dali::Ui::View::SetCornerRadius.
Referenced by SetBarCornerRadius, SetBarCornerRadius.
void Dali::Ui::Integration::ScrollBarImpl::OnInitialize() override
References Dali::Ui::MATCH_PARENT, Dali::Ui::Integration::AbsoluteLayoutImpl::OnInitialize, Dali::Ui::ViewImpl::SetLayoutMode, Dali::Ui::ViewImpl::SetRequestedHeight, Dali::Ui::ViewImpl::SetRequestedWidth, Dali::Ui::STANDALONE.
void Dali::Ui::Integration::ScrollBarImpl::Initialize()
Initializes the scroll bar.
References Dali::Ui::ViewImpl::Initialize.
View Dali::Ui::Integration::ScrollBarImpl::GetTarget() const
Gets the target view.
References Dali::Ui::View::DownCast.
ScrollBarVisibility Dali::Ui::Integration::ScrollBarImpl::GetVerticalScrollBarVisibility() const
Gets the vertical scroll bar visibility.
void Dali::Ui::Integration::ScrollBarImpl::SetVerticalScrollBarVisibility(ScrollBarVisibility visibility)
Sets the vertical scroll bar visibility.
References Dali::Ui::Always, CreateVBar, Dali::Ui::Never, RemoveVBar, ShowBar, UpdateBarSize.
ScrollBarVisibility Dali::Ui::Integration::ScrollBarImpl::GetHorizontalScrollBarVisibility() const
Gets the horizontal scroll bar visibility.
void Dali::Ui::Integration::ScrollBarImpl::SetHorizontalScrollBarVisibility(ScrollBarVisibility visibility)
Sets the horizontal scroll bar visibility.
References Dali::Ui::Always, CreateHBar, Dali::Ui::Never, RemoveHBar, ShowBar, UpdateBarSize.
void Dali::Ui::Integration::ScrollBarImpl::UpdateBarSize(float scrollWidth, float scrollHeight, float viewportWidth, float viewportHeight)
Updates the size of the scroll bar.
References UpdateBarSize.
void Dali::Ui::Integration::ScrollBarImpl::UpdateScrollPosition(const Vector2 &position)
Updates the scroll position.
References SetScrollPosition.
void Dali::Ui::Integration::ScrollBarImpl::HideBar()
Hides the scroll bar (fade out).
References PlayFadeOut.
float Dali::Ui::Integration::ScrollBarImpl::GetBarThickness() const
Gets the bar thickness.
void Dali::Ui::Integration::ScrollBarImpl::SetBarThickness(float thickness)
Sets the bar thickness.
Vector4 Dali::Ui::Integration::ScrollBarImpl::GetBarColor() const
Gets the bar color.
void Dali::Ui::Integration::ScrollBarImpl::SetBarColor(const Vector4 &color)
Sets the bar color.
References Dali::Ui::View::SetBackgroundColor.
float Dali::Ui::Integration::ScrollBarImpl::GetBarMinSize() const
Gets the bar minimum size.
Referenced by UpdateHBarSize, UpdateVBarSize.
void Dali::Ui::Integration::ScrollBarImpl::SetBarMinSize(float minSize)
Sets the bar minimum size.
Vector2 Dali::Ui::Integration::ScrollBarImpl::GetScrollPosition() const
Gets the scroll position.
void Dali::Ui::Integration::ScrollBarImpl::SetScrollPosition(const Vector2 &position)
Sets the scroll position.
References UpdatePosition.
Referenced by UpdateScrollPosition.
float Dali::Ui::Integration::ScrollBarImpl::GetBarOffset() const
Gets the bar offset.
void Dali::Ui::Integration::ScrollBarImpl::SetBarOffset(float offset)
Sets the bar offset.
References UpdateBarSize, UpdatePosition.
Vector4 Dali::Ui::Integration::ScrollBarImpl::GetBarCornerRadius() const
Gets the bar corner radius.
void Dali::Ui::Integration::ScrollBarImpl::SetBarCornerRadius(float radius)
Sets the bar corner radius (same for all corners).
References ApplyCornerRadiusToBars.
void Dali::Ui::Integration::ScrollBarImpl::SetBarCornerRadius(const Vector4 &radius)
Sets the bar corner radius for each corner.
References ApplyCornerRadiusToBars.
Dali::Ui::Integration::ScrollBarImpl::ScrollBarImpl(const ScrollBarImpl &)=delete
Dali::Ui::Integration::ScrollBarImpl::ScrollBarImpl(ScrollBarImpl &&)=delete
ScrollBarImpl & Dali::Ui::Integration::ScrollBarImpl::operator=(const ScrollBarImpl &)=delete
ScrollBarImpl & Dali::Ui::Integration::ScrollBarImpl::operator=(ScrollBarImpl &&)=delete