Dali::Ui::VisualBase
View Dali::Ui::VisualBase::GetOwner() const
< Public API
Get attached view. Empty handle if this visual is not be attached. The attached view, or empty handle if not be attached.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetOwner.
Dali::Ui::Visual::ContainerRangeType Dali::Ui::VisualBase::GetContainerRangeType() const
Get the attached container range type. INVALID if this visual is not be attached.
The attached container range type, or INVALID if not be attached.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetInternalContainerRangeType, Dali::Ui::DevelVisual::INVALID, Dali::Ui::Visual::INVALID, Dali::Ui::Visual::MAX_COUNT.
void Dali::Ui::VisualBase::Detach()
Detach from the attached view.
References Dali::Ui::Internal::VisualBaseImpl::DetachFromContainer, Dali::Ui::GetImplementation.
void Dali::Ui::VisualBase::DoAction(Dali::Property::Index actionId, const Dali::Property::Value &attributes)
Perform an action on a visual registered to this view. Visuals will have actions, this API is used to perform one of these actions with the given attributes.
If visual is not been registered to the view, action should be ignored. actionId The action to perform. See Visual to find supported actions. attributes Optional attributes for the action.
References Dali::Ui::Internal::VisualBaseImpl::DoAction, Dali::Ui::GetImplementation.
Referenced by Dali::Ui::AnimatedImageVisual::JumpTo, Dali::Ui::LottieAnimationVisual::JumpTo, Dali::Ui::AnimatedImageVisual::Pause, Dali::Ui::LottieAnimationVisual::Pause, Dali::Ui::AnimatedImageVisual::Play, Dali::Ui::LottieAnimationVisual::Play, Dali::Ui::AnimatedImageVisual::Stop, Dali::Ui::LottieAnimationVisual::Stop.
Dali::Ui::Visual::Type Dali::Ui::VisualBase::GetVisualType() const
Get the type of this VisualBase.
The type of this VisualBase
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetVisualType.
Dali::Property::Value Dali::Ui::VisualBase::GetProperty(Dali::Property::Index index) const
Retrieves a property value.
BaseHandle is not subclass of Handle. So this API is not use Handle.SetProperty index The index of the property The property value This returns the value set by SetProperty() or the animation target value if it is being animated.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetProperty.
Referenced by Dali::Ui::AnimatedImageVisual::GetPlayRange, Dali::Ui::LottieAnimationVisual::GetPlayRange, Dali::Ui::AnimatedImageVisual::GetResourceUrl, Dali::Ui::AnimatedImageVisual::GetResourceUrlList.
T Dali::Ui::VisualBase::GetProperty(Dali::Property::Index index) const
Convenience function for obtaining a property of a known type.
index The index of the property The property value The property types match i.e. PropertyTypes::Get<T>() is equal to GetPropertyType(index). GetProperty()
void Dali::Ui::VisualBase::SetProperty(Dali::Property::Index index, Dali::Property::Value propertyValue)
Sets the value of an existing property.
BaseHandle is not subclass of Handle. So this API is not use Handle.SetProperty index The index of the property propertyValue The new value of the property
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetProperty.
Referenced by Dali::Ui::AnimatedImageVisual::SetAlphaMaskUrl, Dali::Ui::ImageVisual::SetAlphaMaskUrl, Dali::Ui::AnimatedImageVisual::SetBatchSize, Dali::Ui::ColorVisual::SetBlurRadius, SetBorderlineOffset, SetBorderlineWidth, Dali::Ui::AnimatedImageVisual::SetCacheSize, SetCornerRadius, SetCornerRadius, SetCornerRadius, SetCornerRadiusPolicy, SetCornerRadiusPolicyRelative, SetCornerSquareness, SetCornerSquareness, SetCornerSquareness, Dali::Ui::AnimatedImageVisual::SetCropToMask, Dali::Ui::ImageVisual::SetCropToMask, Dali::Ui::ColorVisual::SetCutoutPolicy, Dali::Ui::AnimatedImageVisual::SetDesiredHeight, Dali::Ui::ImageVisual::SetDesiredHeight, Dali::Ui::LottieAnimationVisual::SetDesiredHeight, Dali::Ui::AnimatedImageVisual::SetDesiredWidth, Dali::Ui::ImageVisual::SetDesiredWidth, Dali::Ui::LottieAnimationVisual::SetDesiredWidth, Dali::Ui::LottieAnimationVisual::SetEnableAspectFit, Dali::Ui::AnimatedImageVisual::SetEnableBrokenImage, Dali::Ui::ImageVisual::SetEnableBrokenImage, Dali::Ui::LottieAnimationVisual::SetEnableBrokenImage, Dali::Ui::LottieAnimationVisual::SetEnableFrameCache, Dali::Ui::ImageVisual::SetFastTrackUploading, Dali::Ui::AnimatedImageVisual::SetFittingMode, Dali::Ui::ImageVisual::SetFittingMode, Dali::Ui::AnimatedImageVisual::SetFrameDelay, Dali::Ui::AnimatedImageVisual::SetFrameSpeedFactor, Dali::Ui::LottieAnimationVisual::SetFrameSpeedFactor, Dali::Ui::AnimatedImageVisual::SetLoadPolicy, Dali::Ui::ImageVisual::SetLoadPolicy, Dali::Ui::LottieAnimationVisual::SetLoadPolicy, Dali::Ui::AnimatedImageVisual::SetLoopCount, Dali::Ui::LottieAnimationVisual::SetLoopCount, Dali::Ui::LottieAnimationVisual::SetLoopingMode, Dali::Ui::AnimatedImageVisual::SetMaskContentScale, Dali::Ui::ImageVisual::SetMaskContentScale, Dali::Ui::AnimatedImageVisual::SetMaskingType, Dali::Ui::ImageVisual::SetMaskingType, Dali::Ui::LottieAnimationVisual::SetNotifyAfterRasterization, Dali::Ui::ImageVisual::SetNPatchAuxiliaryImage, Dali::Ui::ImageVisual::SetNPatchAuxiliaryImageAlpha, Dali::Ui::ImageVisual::SetNPatchBorder, Dali::Ui::ImageVisual::SetNPatchBorderOnly, Dali::Ui::AnimatedImageVisual::SetOrientationCorrection, Dali::Ui::ImageVisual::SetOrientationCorrection, Dali::Ui::LottieAnimationVisual::SetOrientationCorrection, Dali::Ui::AnimatedImageVisual::SetPixelArea, Dali::Ui::ImageVisual::SetPixelArea, Dali::Ui::LottieAnimationVisual::SetPixelArea, Dali::Ui::AnimatedImageVisual::SetPlayRange, Dali::Ui::LottieAnimationVisual::SetPlayRange, Dali::Ui::AnimatedImageVisual::SetPreMultipliedAlpha, Dali::Ui::ImageVisual::SetPreMultipliedAlpha, Dali::Ui::LottieAnimationVisual::SetRedrawInScalingDown, Dali::Ui::LottieAnimationVisual::SetRedrawInScalingUp, Dali::Ui::AnimatedImageVisual::SetReleasePolicy, Dali::Ui::ImageVisual::SetReleasePolicy, Dali::Ui::LottieAnimationVisual::SetReleasePolicy, Dali::Ui::LottieAnimationVisual::SetRenderScale, Dali::Ui::AnimatedImageVisual::SetResourceUrl, Dali::Ui::ImageVisual::SetResourceUrl, Dali::Ui::LottieAnimationVisual::SetResourceUrl, Dali::Ui::AnimatedImageVisual::SetSamplingMode, Dali::Ui::ImageVisual::SetSamplingMode, Dali::Ui::LottieAnimationVisual::SetSamplingMode, Dali::Ui::AnimatedImageVisual::SetStopBehavior, Dali::Ui::LottieAnimationVisual::SetStopBehavior, Dali::Ui::AnimatedImageVisual::SetSynchronousLoading, Dali::Ui::ImageVisual::SetSynchronousLoading, Dali::Ui::LottieAnimationVisual::SetSynchronousLoading, Dali::Ui::AnimatedImageVisual::SetSynchronousSizing, Dali::Ui::ImageVisual::SetSynchronousSizing, Dali::Ui::LottieAnimationVisual::SetSynchronousSizing, Dali::Ui::AnimatedImageVisual::SetWrapModeU, Dali::Ui::ImageVisual::SetWrapModeU, Dali::Ui::LottieAnimationVisual::SetWrapModeU, Dali::Ui::AnimatedImageVisual::SetWrapModeV, Dali::Ui::ImageVisual::SetWrapModeV, Dali::Ui::LottieAnimationVisual::SetWrapModeV.
const Dali::String & Dali::Ui::VisualBase::GetName() const
Gets the name of the VisualBase.
The name of the VisualBase
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetName.
VisualBase & Dali::Ui::VisualBase::SetName(const Dali::String &name)
Sets the name of this VisualBase.
name The name to set
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetName.
UiColor Dali::Ui::VisualBase::GetColor() const
Gets the color of the VisualBase.
The color of the VisualBase
References Dali::Ui::Internal::VisualBaseImpl::GetColor, Dali::Ui::GetImplementation.
VisualBase & Dali::Ui::VisualBase::SetColor(const UiColor &color)
Sets the color of this VisualBase.
color The UiColor to apply
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetColor.
float Dali::Ui::VisualBase::GetOffsetX() const
Gets the X offset of the VisualBase.
The X offset of the VisualBase
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetOffsetX.
VisualBase & Dali::Ui::VisualBase::SetOffsetX(float x)
Sets the X offset of the VisualBase.
x The X offset to set
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetOffsetX.
float Dali::Ui::VisualBase::GetOffsetY() const
Gets the Y offset of the VisualBase.
The Y offset of the VisualBase
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetOffsetY.
VisualBase & Dali::Ui::VisualBase::SetOffsetY(float y)
Sets the Y offset of the VisualBase.
y The Y offset to set
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetOffsetY.
float Dali::Ui::VisualBase::GetWidth() const
Gets the width of the VisualBase.
The width of the VisualBase
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetWidth.
VisualBase & Dali::Ui::VisualBase::SetWidth(float width)
Sets the width of the VisualBase.
width The width to set
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetWidth.
float Dali::Ui::VisualBase::GetHeight() const
Gets the height of the VisualBase.
The height of the VisualBase
References Dali::Ui::Internal::VisualBaseImpl::GetHeight, Dali::Ui::GetImplementation.
VisualBase & Dali::Ui::VisualBase::SetHeight(float height)
Sets the height of the VisualBase.
height The height to set
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetHeight.
Dali::Ui::Visual::Transform::ProportionFlags Dali::Ui::VisualBase::GetProportionFlags() const
Gets the proportion flags of the VisualBase.
The proportion flags of the VisualBase
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetProportionFlags.
VisualBase & Dali::Ui::VisualBase::SetProportionFlags(Dali::Ui::Visual::Transform::ProportionFlags flags)
Sets the proportion flags of the VisualBase.
flags The proportion flags to set
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetProportionFlags.
float Dali::Ui::VisualBase::GetExtraWidth() const
Gets the extra width of the VisualBase.
The extra width of the VisualBase
References Dali::Ui::Internal::VisualBaseImpl::GetExtraWidth, Dali::Ui::GetImplementation.
VisualBase & Dali::Ui::VisualBase::SetExtraWidth(float extraWidth)
Sets the extra width of the VisualBase. This width will be added to final width absolutly, independent as proportion flags.
extraWidth The extra width to set
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetExtraWidth.
float Dali::Ui::VisualBase::GetExtraHeight() const
Gets the extra height of the VisualBase.
The extra height of the VisualBase
References Dali::Ui::Internal::VisualBaseImpl::GetExtraHeight, Dali::Ui::GetImplementation.
VisualBase & Dali::Ui::VisualBase::SetExtraHeight(float extraHeight)
Sets the extra height of the VisualBase. This height will be added to final height absolutly, independent as proportion flags.
extraHeight The extra height to set
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetExtraHeight.
Align::Type Dali::Ui::VisualBase::GetOrigin() const
Gets the origin of the VisualBase.
The origin of the VisualBase
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetOrigin.
VisualBase & Dali::Ui::VisualBase::SetOrigin(Align::Type origin)
Sets the origin of the VisualBase.
origin The origin type to set
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetOrigin.
Align::Type Dali::Ui::VisualBase::GetPivot() const
Gets the pivot of the VisualBase.
The pivot of the VisualBase
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetPivot.
VisualBase & Dali::Ui::VisualBase::SetPivot(Align::Type pivot)
Sets the pivot of the VisualBase.
pivot The pivot to set
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetPivot.
Vector4 Dali::Ui::VisualBase::GetCornerRadius() const
Gets the corner radius of the VisualBase.
The corner radius as Vector4 (topLeft, topRight, bottomRight, bottomLeft)
References Dali::Ui::DevelVisual::Property::CORNER_RADIUS.
VisualBase & Dali::Ui::VisualBase::SetCornerRadius(float radius)
Sets a uniform corner radius for all four corners.
Only supported type of visual has efforts. radius The corner radius to apply to all corners
References Dali::Ui::DevelVisual::Property::CORNER_RADIUS, SetProperty.
VisualBase & Dali::Ui::VisualBase::SetCornerRadius(float topLeft, float topRight, float bottomRight, float bottomLeft)
Sets individual corner radii for all four corners.
Only supported type of visual has efforts. topLeft The radius for the top-left corner topRight The radius for the top-right corner bottomRight The radius for the bottom-right corner bottomLeft The radius for the bottom-left corner
References Dali::Ui::DevelVisual::Property::CORNER_RADIUS, SetProperty.
VisualBase & Dali::Ui::VisualBase::SetCornerRadius(const Vector4 &radius)
Sets corner radii from a Vector4.
Only supported type of visual has efforts. radius Corner radii as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft)
References Dali::Ui::DevelVisual::Property::CORNER_RADIUS, SetProperty.
CornerRadiusPolicy Dali::Ui::VisualBase::GetCornerRadiusPolicy() const
Gets the corner radius policy.
The corner radius policy
References Dali::Ui::DevelVisual::Property::CORNER_RADIUS_POLICY.
Referenced by IsCornerRadiusPolicyRelative.
VisualBase & Dali::Ui::VisualBase::SetCornerRadiusPolicy(CornerRadiusPolicy policy)
Sets the corner radius policy.
Only supported type of visual has efforts. policy ABSOLUTE for world-unit values (default), RELATIVE for percentage [0.0, 0.5] of the shorter side
References Dali::Ui::DevelVisual::Property::CORNER_RADIUS_POLICY, SetProperty.
VisualBase & Dali::Ui::VisualBase::SetCornerRadiusPolicyRelative()
Shortcut to set the corner radius policy to RELATIVE.
Only supported type of visual has efforts. Equivalent to SetCornerRadiusPolicy(CornerRadiusPolicy::RELATIVE).
References Dali::Ui::DevelVisual::Property::CORNER_RADIUS_POLICY, Dali::Ui::RELATIVE, SetProperty.
bool Dali::Ui::VisualBase::IsCornerRadiusPolicyRelative() const
Returns true if the corner radius policy is RELATIVE.
True if the policy is RELATIVE, false if ABSOLUTE
References GetCornerRadiusPolicy, Dali::Ui::RELATIVE.
Vector4 Dali::Ui::VisualBase::GetCornerSquareness() const
Gets the corner squareness of the VisualBase.
The corner squareness as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft)
References Dali::Ui::DevelVisual::Property::CORNER_SQUARENESS.
VisualBase & Dali::Ui::VisualBase::SetCornerSquareness(float squareness)
Sets a uniform corner squareness for all four corners.
Only supported type of visual has efforts. squareness The squareness value to apply to all corners
References Dali::Ui::DevelVisual::Property::CORNER_SQUARENESS, SetProperty.
VisualBase & Dali::Ui::VisualBase::SetCornerSquareness(float topLeft, float topRight, float bottomRight, float bottomLeft)
Sets individual corner squareness values for all four corners.
Only supported type of visual has efforts. topLeft The squareness for the top-left corner topRight The squareness for the top-right corner bottomRight The squareness for the bottom-right corner bottomLeft The squareness for the bottom-left corner
References Dali::Ui::DevelVisual::Property::CORNER_SQUARENESS, SetProperty.
VisualBase & Dali::Ui::VisualBase::SetCornerSquareness(const Vector4 &squareness)
Sets corner squareness from a Vector4.
Only supported type of visual has efforts. squareness Squareness values as Vector4 (x=topLeft, y=topRight, z=bottomRight, w=bottomLeft)
References Dali::Ui::DevelVisual::Property::CORNER_SQUARENESS, SetProperty.
float Dali::Ui::VisualBase::GetBorderlineWidth() const
Gets the borderline width of the VisualBase.
The borderline width
References Dali::Ui::DevelVisual::Property::BORDERLINE_WIDTH.
VisualBase & Dali::Ui::VisualBase::SetBorderlineWidth(float width)
Sets the borderline width of the VisualBase.
Only supported type of visual has efforts. width The borderline width to set
References Dali::Ui::DevelVisual::Property::BORDERLINE_WIDTH, SetProperty.
UiColor Dali::Ui::VisualBase::GetBorderlineColor() const
Gets the borderline color of the VisualBase.
The borderline color
References Dali::Ui::Internal::VisualBaseImpl::GetBorderlineColor, Dali::Ui::GetImplementation.
VisualBase & Dali::Ui::VisualBase::SetBorderlineColor(const UiColor &color)
Sets the borderline color of the VisualBase.
Only supported type of visual has efforts. If the UiColor has a color ID, it is resolved from the current theme and a binding is registered so the color is automatically refreshed when the theme changes. color The UiColor to apply
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetBorderlineColor.
float Dali::Ui::VisualBase::GetBorderlineOffset() const
Gets the borderline offset of the VisualBase.
The borderline offset
References Dali::Ui::DevelVisual::Property::BORDERLINE_OFFSET.
VisualBase & Dali::Ui::VisualBase::SetBorderlineOffset(float offset)
Sets the borderline offset of the VisualBase.
Only supported type of visual has efforts. offset The borderline offset to set
References Dali::Ui::DevelVisual::Property::BORDERLINE_OFFSET, SetProperty.
VisualBase & Dali::Ui::VisualBase::As(VisualBase &self)
Assigns this VisualBase instance to a target variable. This method is useful for capturing a reference to a VisualBase created within a declarative UI tree for later use.
VisualBase & Dali::Ui::VisualBase::With(F &&action)
Executes a custom action on this View instance.
Useful for performing additional setup (e.g. signal connections, predefined style application) without breaking the method chain. action A callable (lambda or free function) invoked with a reference to this instance. Reference to this View for fluent chaining.
uint32_t Dali::Ui::VisualBase::GetSiblingOrder() const
Sibling Order Change API.
Get the sibling order of the visual object inside of the container. The sibling order inside of the container. Or 0 if visual object is not in container.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::GetSiblingOrder.
void Dali::Ui::VisualBase::SetSiblingOrder(uint32_t siblingOrder)
Set the sibling order of the visual object inside of the container.
It will change other VisualBase's sibling order to keep the order. It will throw assert if siblingOrder is bigger than the number of visuals that contianer has. siblingOrder The sibling order inside of the container.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::SetSiblingOrder.
void Dali::Ui::VisualBase::Raise()
Raise the visual object above the next sibling visual object.
The VisualBase has been initialized. The VisualBase has been parented.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::Raise.
void Dali::Ui::VisualBase::Lower()
Lower the visual object below the previous sibling visual object.
The VisualBase has been initialized. The VisualBase has been parented.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::Lower.
void Dali::Ui::VisualBase::RaiseToTop()
Raise visual object above all other sibling visual objects.
The VisualBase has been initialized. The VisualBase has been parented.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::RaiseToTop.
void Dali::Ui::VisualBase::LowerToBottom()
Lower visual object to the bottom of all other sibling visual objects.
The VisualBase has been initialized. The VisualBase has been parented.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::LowerToBottom.
void Dali::Ui::VisualBase::RaiseAbove(VisualBase target)
Raises the visual object above the target visual object.
target The target visual object The VisualBase has been initialized. The VisualBase has been parented. The target visual object is a sibling.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::RaiseAbove.
void Dali::Ui::VisualBase::LowerBelow(VisualBase target)
Lower the visual object to below the target visual object.
target The target visual object The VisualBase has been initialized. The VisualBase has been parented. The target visual object is a sibling.
References Dali::Ui::GetImplementation, Dali::Ui::Internal::VisualBaseImpl::LowerBelow.
Dali::Ui::VisualBase::VisualBase()=default
Dali::Ui::VisualBase::~VisualBase()=default
Dali::Ui::VisualBase::VisualBase(const VisualBase &rhs)=default
VisualBase & Dali::Ui::VisualBase::operator=(const VisualBase &rhs)=default
Dali::Ui::VisualBase::VisualBase(VisualBase &&rhs) noexcept=default
VisualBase & Dali::Ui::VisualBase::operator=(VisualBase &&rhs) noexcept=default
Dali::Ui::VisualBase::VisualBase(Dali::Ui::Internal::VisualBaseImpl *object)
This constructor is used by Dali New() methods.
object A pointer to a newly allocated Dali resource