Dali::Ui::Integration::ScrollViewImpl
View Dali::Ui::Integration::ScrollViewImpl::mContent
The content view.
Vector2 Dali::Ui::Integration::ScrollViewImpl::mScrollPosition
Current scroll position.
Vector2 Dali::Ui::Integration::ScrollViewImpl::mCurrentPosition
Current content position.
float Dali::Ui::Integration::ScrollViewImpl::mScrollableWidth
Scrollable content width.
float Dali::Ui::Integration::ScrollViewImpl::mScrollableHeight
Scrollable content height.
ScrollDirection Dali::Ui::Integration::ScrollViewImpl::mScrollDirection
Scroll direction.
float Dali::Ui::Integration::ScrollViewImpl::mMaxFlingDistance
Maximum fling distance.
int Dali::Ui::Integration::ScrollViewImpl::mMinimumFlingDuration
Minimum fling duration.
int Dali::Ui::Integration::ScrollViewImpl::mMaximumFlingDuration
Maximum fling duration.
float Dali::Ui::Integration::ScrollViewImpl::mFlingSensitivity
Fling sensitivity.
float Dali::Ui::Integration::ScrollViewImpl::mDecelerationRate
Deceleration rate.
OverScrollMode Dali::Ui::Integration::ScrollViewImpl::mOverScrollMode
Over scroll mode.
bool Dali::Ui::Integration::ScrollViewImpl::mIsScrolling
Is scrolling in progress.
float Dali::Ui::Integration::ScrollViewImpl::mViewportWidth
Viewport width.
float Dali::Ui::Integration::ScrollViewImpl::mViewportHeight
Viewport height.
float Dali::Ui::Integration::ScrollViewImpl::mMaximumStartY
Maximum start Y position.
float Dali::Ui::Integration::ScrollViewImpl::mMaximumStartX
Maximum start X position.
float Dali::Ui::Integration::ScrollViewImpl::mMinimumStartY
Minimum start Y position.
float Dali::Ui::Integration::ScrollViewImpl::mMinimumStartX
Minimum start X position.
bool Dali::Ui::Integration::ScrollViewImpl::mHasScrollableArea
Has scrollable area.
ScrollBarVisibility Dali::Ui::Integration::ScrollViewImpl::mVerticalScrollBarVisibility
Vertical scroll bar visibility.
ScrollBarVisibility Dali::Ui::Integration::ScrollViewImpl::mHorizontalScrollBarVisibility
Horizontal scroll bar visibility.
Animation Dali::Ui::Integration::ScrollViewImpl::mScrollAnimation
Fling scroll animation.
PanGestureDetector Dali::Ui::Integration::ScrollViewImpl::mPanGestureDetector
Pan gesture detector.
float Dali::Ui::Integration::ScrollViewImpl::mPanThreshold
Additional displacement threshold (px) after Pan is recognized.
Vector2 Dali::Ui::Integration::ScrollViewImpl::mLastPanPosition
Last pan position.
bool Dali::Ui::Integration::ScrollViewImpl::mIntercepting
True while this ScrollView owns the touch sequence.
bool Dali::Ui::Integration::ScrollViewImpl::mJustIntercepted
True for one cycle when interception first begins (prevents double HandleEvent feed)
bool Dali::Ui::Integration::ScrollViewImpl::mPanRecognized
True once PanGestureDetector fires STARTED; waiting for post-recognition threshold.
Vector2 Dali::Ui::Integration::ScrollViewImpl::mPanStartPosition
Screen position at Pan STARTED, used to measure post-recognition displacement.
ScrollBar Dali::Ui::Integration::ScrollViewImpl::mScrollBar
Scroll bar for visual indication of scroll position.
PropertyNotification Dali::Ui::Integration::ScrollViewImpl::mContentPositionNotification
Notifies when content position changes.
Ui::ScrollView::ScrollStartedSignalType Dali::Ui::Integration::ScrollViewImpl::mScrollStartedSignal
Ui::ScrollView::ScrollFinishedSignalType Dali::Ui::Integration::ScrollViewImpl::mScrollFinishedSignal
Ui::ScrollView::ScrollingSignalType Dali::Ui::Integration::ScrollViewImpl::mScrollingSignal
Ui::ScrollView::DragStartedSignalType Dali::Ui::Integration::ScrollViewImpl::mDragStartedSignal
Ui::ScrollView::DragFinishedSignalType Dali::Ui::Integration::ScrollViewImpl::mDragFinishedSignal
Ui::ScrollView::DraggingSignalType Dali::Ui::Integration::ScrollViewImpl::mDraggingSignal
ScrollViewImplPtr Dali::Ui::Integration::ScrollViewImpl::New()
Creates a new ScrollView.
References ScrollViewImpl.
Referenced by Dali::Ui::ScrollView::New.
Dali::Ui::Integration::ScrollViewImpl::~ScrollViewImpl()
Destructor.
Dali::Ui::Integration::ScrollViewImpl::ScrollViewImpl()
ScrollView constructor.
Referenced by New.
Vector2 Dali::Ui::Integration::ScrollViewImpl::VelocityToMovement(const Vector2 &velocity) const
Converts velocity to movement distance.
Vector2 Dali::Ui::Integration::ScrollViewImpl::AdjustMovement(const Vector2 &movement) const
Adjusts movement based on scroll direction.
References Dali::Ui::Both, Dali::Ui::Horizontal, Dali::Ui::Vertical.
Referenced by AdjustDelta.
Vector2 Dali::Ui::Integration::ScrollViewImpl::AdjustDelta(const Vector2 &movement, const Vector2 &currentPosition)
Adjusts delta to stay within bounds.
References AdjustMovement.
Vector2 Dali::Ui::Integration::ScrollViewImpl::AdjustScrollPosition(const Vector2 &position) const
Adjusts scroll position to valid range.
References Dali::Ui::ViewImpl::GetRequestedHeight, Dali::Ui::View::GetRequestedHeight, Dali::Ui::ViewImpl::GetRequestedWidth, Dali::Ui::View::GetRequestedWidth.
Referenced by ScrollTo.
Vector2 Dali::Ui::Integration::ScrollViewImpl::GetScrollPositionForChild(View child, Vector2 current) const
Gets scroll position for a child view.
References Dali::Ui::View::DownCast, GetScrollPositionForChild.
Referenced by GetScrollPositionForChild, ScrollTo.
Vector2 Dali::Ui::Integration::ScrollViewImpl::ContentPositionToScrollPosition(const Vector2 &content) const
Converts content position to scroll position.
References Dali::Ui::ViewImpl::GetPadding.
Referenced by ScrollTo.
Vector2 Dali::Ui::Integration::ScrollViewImpl::DeltaFromScrollPosition(const Vector2 &scrollPosition) const
Converts scroll position to delta.
void Dali::Ui::Integration::ScrollViewImpl::OnInitialize() override
References Dali::Ui::ViewImpl::OnInitialize, Dali::Ui::View::RaiseToTop, Dali::Ui::ScrollBar::SetHorizontalScrollBarVisibility, Dali::Ui::View::SetLayoutDirection, Dali::Ui::Integration::LayoutImpl::SetLayoutManager, Dali::Ui::ScrollBar::SetVerticalScrollBarVisibility.
void Dali::Ui::Integration::ScrollViewImpl::SetContent(View content)
Sets the content view.
References Dali::Ui::View::LowerToBottom, Dali::Ui::View::RaiseToTop.
View Dali::Ui::Integration::ScrollViewImpl::GetContent() const
Gets the content view.
Referenced by Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren.
Vector2 Dali::Ui::Integration::ScrollViewImpl::GetScrollPosition() const
Gets the scroll position.
Referenced by ScrollTo.
void Dali::Ui::Integration::ScrollViewImpl::SetScrollPosition(const Vector2 &position)
Sets the scroll position.
References ScrollTo.
bool Dali::Ui::Integration::ScrollViewImpl::IsScrolling() const
Checks if scrolling is in progress.
float Dali::Ui::Integration::ScrollViewImpl::GetScrollableWidth() const
Gets the scrollable width.
void Dali::Ui::Integration::ScrollViewImpl::SetScrollableWidth(float width)
Sets the scrollable width.
Referenced by Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren.
float Dali::Ui::Integration::ScrollViewImpl::GetScrollableHeight() const
Gets the scrollable height.
void Dali::Ui::Integration::ScrollViewImpl::SetScrollableHeight(float height)
Sets the scrollable height.
Referenced by Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren.
ScrollDirection Dali::Ui::Integration::ScrollViewImpl::GetScrollDirection() const
Gets the scroll direction.
void Dali::Ui::Integration::ScrollViewImpl::SetScrollDirection(ScrollDirection direction)
Sets the scroll direction.
References Dali::Ui::Both, Dali::Ui::Horizontal, Dali::Ui::Vertical.
float Dali::Ui::Integration::ScrollViewImpl::GetMaxFlingDistance() const
Gets the maximum fling distance.
void Dali::Ui::Integration::ScrollViewImpl::SetMaxFlingDistance(float distance)
Sets the maximum fling distance.
int Dali::Ui::Integration::ScrollViewImpl::GetMinimumFlingDuration() const
Gets the minimum duration of fling scroll animation.
void Dali::Ui::Integration::ScrollViewImpl::SetMinimumFlingDuration(int duration)
Sets the minimum duration of fling scroll animation.
int Dali::Ui::Integration::ScrollViewImpl::GetMaximumFlingDuration() const
Gets the maximum duration of fling scroll animation.
void Dali::Ui::Integration::ScrollViewImpl::SetMaximumFlingDuration(int duration)
Sets the maximum duration of fling scroll animation.
float Dali::Ui::Integration::ScrollViewImpl::GetFlingSensitivity() const
Gets the fling sensitivity.
void Dali::Ui::Integration::ScrollViewImpl::SetFlingSensitivity(float sensitivity)
Sets the fling sensitivity.
float Dali::Ui::Integration::ScrollViewImpl::GetDecelerationRate() const
Gets the deceleration rate.
void Dali::Ui::Integration::ScrollViewImpl::SetDecelerationRate(float rate)
Sets the deceleration rate.
OverScrollMode Dali::Ui::Integration::ScrollViewImpl::GetOverScrollMode() const
Gets the over scroll mode.
void Dali::Ui::Integration::ScrollViewImpl::SetOverScrollMode(OverScrollMode mode)
Sets the over scroll mode.
void Dali::Ui::Integration::ScrollViewImpl::ScrollTo(const Vector2 &position, bool animation)
Scrolls to the specified position.
References AdjustScrollPosition, ContentPositionToScrollPosition.
Referenced by ScrollTo, ScrollToX, ScrollToY, SetScrollPosition.
void Dali::Ui::Integration::ScrollViewImpl::ScrollTo(View child, bool animation, ScrollToPosition scrollToPosition)
Scrolls to the specified child view.
References Dali::Ui::Both, Dali::Ui::Center, Dali::Ui::End, GetScrollPosition, GetScrollPositionForChild, Dali::Ui::Horizontal, Dali::Ui::MakeVisible, ScrollTo, Dali::Ui::Start, Dali::Ui::Vertical.
void Dali::Ui::Integration::ScrollViewImpl::ScrollToX(float position, bool animation)
Scrolls to the specified X position.
References ScrollTo.
void Dali::Ui::Integration::ScrollViewImpl::ScrollToY(float position, bool animation)
Scrolls to the specified Y position.
References ScrollTo.
ScrollBarVisibility Dali::Ui::Integration::ScrollViewImpl::GetVerticalScrollBarVisibility() const
Gets the vertical scroll bar visibility.
void Dali::Ui::Integration::ScrollViewImpl::SetVerticalScrollBarVisibility(ScrollBarVisibility visibility)
Sets the vertical scroll bar visibility.
References Dali::Ui::ScrollBar::SetVerticalScrollBarVisibility.
ScrollBarVisibility Dali::Ui::Integration::ScrollViewImpl::GetHorizontalScrollBarVisibility() const
Gets the horizontal scroll bar visibility.
void Dali::Ui::Integration::ScrollViewImpl::SetHorizontalScrollBarVisibility(ScrollBarVisibility visibility)
Sets the horizontal scroll bar visibility.
References Dali::Ui::ScrollBar::SetHorizontalScrollBarVisibility.
Ui::ScrollView::ScrollStartedSignalType & Dali::Ui::Integration::ScrollViewImpl::ScrollStartedSignal()
Gets the scroll started signal.
Ui::ScrollView::ScrollingSignalType & Dali::Ui::Integration::ScrollViewImpl::ScrollingSignal()
Gets the scrolling signal.
Ui::ScrollView::ScrollFinishedSignalType & Dali::Ui::Integration::ScrollViewImpl::ScrollFinishedSignal()
Gets the scroll finished signal.
Ui::ScrollView::DragStartedSignalType & Dali::Ui::Integration::ScrollViewImpl::DragStartedSignal()
Gets the drag started signal.
Ui::ScrollView::DraggingSignalType & Dali::Ui::Integration::ScrollViewImpl::DraggingSignal()
Gets the dragging signal.
Ui::ScrollView::DragFinishedSignalType & Dali::Ui::Integration::ScrollViewImpl::DragFinishedSignal()
Gets the drag finished signal.
void Dali::Ui::Integration::ScrollViewImpl::OnChildRelayout(Actor actor)
Callback for child relayouted.
bool Dali::Ui::Integration::ScrollViewImpl::OnInterceptTouch(Actor actor, TouchEvent touch)
Intercepts touch events before children receive them.
Feeds the raw touch to the PanGestureDetector via HandleEvent and tracks cumulative displacement. Returns true (steals touch from children) once the displacement exceeds mPanThreshold, ensuring scroll works even when children consume touch events.
bool Dali::Ui::Integration::ScrollViewImpl::OnTouch(Actor actor, TouchEvent touch)
Handles touch events on the ScrollView after interception.
Called for subsequent events once OnInterceptTouch has returned true. Feeds each event to the PanGestureDetector via HandleEvent.
bool Dali::Ui::Integration::ScrollViewImpl::OnWheelEvent(Actor actor, WheelEvent event)
Handles mouse wheel events for scrolling.
void Dali::Ui::Integration::ScrollViewImpl::OnPanGesture(Actor actor, PanGesture gesture)
Callback for pan gesture detection.
void Dali::Ui::Integration::ScrollViewImpl::OnDragStarted(const PanGesture &gesture)
Handles drag started.
void Dali::Ui::Integration::ScrollViewImpl::OnDragging(const PanGesture &gesture)
Handles dragging.
void Dali::Ui::Integration::ScrollViewImpl::OnDragFinished(const PanGesture &gesture)
Handles drag finished.
void Dali::Ui::Integration::ScrollViewImpl::SendScrollStarted()
Sends scroll started signal.
void Dali::Ui::Integration::ScrollViewImpl::SendScrolling()
Sends scrolling signal.
void Dali::Ui::Integration::ScrollViewImpl::SendScrollFinished()
Sends scroll finished signal.
void Dali::Ui::Integration::ScrollViewImpl::SendDragStarted()
Sends drag started signal.
void Dali::Ui::Integration::ScrollViewImpl::SendDragging(float deltaX, float deltaY)
Sends dragging signal.
void Dali::Ui::Integration::ScrollViewImpl::SendDragFinished()
Sends drag finished signal.
void Dali::Ui::Integration::ScrollViewImpl::UpdateScrollingProperties()
Updates scrolling properties.
void Dali::Ui::Integration::ScrollViewImpl::ApplyScrollPosition(const Vector2 &position)
Applies scroll position to content.
void Dali::Ui::Integration::ScrollViewImpl::CancelScrollAnimation()
Cancels scroll animation.
void Dali::Ui::Integration::ScrollViewImpl::OnScrollAnimationFinished(Animation animation)
Callback for scroll animation finished.
void Dali::Ui::Integration::ScrollViewImpl::OnContentRelayout()
Callback for content relayout.
void Dali::Ui::Integration::ScrollViewImpl::OnContentPositionChanged(PropertyNotification source)
Callback for content position change (during animation).
void Dali::Ui::Integration::ScrollViewImpl::OnLayoutDirectionChanged(Actor actor, LayoutDirection::Type type)
Callback for layout direction changes.
Manually propagates the new direction to the ScrollBar, which is a STANDALONE child and therefore excluded from the automatic ApplyLayoutDirection traversal.
Dali::Ui::Integration::ScrollViewImpl::ScrollViewImpl(const ScrollViewImpl &)=delete
Dali::Ui::Integration::ScrollViewImpl::ScrollViewImpl(ScrollViewImpl &&)=delete
ScrollViewImpl & Dali::Ui::Integration::ScrollViewImpl::operator=(const ScrollViewImpl &)=delete
ScrollViewImpl & Dali::Ui::Integration::ScrollViewImpl::operator=(ScrollViewImpl &&)=delete
bool Dali::Ui::Integration::ScrollViewImpl::CanScrollHorizontally(ScrollDirection direction)
Checks if can scroll horizontally.
bool Dali::Ui::Integration::ScrollViewImpl::CanScrollVertically(ScrollDirection direction)
Checks if can scroll vertically.