Dali::Ui::IntegrationView
using Dali::Ui::IntegrationView::ChildContainer = typedef Dali::Vector<Ui::View>
Container of child view handles (in add order).
Per-child layout state (measured size, arranged bounds) is owned by the child view itself (ViewImpl). Layout managers that need a mutable working buffer (flex-basis/grow/shrink, stack weight distribution, etc.) allocate one locally per Measure/Arrange call.
DALI_UI_API void Dali::Ui::IntegrationView::AddActorChild(Ui::View view, Dali::Actor actor)
Adds a raw (non-View) Actor as a child of the given View.
View::OnChildAdd normally asserts when the added child cannot be DownCast to Ui::View. This Integration helper bypasses that check so internal modules can attach supporting Actors (clipping stencils, render-effect roots, decoration layers, etc.) without violating the View-only invariant for application code. The added Actor is NOT tracked in the View's child container and therefore is excluded from the View's measure/arrange layout pass. The caller is fully responsible for the Actor's size, position, and lifecycle. view The parent View to add to. actor The raw Actor to attach as a child.
References AllowToAddActorToChildBegin, AllowToAddActorToChildEnd.
DALI_UI_API void Dali::Ui::IntegrationView::AllowToAddActorToChildBegin(Ui::View view)
Allow to Adds some raw (non-View) Actor as a child of the given View for a whiles.
View::OnChildAdd normally asserts when the added child cannot be DownCast to Ui::View. This Integration helper bypasses that check so internal modules can attach supporting Actors (clipping stencils, render-effect roots, decoration layers, etc.) without violating the View-only invariant for application code. The added Actor is NOT tracked in the View's child container and therefore is excluded from the View's measure/arrange layout pass. The caller is fully responsible for the Actor's size, position, and lifecycle. AllowToAddActorToChildEnd() MUST be called at final. view The parent View to allow begin.
Referenced by AddActorChild.
DALI_UI_API void Dali::Ui::IntegrationView::AllowToAddActorToChildEnd(Ui::View view)
Stop allowing to Adds some raw (non-View) Actor as a child of the given View for a whiles.
AllowToAddActorToChildBegin() MUST be called before. view The parent View to allow end.
Referenced by AddActorChild.
DALI_UI_API void Dali::Ui::IntegrationView::SetTrait(ViewImpl &viewImpl, TraitId id, Dali::BaseHandle handle)
Sets trait data on a View.
If the stored object implements TraitInterface, lifecycle callbacks (OnBeforeAttached, OnAttached, OnDetached, OnViewDestroying) are invoked. Otherwise the object is stored without callbacks. viewImpl The view implementation to attach to id The key to identify the trait handle The object to store
Referenced by Dali::Ui::ViewImpl::EnsureInteractiveTrait, Dali::Ui::ViewImpl::EnsureSelectableTrait, Dali::Ui::ViewImpl::SetInteractionEffect, Dali::Ui::Integration::LayoutImpl::SetLayoutManager.
DALI_UI_API Dali::BaseHandle Dali::Ui::IntegrationView::GetTrait(const ViewImpl &viewImpl, TraitId id)
Gets trait data from a View.
viewImpl The view implementation to query id The key to identify the trait The stored handle, or an empty handle if not found
Referenced by Dali::Ui::ViewImpl::EnsureInteractiveTrait, GetTrait, Dali::Ui::ViewImpl::IsInteractive, Dali::Ui::ViewImpl::IsSelectable.
DALI_UI_API bool Dali::Ui::IntegrationView::RemoveTrait(ViewImpl &viewImpl, TraitId id)
Removes trait data from a View.
viewImpl The view implementation to modify id The key to identify the trait true if the trait was found and removed
Referenced by Dali::Ui::Integration::ExclusiveTraitImpl::OnBeforeAttached, Dali::Ui::ViewImpl::SetInteractionEffect.
DALI_UI_API void Dali::Ui::IntegrationView::SetState(ViewImpl &viewImpl, ViewState state, bool on, InputEvent cause=InputEvent::None())
Updates a state bit in the view's ViewState and emits StateChangedSignal.
viewImpl The view implementation state The state to set or clear on True to add the state, false to remove it cause Input event that triggered the change; leave default if programmatic
Referenced by Dali::Ui::ViewImpl::OnFocusChanged, Dali::Ui::ViewImpl::OnPropertySet, Dali::Ui::Integration::InteractiveTraitImpl::SetPseudoDisabled.
DALI_UI_API void Dali::Ui::IntegrationView::SetNamedStateHandler(ViewImpl &viewImpl, const Dali::String &id, Dali::ConnectionTrackerInterface *tracker, CallbackBase *callback)
Internal helper for WhenStateChanged templates.
Referenced by WhenStateChanged, WhenStateChanged, WhenStateChanged, WhenStateChanged.
DALI_UI_API bool Dali::Ui::IntegrationView::UnsetStateHandler(ViewImpl &viewImpl, const Dali::String &id)
Removes a named state-change handler.
viewImpl The view implementation id The handler identifier to remove True if a handler was found and removed
DALI_UI_API bool Dali::Ui::IntegrationView::UnsetStateHandlerWhenNotProcessing(ViewImpl &viewImpl, const Dali::String &id)
Removes a named state-change handler only if it is not currently being processed.
viewImpl The view implementation id The handler identifier to remove True if removed, false if currently processing or not found
DALI_UI_API void Dali::Ui::IntegrationView::SetState(Ui::View view, ViewState state, bool on, InputEvent cause=InputEvent::None())
Updates a state bit in the view's ViewState and emits StateChangedSignal.
viewImpl The view implementation state The state to set or clear on True to add the state, false to remove it cause Input event that triggered the change; leave default if programmatic
References Dali::Ui::GetImpl.
DALI_UI_API void Dali::Ui::IntegrationView::SetNamedStateHandler(Ui::View view, const Dali::String &id, Dali::ConnectionTrackerInterface *tracker, CallbackBase *callback)
Internal helper for WhenStateChanged templates (View overload).
References Dali::Ui::GetImpl.
DALI_UI_API bool Dali::Ui::IntegrationView::UnsetStateHandler(Ui::View view, const Dali::String &id)
Removes a named state-change handler.
viewImpl The view implementation id The handler identifier to remove True if a handler was found and removed
References Dali::Ui::GetImpl.
DALI_UI_API bool Dali::Ui::IntegrationView::UnsetStateHandlerWhenNotProcessing(Ui::View view, const Dali::String &id)
Removes a named state-change handler only if it is not currently being processed.
viewImpl The view implementation id The handler identifier to remove True if removed, false if currently processing or not found
References Dali::Ui::GetImpl.
DALI_UI_API Dali::Property Dali::Ui::IntegrationView::GetVisualProperty(Ui::View view, Dali::Property::Index index, Dali::Property::Key visualPropertyKey)
Returns a Property handle for animating a visual sub-property.
Uses ViewDataImpl::GetVisualProperty internally. If the visual for the given index has not been created yet, the returned Property has Property::INVALID_INDEX. view The view to query. index The property index that owns the visual (e.g. View::Property::BACKGROUND). visualPropertyKey The visual sub-property key (e.g. Visual::Property::MIX_COLOR). A Property targeting the visual sub-property, or an invalid Property.
References Dali::Ui::GetImpl.
DALI_UI_API bool Dali::Ui::IntegrationView::IsLayoutModeStandalone(const ViewImpl &viewImpl)
Convenience: returns true if LayoutMode is Standalone.
viewImpl The view implementation to query True if the view's layout mode is Standalone
References Dali::Ui::ViewImpl::GetLayoutMode, Dali::Ui::STANDALONE.
Referenced by Dali::Ui::Integration::AbsoluteLayoutManager::ArrangeChildren, Dali::Ui::Integration::ScrollViewLayoutManager::ArrangeChildren, Dali::Ui::Integration::StackLayoutManager::ArrangeChildren, Dali::Ui::ViewImpl::InvalidateArrange, Dali::Ui::ViewImpl::InvalidateMeasure, Dali::Ui::Integration::AbsoluteLayoutManager::Measure, Dali::Ui::Integration::FlexLayoutManager::Measure, Dali::Ui::Integration::ScrollViewLayoutManager::Measure, Dali::Ui::Integration::StackLayoutManager::Measure, Dali::Ui::ViewImpl::OnArrange, Dali::Ui::ViewImpl::OnChildAdd, Dali::Ui::ViewImpl::OnChildRemove, Dali::Ui::ViewImpl::OnMeasure, Dali::Ui::ViewImpl::OnSceneConnection.
DALI_UI_API ChildContainer & Dali::Ui::IntegrationView::GetChildren(ViewImpl &viewImpl)
Gets the children container from a view.
viewImpl The view implementation Reference to the children container
Referenced by Dali::Ui::LayoutManager::GetChildren.
DALI_UI_API const ChildContainer & Dali::Ui::IntegrationView::GetChildren(const ViewImpl &viewImpl)
Gets the children container from a view.
viewImpl The view implementation Reference to the children container
DALI_UI_API bool Dali::Ui::IntegrationView::IsLayout(ViewImpl &viewImpl)
Returns whether this view is a Layout container.
viewImpl The view implementation to query True if the view is a Layout (i.e. Ui::Layout::DownCast succeeds)
References Dali::Ui::Layout::DownCast.
Referenced by Dali::Ui::ViewImpl::OnRelayout.
HandleType Dali::Ui::IntegrationView::GetTrait(const ViewImpl &viewImpl, TraitId id)
Gets trait data from a View and DownCasts to the specified handle type.
HandleType A handle class that provides a static DownCast(BaseHandle) method viewImpl The view implementation to query id The key to identify the trait The DownCast handle, or an empty handle if not found or cast fails
References GetTrait.
void Dali::Ui::IntegrationView::WhenStateChanged(ViewImpl &viewImpl, const Dali::String &id, X *obj, void(X::*func)(Ui::View, const StateEvent &))
Registers a named state-change handler using a member function.
viewImpl The view implementation id Unique identifier for this handler obj Object whose member function will be called func Member function with signature void(View, const StateEvent&)
References SetNamedStateHandler.
void Dali::Ui::IntegrationView::WhenStateChanged(ViewImpl &viewImpl, const Dali::String &id, Dali::ConnectionTrackerInterface *tracker, F &&func)
Registers a named state-change handler using a callable (e.g. lambda).
viewImpl The view implementation id Unique identifier for this handler tracker ConnectionTrackerInterface for automatic lifetime management func Callable with signature void(View, const StateEvent&)
References SetNamedStateHandler.
void Dali::Ui::IntegrationView::WhenStateChanged(Ui::View view, const Dali::String &id, X *obj, void(X::*func)(Ui::View, const StateEvent &))
Registers a named state-change handler using a member function.
view The view handle id Unique identifier for this handler obj Object whose member function will be called func Member function with signature void(View, const StateEvent&)
References SetNamedStateHandler.
void Dali::Ui::IntegrationView::WhenStateChanged(Ui::View view, const Dali::String &id, Dali::ConnectionTrackerInterface *tracker, F &&func)
Registers a named state-change handler using a callable (e.g. lambda).
view The view handle id Unique identifier for this handler tracker ConnectionTrackerInterface for automatic lifetime management func Callable with signature void(View, const StateEvent&)
References SetNamedStateHandler.