Dali::UniquePtr
friend class UniquePtr
constexpr Deleter Dali::UniquePtr< Type, Deleter, typename >::DefaultDeleter
Default deleter.
Referenced by Dali::UniquePtr< Type, Deleter, typename >::operator=, Dali::UniquePtr< Type, Deleter, typename >::operator=.
Type* Dali::UniquePtr< Type, Deleter, typename >::mPtr
The managed object.
DALI_NO_UNIQUE_ADDRESS Deleter Dali::UniquePtr< Type, Deleter, typename >::mDeleter
The custom deleter.
Dali::UniquePtr< Type, Deleter, typename >::UniquePtr()
Default constructor. @SINCE_2_5.11.
Dali::UniquePtr< Type, Deleter, typename >::UniquePtr(Type *ptr, Deleter deleter=DefaultDeleter)
Constructor that takes ownership of a raw pointer. @SINCE_2_5.11.
ptr Raw pointer to take ownership of deleter The function to delete the ptr If deleter is nullptr, then the DefaultDeleter will be used (i.e. simple delete)
Dali::UniquePtr< Type, Deleter, typename >::~UniquePtr()
Destructor. @SINCE_2_5.11.
Dali::UniquePtr< Type, Deleter, typename >::UniquePtr(UniquePtr &&other) noexcept
Move constructor. @SINCE_2_5.11.
other The object to be moved other deleter is not changed
UniquePtr & Dali::UniquePtr< Type, Deleter, typename >::operator=(UniquePtr &&other) noexcept
Move assignment operator. @SINCE_2_5.11.
other The object to be moved other deleter is not changed
References Dali::UniquePtr< Type, Deleter, typename >::DefaultDeleter.
Dali::UniquePtr< Type, Deleter, typename >::UniquePtr(UniquePtr< U, E > &&other) noexcept
Converting move constructor from derived type.
Constructs a UniquePtr<Base> from a UniquePtr<Derived>. @SINCE_2_5.11 U The derived type E The deleter type of the source other The derived UniquePtr to move from Enabled only if U* is convertible to Type*
UniquePtr & Dali::UniquePtr< Type, Deleter, typename >::operator=(UniquePtr< U, E > &&other) noexcept
Converting move assignment operator from derived type.
Assigns a UniquePtr<Base> from a UniquePtr<Derived>. @SINCE_2_5.11 U The derived type E The deleter type of the source other The derived UniquePtr to move from Reference to this object Enabled only if U* is convertible to Type*
References Dali::UniquePtr< Type, Deleter, typename >::DefaultDeleter.
Dali::UniquePtr< Type, Deleter, typename >::UniquePtr(const UniquePtr &)=delete
Deleted copy constructor.
UniquePtr & Dali::UniquePtr< Type, Deleter, typename >::operator=(const UniquePtr &)=delete
Deleted copy assignment operator.
Type & Dali::UniquePtr< Type, Deleter, typename >::operator*()
Overloaded dereference operator. @SINCE_2_5.11.
A reference to the object
const Type & Dali::UniquePtr< Type, Deleter, typename >::operator*() const
Overloaded const dereference operator. @SINCE_2_5.11.
A const reference to the object
Type * Dali::UniquePtr< Type, Deleter, typename >::operator->()
Overloaded pointer operator. @SINCE_2_5.11.
A pointer to the object
const Type * Dali::UniquePtr< Type, Deleter, typename >::operator->() const
Overloaded pointer to const operator. @SINCE_2_5.11.
A pointer to a const object
Dali::UniquePtr< Type, Deleter, typename >::operator bool() const
Explicit conversion to bool. @SINCE_2_5.11.
Type * Dali::UniquePtr< Type, Deleter, typename >::Get()
Get the raw pointer. @SINCE_2_5.11.
The raw pointer to the object
const Type * Dali::UniquePtr< Type, Deleter, typename >::Get() const
Get the raw pointer to const object. @SINCE_2_5.11.
The raw pointer to the const object
Type * Dali::UniquePtr< Type, Deleter, typename >::Release()
Release ownership of the managed object. @SINCE_2_5.11.
A pointer to the object that has been released The deleter remains the same as before
void Dali::UniquePtr< Type, Deleter, typename >::Reset(Type *ptr=nullptr)
Reset the managed object. @SINCE_2_5.11.
ptr The object to take ownership of The deleter remains the same as before
Deleter & Dali::UniquePtr< Type, Deleter, typename >::GetDeleter()
Get the deleter. @SINCE_2_5.19.
A reference to the deleter
Referenced by Dali::UniquePtr< Type, Deleter, typename EnableIf<!IsFunctionPointer< Deleter >::value >::type >::operator=, Dali::UniquePtr< Type, Deleter, typename EnableIf<!IsFunctionPointer< Deleter >::value >::type >::operator=, Dali::UniquePtr< Type, Deleter, typename EnableIf<!IsFunctionPointer< Deleter >::value >::type >::Reset, Dali::UniquePtr< Type, Deleter, typename EnableIf<!IsFunctionPointer< Deleter >::value >::type >::~UniquePtr.
const Deleter & Dali::UniquePtr< Type, Deleter, typename >::GetDeleter() const
Get the deleter (const). @SINCE_2_5.19.
A const reference to the deleter