Dali::SlotDelegate
Slot* Dali::SlotDelegate< Slot >::mSlot
The slot object.
ConnectionTracker Dali::SlotDelegate< Slot >::mConnectionTracker
A connection tracker.
Dali::SlotDelegate< Slot >::SlotDelegate(Slot *slot)
Constructor.
@SINCE_1_0.0 slot The object with a callback
Dali::SlotDelegate< Slot >::~SlotDelegate()=default
Non-virtual destructor.
@SINCE_1_0.0
void Dali::SlotDelegate< Slot >::DisconnectAll()
Disconnects all signals from this object.
@SINCE_1_0.0
References Dali::ConnectionTracker::DisconnectAll.
std::size_t Dali::SlotDelegate< Slot >::GetConnectionCount() const
Returns the connection count. @SINCE_1_0.0.
The connection count
References Dali::ConnectionTracker::GetConnectionCount.
Slot * Dali::SlotDelegate< Slot >::GetSlot()
Retrieves the slot object.
@SINCE_1_0.0 The object with a callback
Referenced by Dali::Signal< Ret()>::Connect, Dali::Signal< Ret(Arg0)>::Connect, Dali::Signal< Ret(Arg0, Arg1)>::Connect, Dali::Signal< Ret(Arg0, Arg1, Arg2)>::Connect, Dali::Signal< void()>::Connect, Dali::Signal< void(Arg0)>::Connect, Dali::Signal< void(Arg0, Arg1)>::Connect, Dali::Signal< void(Arg0, Arg1, Arg2)>::Connect, Dali::Signal< Ret()>::Disconnect, Dali::Signal< Ret(Arg0)>::Disconnect, Dali::Signal< Ret(Arg0, Arg1)>::Disconnect, Dali::Signal< Ret(Arg0, Arg1, Arg2)>::Disconnect, Dali::Signal< void()>::Disconnect, Dali::Signal< void(Arg0)>::Disconnect, Dali::Signal< void(Arg0, Arg1)>::Disconnect, Dali::Signal< void(Arg0, Arg1, Arg2)>::Disconnect.
ConnectionTracker * Dali::SlotDelegate< Slot >::GetConnectionTracker()
Retrieves the connection tracker component.
@SINCE_1_0.0 The connection tracker component
Referenced by Dali::Signal< Ret()>::Connect, Dali::Signal< Ret(Arg0)>::Connect, Dali::Signal< Ret(Arg0, Arg1)>::Connect, Dali::Signal< Ret(Arg0, Arg1, Arg2)>::Connect, Dali::Signal< void()>::Connect, Dali::Signal< void(Arg0)>::Connect, Dali::Signal< void(Arg0, Arg1)>::Connect, Dali::Signal< void(Arg0, Arg1, Arg2)>::Connect, Dali::Signal< Ret()>::Disconnect, Dali::Signal< Ret(Arg0)>::Disconnect, Dali::Signal< Ret(Arg0, Arg1)>::Disconnect, Dali::Signal< Ret(Arg0, Arg1, Arg2)>::Disconnect, Dali::Signal< void()>::Disconnect, Dali::Signal< void(Arg0)>::Disconnect, Dali::Signal< void(Arg0, Arg1)>::Disconnect, Dali::Signal< void(Arg0, Arg1, Arg2)>::Disconnect.
Dali::SlotDelegate< Slot >::SlotDelegate(const SlotDelegate &)=delete
Deleted copy constructor. @SINCE_1_0.0.
Dali::SlotDelegate< Slot >::SlotDelegate(SlotDelegate &&)=delete
Deleted move constructor. @SINCE_1_9.25.
SlotDelegate & Dali::SlotDelegate< Slot >::operator=(const SlotDelegate &)=delete
Deleted copy assignment operator. @SINCE_1_0.0.
SlotDelegate & Dali::SlotDelegate< Slot >::operator=(SlotDelegate &&)=delete
Deleted move assignment operator. @SINCE_1_9.25.