Dali::Handle
Capability
Some objects support dynamic property creation at run-time.
New properties are registered by calling RegisterProperty() with an unused property name. @SINCE_1_0.0
using Dali::Handle::PropertySetSignalType = Signal<void(Handle handle, Property::Index index, const Property::Value& value)>
PropertySetSignal function prototype for signal handler. Called when a property is set on this object.
Dali::Handle::Handle(Dali::Internal::Object *handle)
This constructor is used by Dali New() methods.
@SINCE_1_0.0 handle A pointer to a newly allocated Dali resource
Dali::Handle::Handle()
This constructor provides an uninitialized Dali::Handle.
This should be initialized with a Dali New() method before use. Methods called on an uninitialized Dali::Handle will assert. Handlehandle;//uninitialized handle.SomeMethod();//unsafe!Thiswillassert handle=SomeClass::New();//nowinitialized handle.SomeMethod();//safe @SINCE_1_0.0
Referenced by DownCast, New.
Dali::Handle::~Handle()
Dali::Handle is intended as a base class.
This is non-virtual since derived Handle types must not contain data or virtual methods. @SINCE_1_0.0
Dali::Handle::Handle(const Handle &handle)
This copy constructor is required for (smart) pointer semantics.
@SINCE_1_0.0 handle A reference to the copied handle
Handle & Dali::Handle::operator=(const Handle &rhs)
This assignment operator is required for (smart) pointer semantics.
@SINCE_1_0.0 rhs A reference to the copied handle A reference to this
Dali::Handle::Handle(Handle &&rhs) noexcept
Move constructor.
@SINCE_1_9.22 rhs A reference to the moved handle
Handle & Dali::Handle::operator=(Handle &&rhs) noexcept
Move assignment operator.
@SINCE_1_9.22 rhs A reference to the moved handle A reference to this handle
References Dali::DownCast.
bool Dali::Handle::Supports(Capability capability) const
Queries whether an handle supports a given capability.
@SINCE_1_0.0 capability The queried capability True if the capability is supported
References Dali::GetImplementation.
uint32_t Dali::Handle::GetPropertyCount() const
Queries how many properties are provided by an handle.
This may vary between instances of a class, if dynamic properties are supported. @SINCE_1_0.0 The number of properties
References Dali::GetImplementation.
Dali::String Dali::Handle::GetPropertyName(Property::Index index) const
Queries the name of a property.
@SINCE_1_0.0 index The index of the property The name of the property
References Dali::GetImplementation.
Referenced by Dali::Scripting::CreatePropertyMap.
Property::Index Dali::Handle::GetPropertyIndex(Property::Key key) const
Query the index of a property using the given key.
@SINCE_1_9.27 key The key of the property to search for. (The name or integer key provided to RegisterProperty()). the matching property index of the key, or Property::INVALID_INDEX if no property matches the given key.
References Dali::GetImplementation.
Referenced by GetCurrentProperty, GetProperty, Dali::Scripting::NewActor, operator[], SetProperty.
bool Dali::Handle::IsPropertyWritable(Property::Index index) const
Queries whether a property can be set using SetProperty().
@SINCE_1_0.0 index The index of the property True if the property is writable Property::INVALID_INDEX < index.
References Dali::GetImplementation.
bool Dali::Handle::IsPropertyAnimatable(Property::Index index) const
Queries whether a writable property can be the target of an animation or constraint.
@SINCE_1_0.0 index The index of the property True if the property is animatable
References Dali::GetImplementation.
bool Dali::Handle::IsPropertyAConstraintInput(Property::Index index) const
Queries whether a property can be used as in input to a constraint.
@SINCE_1_0.0 index The index of the property True if the property can be used as a constraint input
References Dali::GetImplementation.
Property::Type Dali::Handle::GetPropertyType(Property::Index index) const
Queries the type of a property.
@SINCE_1_0.0 index The index of the property The type of the property
References Dali::GetImplementation.
void Dali::Handle::SetProperty(Property::Index index, Property::Value propertyValue)
Sets the value of an existing property.
Property should be write-able. Setting a read-only property is a no-op. @SINCE_1_0.0 index The index of the property propertyValue The new value of the property The property types match i.e. propertyValue.GetType() is equal to GetPropertyType(index).
References Dali::GetImplementation.
Referenced by Dali::Scripting::NewActor, Dali::IndirectValue::operator=, SetProperty.
bool Dali::Handle::SetProperty(const Dali::String &propertyName, Property::Value propertyValue)
Sets the value of an existing property by name.
This is a convenience overload for looking up the property index from a string key before setting the value. Property should be write-able. Setting a read-only property is a no-op. @SINCE_2_5.22 propertyName The name of the property propertyValue The new value of the property True if the property name was found and the set request was issued The property types match i.e. propertyValue.GetType() is equal to GetPropertyType(index).
References GetPropertyIndex, Dali::Property::INVALID_INDEX, Dali::Property::Key, SetProperty.
void Dali::Handle::ReserveCustomProperties(int propertyCount)
Reserves a number of custom properties.
Saves automatic re-allocation of vectors for properties when we know in advance how many there will be. propertyCount The total number of initial properties.
References Dali::GetImplementation.
Property::Index Dali::Handle::RegisterProperty(Dali::String name, Property::Value propertyValue)
Registers a new animatable property.
@SINCE_1_0.0 name The name of the property propertyValue The new value of the property The index of the property or Property::INVALID_INDEX if registration failed The object supports dynamic properties i.e. Supports(Handle::DYNAMIC_PROPERTIES) returns true. Property names are expected to be unique, but this is not enforced. Property indices are unique to each registered custom property in a given object. returns Property::INVALID_INDEX if registration failed. This can happen if you try to register animatable property on an object that does not have scene graph object. Only the following types can be animated: Property::BOOLEAN Property::FLOAT Property::INTEGER Property::VECTOR2 Property::VECTOR3 Property::VECTOR4 Property::MATRIX3 Property::MATRIX Property::ROTATION If a property with the desired name already exists, then the value given is just set.
References Dali::GetImplementation.
Referenced by Dali::WeightObject::New.
Property::Index Dali::Handle::RegisterUniqueProperty(Dali::String name, Property::Value propertyValue)
Registers a new animatable property.
@SINCE_2_1.6 name The name of the property propertyValue The new value of the property The index of the property or Property::INVALID_INDEX if registration failed The object supports dynamic properties i.e. Supports(Handle::DYNAMIC_PROPERTIES) returns true. Property names are expected to be unique, but this is DEFINITELY not enforced. It is up to the caller to enforce uniqueness. Property indices are unique to each registered custom property in a given object. returns Property::INVALID_INDEX if registration failed. This can happen if you try to register animatable property on an object that does not have scene graph object. Only the following types can be animated: Property::BOOLEAN Property::FLOAT Property::INTEGER Property::VECTOR2 Property::VECTOR3 Property::VECTOR4 Property::MATRIX3 Property::MATRIX Property::ROTATION If a property with the desired name already exists, then this creates a secondary entry to a different scene graph property; Access by index works as expected, but uniform values will use the last registered version, not the existing version, so things may break.
References Dali::GetImplementation, Dali::Property::INVALID_KEY.
Property::Index Dali::Handle::RegisterProperty(Property::Index key, Dali::String name, Property::Value propertyValue)
Register a new animatable property with an integer key.
@SINCE_1_9.27 key The integer key of the property. name The text key of the property. propertyValue The new value of the property. The index of the property or Property::INVALID_INDEX if registration failed The object supports dynamic properties i.e. Supports(Handle::DYNAMIC_PROPERTIES) returns true. Property names and keys are expected to be unique, but this is not enforced. Property indices are unique to each registered custom property in a given object. TodoCHECK THIS! Returns Property::INVALID_INDEX if registration failed. This can happen if you try to register animatable property on an object that does not have scene graph object. The returned property index is not the same as the integer key (though it shares a type) This version of RegisterProperty associates both an integer key and the text key with the property, allowing for lookup of the property index by either key or name ( which is useful when other classes know the key but not the name ) Only the following types can be animated: Property::BOOLEAN Property::FLOAT Property::INTEGER Property::VECTOR2 Property::VECTOR3 Property::VECTOR4 Property::MATRIX3 Property::MATRIX Property::ROTATION If a property with the desired name already exists, then the value given is just set.
References Dali::GetImplementation.
Property::Index Dali::Handle::RegisterUniqueProperty(Property::Index key, Dali::String name, Property::Value propertyValue)
Register a new animatable property with an integer key.
@SINCE_2_1.6 key The integer key of the property. name The text key of the property. propertyValue The new value of the property. The index of the property or Property::INVALID_INDEX if registration failed It is up to the caller to guarantee that the property is unique. This allows many checks to be skipped. The object supports dynamic properties i.e. Supports(Handle::DYNAMIC_PROPERTIES) returns true. Property names and keys are expected to be unique, and are therefore just added without any checks. Property indices are unique to each registered custom property in a given object. Returns Property::INVALID_INDEX if registration failed. This can happen if you try to register animatable property on an object that does not have scene graph object. The returned property index is not the same as the integer key (though it shares a type) This version of RegisterProperty associates both an integer key and the text key with the property, allowing for lookup of the property index by either key or name ( which is useful when other classes know the key but not the name ) Only the following types can be animated: Property::BOOLEAN Property::FLOAT Property::INTEGER Property::VECTOR2 Property::VECTOR3 Property::VECTOR4 Property::MATRIX3 Property::MATRIX Property::ROTATION If a property with the desired name already exists, then this will create a second entry with the same name, and may cause problems. It is up to the caller to prevent this happening. Possible side effects are: lookup by name always finds the first such property, not the second; whereas, writing uniform value to shader will use the second, not the first; Using the returned Property::Index for future reference will always access the correct property.
References Dali::GetImplementation.
Property::Index Dali::Handle::RegisterProperty(Dali::String name, Property::Value propertyValue, Property::AccessMode accessMode)
Registers a new property.
Properties can be set as non animatable using property attributes. @SINCE_1_0.0 name The name of the property propertyValue The new value of the property accessMode The property access mode (writable, animatable etc) The index of the property The handle supports dynamic properties i.e. Supports(Handle::DYNAMIC_PROPERTIES) returns true. name is unused i.e. GetPropertyIndex(name) returns PropertyIndex::INVALID. Only the following types can be animated: Property::BOOLEAN Property::FLOAT Property::INTEGER Property::VECTOR2 Property::VECTOR3 Property::VECTOR4 Property::MATRIX3 Property::MATRIX Property::ROTATION If a property with the desired name already exists, then the value given is just set.
References Dali::GetImplementation.
Property::Value Dali::Handle::GetProperty(Property::Index index) const
Retrieves a property value.
@SINCE_1_0.0 index The index of the property The property value This returns the value set by SetProperty() or the animation target value if it is being animated. To get the current value on the scene-graph, use GetCurrentProperty().
References Dali::GetImplementation.
Referenced by Dali::Scripting::CreatePropertyMap, GetProperty.
T Dali::Handle::GetProperty(Property::Index index) const
Convenience function for obtaining a property of a known type.
@SINCE_1_0.0 index The index of the property The property value The property types match i.e. PropertyTypes::Get<T>() is equal to GetPropertyType(index). GetProperty()
Property::Value Dali::Handle::GetProperty(const Dali::String &propertyName) const
Retrieves a property value by name.
This is a convenience overload for looking up the property index from a string key before retrieving the value. @SINCE_2_5.22 propertyName The name of the property The property value, or an empty Property::Value if the property name was not found This returns the value set by SetProperty() or the animation target value if it is being animated. To get the current value on the scene-graph, use GetCurrentProperty().
References GetProperty, GetPropertyIndex, Dali::Property::INVALID_INDEX, Dali::Property::Key.
T Dali::Handle::GetProperty(const Dali::String &propertyName) const
Convenience function for obtaining a property of a known type by name.
This is a convenience overload for looking up the property index from a string key before retrieving the value. @SINCE_2_5.22 propertyName The name of the property The property value, or a default-constructed T if the property name was not found The property types match i.e. PropertyTypes::Get<T>() is equal to GetPropertyType(index). GetProperty(const Dali::String&)
Property::Value Dali::Handle::GetCurrentProperty(Property::Index index) const
Retrieves the latest value of the property from the scene-graph.
@SINCE_1_2.41 index The index of the property The property value This returns the value of the property in the last rendered frame so can be different to that set by SetProperty() if the set-message has not been processed by the scene-graph yet. To retrieve the value set by SetProperty(), use GetProperty().
References Dali::GetImplementation.
Referenced by GetCurrentProperty.
T Dali::Handle::GetCurrentProperty(Property::Index index) const
Convenience function for obtaining the current value of a property of a known type.
@SINCE_1_2.41 index The index of the property The property value The property types match i.e. PropertyTypes::Get<T>() is equal to GetPropertyType(index). GetCurrentProperty()
Property::Value Dali::Handle::GetCurrentProperty(const Dali::String &propertyName) const
Retrieves the latest value of the property from the scene-graph by name.
This is a convenience overload for looking up the property index from a string key before retrieving the current value. @SINCE_2_5.22 propertyName The name of the property The property value, or an empty Property::Value if the property name was not found This returns the value of the property in the last rendered frame so can be different to that set by SetProperty() if the set-message has not been processed by the scene-graph yet. To retrieve the value set by SetProperty(), use GetProperty().
References GetCurrentProperty, GetPropertyIndex, Dali::Property::INVALID_INDEX, Dali::Property::Key.
T Dali::Handle::GetCurrentProperty(const Dali::String &propertyName) const
Convenience function for obtaining the current value of a property of a known type by name.
This is a convenience overload for looking up the property index from a string key before retrieving the current value. @SINCE_2_5.22 propertyName The name of the property The property value, or a default-constructed T if the property name was not found The property types match i.e. PropertyTypes::Get<T>() is equal to GetPropertyType(index). GetCurrentProperty(const Dali::String&)
void Dali::Handle::SetProperties(const Property::Map &properties)
Sets all the properties in the given property map.
@SINCE_1_9.27 properties The properties to set
References Dali::GetImplementation.
void Dali::Handle::GetProperties(Property::Map &properties)
Retrieves all the properties and the values for this object.
@SINCE_1_9.27 properties A map which is populated with the index-value pairs The properties map will be cleared by this method first.
References Dali::GetImplementation.
void Dali::Handle::GetPropertyIndices(Property::IndexContainer &indices) const
Retrieves all the property indices for this object (including custom properties).
@SINCE_1_0.0 indices A container of property indices for this object The added container is cleared.
References Dali::GetImplementation.
Referenced by Dali::Scripting::CreatePropertyMap.
bool Dali::Handle::DoesCustomPropertyExist(Property::Index index)
Determine if the custom property index exists on this object without throwing a Dali::Exception.
@SINCE_1_9.27 This does not check default properties. index The index of the property to test for
References Dali::GetImplementation.
Dali::PropertyNotification Dali::Handle::AddPropertyNotification(Property::Index index, const PropertyCondition &condition)
Adds a property notification to this object.
@SINCE_1_0.0 index The index of the property condition The notification will be triggered when this condition is satisfied A handle to the newly created PropertyNotification
References Dali::GetImplementation.
Dali::PropertyNotification Dali::Handle::AddPropertyNotification(Property::Index index, int componentIndex, const PropertyCondition &condition)
Adds a property notification to this object.
@SINCE_1_0.0 index The index of the property componentIndex Index to the component of a complex property such as a Vector condition The notification will be triggered when this condition is satisfied A handle to the newly created PropertyNotification
References Dali::GetImplementation.
void Dali::Handle::RemovePropertyNotification(Dali::PropertyNotification propertyNotification)
Removes a property notification from this object.
@SINCE_1_0.0 propertyNotification The propertyNotification to be removed
References Dali::GetImplementation.
void Dali::Handle::RemovePropertyNotifications()
Removes all property notifications from this object. @SINCE_1_0.0.
References Dali::GetImplementation.
void Dali::Handle::RemoveConstraints()
Removes all default tag constraints and custom constraints from an Object.
@SINCE_1_0.0 The object has been initialized.
References Dali::CUSTOM_CONSTRAINT_TAG_MAX, Dali::DEFAULT_TAG, RemoveConstraints.
Referenced by RemoveConstraints.
void Dali::Handle::RemoveConstraints(uint32_t tag)
Removes all the constraint from the Object with a matching tag.
We can only use tag between [ConstraintTagRanges::CUSTOM_CONSTRAINT_TAG_START ConstraintTagRanges::CUSTOM_CONSTRAINT_TAG_END] or ConstraintTagRanges::DEFAULT_TAG @SINCE_1_0.0 tag The tag of the constraints which will be removed The Object has been initialized.
References Dali::CUSTOM_CONSTRAINT_TAG_MAX, DALI_ASSERT_ALWAYS, Dali::GetImplementation.
void Dali::Handle::RemoveConstraints(uint32_t tagBegin, uint32_t tagEnd)
Removes all the constraint from the Object with a range of tags [tagBegin tagEnd).
We can only use tag between [ConstraintTagRanges::CUSTOM_CONSTRAINT_TAG_START ConstraintTagRanges::CUSTOM_CONSTRAINT_TAG_END] or ConstraintTagRanges::DEFAULT_TAG @SINCE_2_4.14 tagBegin The begin tag of the constraints which will be removed (include) tagEnd The end tag of the constraints which will be removed (exclusived) The Object has been initialized.
References Dali::CUSTOM_CONSTRAINT_TAG_MAX, DALI_ASSERT_ALWAYS, Dali::GetImplementation.
IndirectValue Dali::Handle::operator[](Property::Index index)
Index operator, using integer lookup.
Returns an object that can be assigned to or cast from, enabling the indexed property to be either read or written. index The index of the property to access. indirect value. Should have shorter scope than the handle
IndirectValue Dali::Handle::operator[](Dali::String name)
Index operator, using name lookup.
Returns an object that can be assigned to or cast from, enabling the named property to be either read or written. name The name of the property to access. indirect value. Should have shorter scope than the handle
References GetPropertyIndex, Dali::Property::Key.
Handle::PropertySetSignalType & Dali::Handle::PropertySetSignal()
Get a signal when a property is set on this object through the API (i.e. not when animating)
@SINCE_1_9.27 The signal to attach a connection to.
References Dali::GetImplementation.
Handle Dali::Handle::New()
Creates a new object.
@SINCE_1_0.0 A handle to a newly allocated object
References Handle.
Referenced by Dali::WeightObject::New.
static DALI_NO_EXPORT_API Type Dali::Handle::New(const Property::Map &properties)
Template to create a derived handle and set properties on it.
Marked as DALI_NO_EXPORT_API to prevent internal usage exporting symbols. @SINCE_1_9.27 T The derived class to create properties The properties to set
Handle Dali::Handle::DownCast(BaseHandle handle)
Downcasts to a handle.
If not, the returned handle is left uninitialized. @SINCE_1_0.0 handle to An object handle or an uninitialized handle
References Dali::BaseHandle::GetObjectPtr, Handle.