Dali::Integration::OrderedSet
using Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::ListContainer = typename std::list<T*>
using Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Iterator = typename ListContainer::iterator
using Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::ConstIterator = typename ListContainer::const_iterator
using Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::MapContainer = typename Dali::Integration::OpenHashMap<const T*, Iterator, Hash, KeyEqual>
using Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::SizeType = uint32_t
MapContainer Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::mMap
Helper cache map to find item fast.
ListContainer Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::mList
Ordered by PushBack API called. Actual ownership will be stored here.
Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::OrderedSet()=default
Construct a new OrderedSet object.
Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::OrderedSet(OrderedSet &&rhs) noexcept
Move construct.
OrderedSet & Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::operator=(OrderedSet &&rhs) noexcept
Move assign.
References Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Clear.
Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::~OrderedSet()
References Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Clear.
Iterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Begin()
Iterator of begin & end.
Referenced by Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::begin, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::begin.
Iterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::End()
Referenced by Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::end, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::end, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Find, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Find, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::PushBack.
ConstIterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Begin() const
ConstIterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::End() const
Iterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::begin()
References Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Begin.
Iterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::end()
References Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::End.
ConstIterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::begin() const
References Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Begin.
ConstIterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::end() const
References Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::End.
SizeType Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Count() const
Get the number of elements.
The number of elements that this container owned.
bool Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::IsEmpty() const
Predicate to determine if the container is empty.
true if the container is empty
void Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Reserve(SizeType count)
Reserves space in the ordered set.
count Count of elements to reserve
Iterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Find(T *object)
Find and get iterator of object. If not exist, return End().
object The object pointer what we want to find. Iterator of object, or End().
References Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::End.
Referenced by Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::EraseObject, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::EraseObject, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::PushBack.
ConstIterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Find(const T *object) const
References Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::End.
void Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::PushBack(T *object)
PushBack and keep ownership of object.
Iterator will keep order of PushBack API call. object The object pointer what we want to insert.
References DALI_ASSERT_DEBUG, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::End, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Find.
void Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::EraseObject(T *object)
Erase and remove memory of object.
object The object pointer what we want to erase.
References Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Erase, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Find.
void Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::EraseObject(const T *object)
References Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Erase, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Find.
Iterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Erase(Iterator iter)
Erase and remove memory of object by iterator.
iter The iterator what we want to erase.
References DALI_ASSERT_DEBUG.
Referenced by Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::EraseObject, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::EraseObject.
ConstIterator Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Erase(ConstIterator iter)
References DALI_ASSERT_DEBUG.
T * Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Release(Iterator iter)
Release and move ownership of object. This API do not remove memory.
iterators are invalidated by this method. iter The iterator what we want to release.
References DALI_ASSERT_DEBUG.
T * Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Release(ConstIterator iter)
References DALI_ASSERT_DEBUG.
void Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::Clear()
Remove all data and release memory if we owned data.
Referenced by Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::operator=, Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::~OrderedSet.
void Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::ReorderCacheMap()
Reorder cache map. It should be called after the value of mList changed.
Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::OrderedSet(const OrderedSet &)=delete
OrderedSet & Dali::Integration::OrderedSet< T, owned, Hash, KeyEqual >::operator=(const OrderedSet &)=delete