Dali::ManagedOpenHashMap
using Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::InsertResult = Dali::Pair<Value*, bool>
Result type returned by TryInsert.
Equivalent to the std::pair<iterator, bool> returned by std::unordered_map::insert: first : pointer to the value for the key (never null) second : true if a new entry was inserted, false if the key already existed Uses Dali::Pair so callers get the full Dali::Pair interface (comparison operators, Swap, MakePair) and the familiar first/second field names without depending on any bespoke type. @SINCE_2_5.20
constexpr uint32_t Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::INITIAL_CAPACITY
Entry* Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::mEntries
uint32_t Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::mCapacity
uint32_t Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::mSize
Live entries.
uint32_t Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::mOccupied
Live entries + tombstones (drives load-factor check).
DALI_NO_UNIQUE_ADDRESS Hash Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::mHash
DALI_NO_UNIQUE_ADDRESS KeyEqual Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::mKeyEqual
Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::ManagedOpenHashMap()=default
Default constructor.
Creates an empty map with no allocated table (capacity 0). The table is allocated on the first Insert. @SINCE_2_5.20
Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::~ManagedOpenHashMap()
Destructor.
Destroys all live key-value pairs and frees the entry table. @SINCE_2_5.20
Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::ManagedOpenHashMap(const ManagedOpenHashMap &)=delete
Copy constructor is deleted.
ManagedOpenHashMap is not copyable because copying a hash map with non-trivial key/value types is expensive and easily done unintentionally. Use move semantics or manually copy entries via ForEach() + Insert(). @SINCE_2_5.20
ManagedOpenHashMap & Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::operator=(const ManagedOpenHashMap &)=delete
Copy assignment operator is deleted.
ManagedOpenHashMap is not copy-assignable for the same reason as the copy constructor. @SINCE_2_5.20
Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::ManagedOpenHashMap(ManagedOpenHashMap &&rhs) noexcept(IsNothrowMoveConstructible< Hash >::value &&IsNothrowMoveConstructible< KeyEqual >::value)
Move constructor.
Transfers ownership of the entry table from rhs to this map. After the move, rhs is in a valid empty state (size 0, capacity 0). noexcept is conditional on Hash and KeyEqual being nothrow-move-constructible. If either functor's move constructor can throw, std::terminate would be called. rhs The map to move from @SINCE_2_5.20
ManagedOpenHashMap & Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::operator=(ManagedOpenHashMap &&rhs) noexcept(IsNothrowMoveAssignable< Hash >::value &&IsNothrowMoveAssignable< KeyEqual >::value)
Move assignment operator.
Frees this map's current entry table, then transfers ownership of the entry table from rhs. After the move, rhs is in a valid empty state (size 0, capacity 0). noexcept is conditional on Hash and KeyEqual being nothrow-move-assignable. rhs The map to move from Reference to this map @SINCE_2_5.20
References Dali::Move.
Value * Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Insert(const Key &key, const Value &value)
Insert or update a key-value pair (copy both).
WARNING: Unlike std::unordered_map::insert(), this always overwrites an existing value when the key is already present. Use TryInsert() for insert-if-absent semantics. WARNING: Any pointer or iterator obtained before this call may be invalidated if the insert triggers a table grow. key The key to insert value The value to associate Pointer to the inserted/updated entry's value @SINCE_2_5.20
Value * Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Insert(Key &&key, Value &&value)
Insert or update a key-value pair (move both).
WARNING: Unlike std::unordered_map::insert(), this always overwrites an existing value when the key is already present. Use TryInsert() for insert-if-absent semantics. WARNING: Any pointer or iterator obtained before this call may be invalidated if the insert triggers a table grow. key The key to insert (rvalue reference) value The value to associate (rvalue reference) Pointer to the inserted/updated entry's value @SINCE_2_5.20
References Dali::Move.
Value * Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Insert(Key &&key, const Value &value)
Insert or update a key-value pair (move key, copy value).
WARNING: Unlike std::unordered_map::insert(), this always overwrites an existing value when the key is already present. Use TryInsert() for insert-if-absent semantics. WARNING: Any pointer or iterator obtained before this call may be invalidated if the insert triggers a table grow. key The key to insert (rvalue reference) value The value to associate Pointer to the inserted/updated entry's value @SINCE_2_5.20
References Dali::Move.
Value * Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Insert(const Key &key, Value &&value)
Insert or update a key-value pair (copy key, move value).
WARNING: Unlike std::unordered_map::insert(), this always overwrites an existing value when the key is already present. Use TryInsert() for insert-if-absent semantics. WARNING: Any pointer or iterator obtained before this call may be invalidated if the insert triggers a table grow. key The key to insert value The value to associate (rvalue reference) Pointer to the inserted/updated entry's value @SINCE_2_5.20
References Dali::Move.
Value & Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::operator[](const Key &key)
Access or insert a value by key.
If the key is present, returns a reference to the existing value unchanged. If the key is absent, inserts a default-constructed Value and returns a reference to it. This matches std::unordered_map::operator[] exactly. Implementation note: routes through TryInsertImpl (not InsertImpl) so that an existing value is never overwritten by a default-constructed Value{}. Using InsertImpl here would silently reset an existing value to Value{} on every operator[] access for a key that is already present. WARNING: Any reference obtained before this call may be invalidated if the call triggers a table grow. key The key to look up or insert Reference to the value associated with key @SINCE_2_5.20
Value & Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::At(const Key &key)
Access a value by key with an assertion on miss (non-const).
Equivalent to std::unordered_map::at() but calls DALI_ASSERT_ALWAYS instead of throwing std::out_of_range when the key is absent. Does NOT insert a default value for missing keys (unlike operator[]). key The key to look up Reference to the value associated with key @SINCE_2_5.20
References DALI_ASSERT_ALWAYS, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Find.
const Value & Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::At(const Key &key) const
Access a value by key with an assertion on miss (const).
Equivalent to std::unordered_map::at() const but calls DALI_ASSERT_ALWAYS instead of throwing std::out_of_range when the key is absent. key The key to look up Const reference to the value associated with key @SINCE_2_5.20
References DALI_ASSERT_ALWAYS, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Find.
InsertResult Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::TryInsert(const Key &key, const Value &value)
Insert a key-value pair only if the key is absent (copy both).
Equivalent to std::unordered_map::insert(). Unlike Insert(), this never overwrites an existing value. If the key is already present, the existing value is left unchanged. WARNING: Any pointer or iterator obtained before this call may be invalidated if the insert triggers a table grow. key The key to insert value The value to associate InsertResult::first — pointer to the value (existing or newly inserted) InsertResult::second — true if inserted, false if key already existed @SINCE_2_5.20
InsertResult Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::TryInsert(Key &&key, Value &&value)
Insert a key-value pair only if the key is absent (move both).
key The key to insert (rvalue reference) value The value to associate (rvalue reference) InsertResult @SINCE_2_5.20
References Dali::Move.
InsertResult Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::TryInsert(Key &&key, const Value &value)
Insert a key-value pair only if the key is absent (move key, copy value).
key The key to insert (rvalue reference) value The value to associate InsertResult @SINCE_2_5.20
References Dali::Move.
InsertResult Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::TryInsert(const Key &key, Value &&value)
Insert a key-value pair only if the key is absent (copy key, move value).
key The key to insert value The value to associate (rvalue reference) InsertResult @SINCE_2_5.20
References Dali::Move.
Value * Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Find(const Key &key)
Find a value by key.
key The key to look up Pointer to the value, or nullptr if not found @SINCE_2_5.20
References Dali::EMPTY, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::key, Dali::OCCUPIED, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::state, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::value.
Referenced by Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::At, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::At, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Contains.
const Value * Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Find(const Key &key) const
Find a value by key (const).
key The key to look up Pointer to the value, or nullptr if not found @SINCE_2_5.20
References Dali::EMPTY, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::key, Dali::OCCUPIED, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::state, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::value.
bool Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Erase(const Key &key)
Erase an entry by key.
key The key to erase true if the key was found and erased, false otherwise @SINCE_2_5.20
References Dali::EMPTY, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::key, Dali::OCCUPIED, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::state, Dali::TOMBSTONE.
void Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Clear()
Mark all entries as empty.
Every slot (OCCUPIED or TOMBSTONE) is reset to EMPTY and the size counters are zeroed. The table buffer itself is retained for reuse. Key and Value objects in formerly-occupied slots are left in their current state: they will be overwritten when the slot is reused by a subsequent Insert, or destroyed when the table is freed. If you need resources released immediately rather than lazily, follow this call with Rehash(), which frees the entire table when size is zero: map.Clear(); map.Rehash();//releasesthetablebufferandallKey/Valuestorageimmediately @SINCE_2_5.20
References Dali::EMPTY, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::state.
void Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::ForEach(Functor &&functor)
Call a functor for each live entry.
functor Called with (const Key& key, Value& value) for each entry @SINCE_2_5.20
References Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::key, Dali::OCCUPIED, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::state, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::value.
void Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::ForEach(Functor &&functor) const
Call a functor for each live entry (const version).
functor Called with (const Key& key, const Value& value) for each entry @SINCE_2_5.20
References Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::key, Dali::OCCUPIED, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::state, Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Entry::value.
uint32_t Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Size() const
Number of live entries. @SINCE_2_5.20
bool Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Empty() const
true if there are no live entries. @SINCE_2_5.20
uint32_t Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Capacity() const
Current table capacity (always a power of 2, or 0). @SINCE_2_5.20
bool Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Contains(const Key &key) const
Test whether a key exists in the map.
Equivalent to std::unordered_map::contains() (C++20). key The key to test true if the key is present, false otherwise @SINCE_2_5.20
References Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Find.
Referenced by Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Count.
uint32_t Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Count(const Key &key) const
Return the number of entries with the given key (0 or 1).
Equivalent to std::unordered_map::count(). Since this is a map (not a multimap), the return value is always 0 or 1. key The key to count 1 if the key is present, 0 otherwise @SINCE_2_5.20
References Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Contains.
Iterator Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::begin()
Return an iterator to the first live entry.
Iteration order is unspecified (depends on hash distribution). The iterator is invalidated by any operation that may grow or rehash the table. @SINCE_2_5.20
Iterator Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::end()
Return a past-the-end iterator. @SINCE_2_5.20.
ConstIterator Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::begin() const
Return a const iterator to the first live entry. @SINCE_2_5.20.
ConstIterator Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::end() const
Return a past-the-end const iterator. @SINCE_2_5.20.
ConstIterator Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::cbegin() const
Return a const iterator to the first live entry (explicit const). @SINCE_2_5.20.
ConstIterator Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::cend() const
Return a past-the-end const iterator (explicit const). @SINCE_2_5.20.
void Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Rehash(uint32_t targetCapacity=0u)
Resize the table to the smallest power-of-2 capacity that keeps load under 75%, clearing all tombstones in the process.
If the input capacity is bigger than zero, the table will be resized to at least that capacity (rounded up to the next power of 2). If the map is empty and targetCapacity is 0, the table is freed entirely (capacity becomes 0). This releases all Key/Value storage immediately via delete[], which is the recommended way to eagerly release resources after Clear(): map.Clear(); map.Rehash();//freesthetablebuffer,destructingallKey/Valueobjects If the current capacity is already optimal, this is a no-op (unless there are tombstones, in which case an in-place rehash clears them). Provides the strong exception guarantee: if RehashTo throws during the copy, the map is left unchanged. WARNING: Invalidates all pointers, references, and iterators obtained before this call. targetCapacity Minimum desired capacity (0 to shrink to fit). @SINCE_2_5.20
References Dali::Max, Dali::NextPowerOfTwo.
uint32_t Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::HashIndex(const Key &key, uint32_t mask) const
Hash a key and return a table index.
Applies a finalizer (splitmix64-style) to the raw hash to improve bit distribution for linear probing with power-of-2 table sizes.
void Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::Grow()
void Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::RehashTo(uint32_t newCapacity)
Rehash the table to a new capacity.
Always copies (never moves) live entries into the new table so that the old table remains completely untouched until the full copy succeeds and the swap is committed. Trade-off: rehash always performs O(n) copy work rather than O(n) move work for nothrow-movable types. This is acceptable because rehashing is amortised and infrequent, and correctness is not compromised. If the application profile shows rehash to be a measurable hot path and all Key/Value types used are guaranteed nothrow-movable, this policy can be revisited by re-adding a MoveIfNoexcept path — but only after the old table has been fully abandoned (i.e. move everything first with no fallback, accepting the basic guarantee only).
Value * Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::InsertImpl(K &&key, V &&value)
Unified insert implementation that forwards key/value perfectly.
InsertResult Dali::ManagedOpenHashMap< Key, Value, Hash, KeyEqual >::TryInsertImpl(K &&key, V &&value)
Unified insert-or-ignore implementation.
Like InsertImpl but never overwrites an existing value. Returns {ptr, true} on insertion, {ptr, false} if key was already present.