Dali::Any::AnyContainerBase
TypeInfoId Dali::Any::AnyContainerBase::mType
Referenced by GetType.
CloneFunc Dali::Any::AnyContainerBase::mCloneFunc
Referenced by Dali::Any::Any, Dali::Any::operator=.
DeleteFunc Dali::Any::AnyContainerBase::mDeleteFunc
Referenced by Dali::Any::operator=, Dali::Any::operator=, Dali::Any::~Any.
Dali::Any::AnyContainerBase::AnyContainerBase(TypeInfoId type, CloneFunc cloneFunc, DeleteFunc deleteFunc)
Constructor of base container.
@SINCE_1_0.0 type TypeInfoId of container cloneFunc Cloning function to replicate this container type deleteFunc Deleting function to destroy this container type
const TypeInfoId & Dali::Any::AnyContainerBase::GetType() const
Gets the TypeInfoId of this container.
@SINCE_1_0.0 Type
References mType.
Referenced by Dali::Any::Get, Dali::Any::GetPointer, Dali::Any::GetPointer, Dali::Any::GetType, Dali::Any::IsType, Dali::Any::operator=, Dali::Any::operator=.